CREATE TABLE [dbo].[EXCELDB] (
    [ITEM]       NVARCHAR (50) NULL,
    [CHARACT]    NVARCHAR (50) NULL,
    [TYPE]       NVARCHAR (50) NULL,
    [UNIT]       NVARCHAR (50) NULL,
    [NOMINAL]    NVARCHAR (50) NULL,
    [UPPER]      NVARCHAR (50) NULL,
    [LOWER]      NVARCHAR (50) NULL,
    [HYSTERESIS] NVARCHAR (50) NULL,
    [REQUIRED]   NVARCHAR (50) NULL,
    [CATALOG]    NVARCHAR (50) NULL
);

