CREATE TABLE [PRD].[C_CARTON_ITEM] (
    [ID_CARTON_ITEM]       INT           IDENTITY (1, 1) NOT NULL,
    [ID_ITEM]              INT           NOT NULL,
    [ID_CARTON]            INT           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]    NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_CARTON_ITEM] PRIMARY KEY CLUSTERED ([ID_CARTON_ITEM] ASC),
    CONSTRAINT [FK_C_CARTON_ITEM_C_ITEM] FOREIGN KEY ([ID_ITEM]) REFERENCES [PRD].[C_ITEM] ([ID_ITEM]),
    CONSTRAINT [FK_C_CARTON_ITEM_C_VALUE_CATALOG] FOREIGN KEY ([ID_CARTON]) REFERENCES [ADM].[C_VALUE_CATALOG] ([ID_VALUE_CATALOG])
);

