CREATE TABLE [PRD].[C_CODES_POSITION_ALERT] (
    [ID_POSITION_CODE]     INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROBLEM_CODE]      INT           NOT NULL,
    [ID_POSITION]          INT           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]    NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_CODES_POSITION_ALERT] PRIMARY KEY CLUSTERED ([ID_POSITION_CODE] ASC),
    CONSTRAINT [FK_C_CODES_POSITION_ALERT_C_POSITION] FOREIGN KEY ([ID_POSITION]) REFERENCES [ADM].[C_POSITION] ([ID_POSITION]),
    CONSTRAINT [FK_C_CODES_POSITION_ALERT_C_PROBLEM_CODE] FOREIGN KEY ([ID_PROBLEM_CODE]) REFERENCES [PRD].[C_PROBLEM_CODE] ([ID_PROBLEM_CODE])
);

