CREATE TABLE [PRD].[C_DEVICE_METRICS] (
    [ID_DEVICE_METRICS]    INT            IDENTITY (1, 1) NOT NULL,
    [ID_DEVICE]            INT            NOT NULL,
    [ID_METRICS]           INT            NOT NULL,
    [NO_REGISTER]          NVARCHAR (100) NOT NULL,
    [KY_MODBUS_DATATYPE]   NVARCHAR (15)  NOT NULL,
    [KY_SCALING_TYPE]      NVARCHAR (10)  NOT NULL,
    [NO_RAW_HI]            NVARCHAR (15)  NULL,
    [NO_RAW_LO]            NVARCHAR (15)  NULL,
    [NO_SCALE_HI]          NVARCHAR (15)  NULL,
    [NO_SCALE_LO]          NVARCHAR (15)  NULL,
    [FG_CLAMP_HI]          BIT            NULL,
    [FG_CLAMP_LO]          BIT            NULL,
    [DT_CREATION]          DATETIME       NOT NULL,
    [DT_UPDATE]            DATETIME       NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_DEVICE_METRICS] PRIMARY KEY CLUSTERED ([ID_DEVICE_METRICS] ASC),
    CONSTRAINT [FK_C_DEVICE_METRICS_C_METRICS] FOREIGN KEY ([ID_METRICS]) REFERENCES [PRD].[C_METRICS] ([ID_METRICS])
);

