CREATE TABLE [PRD].[C_DEVICE] (
    [ID_DEVICE]            INT             IDENTITY (1, 1) NOT NULL,
    [KY_DEVICE]            NVARCHAR (100)  NOT NULL,
    [NM_DEVICE]            NVARCHAR (300)  NOT NULL,
    [DS_DEVICE]            NVARCHAR (1000) NULL,
    [ID_BRANCH_PLANT]      INT             NULL,
    [NO_IP]                NVARCHAR (20)   NOT NULL,
    [NO_PORT]              NVARCHAR (4)    NOT NULL,
    [FG_ACTIVE]            BIT             CONSTRAINT [DF_C_DEVICE_FG_ACTIVE] DEFAULT ((1)) NOT NULL,
    [DT_CREATION]          DATETIME        NOT NULL,
    [DT_UPDATE]            DATETIME        NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)   NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)   NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)   NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_C_DEVICE] PRIMARY KEY CLUSTERED ([ID_DEVICE] ASC),
    CONSTRAINT [FK_C_DEVICE_C_BRANCH_PLANT] FOREIGN KEY ([ID_BRANCH_PLANT]) REFERENCES [ADM].[C_BRANCH_PLANT] ([ID_BRANCH_PLANT])
);

