CREATE TABLE [PRD].[C_LINE_METRIC] (
    [ID_LINE_METRIC]       INT           IDENTITY (1, 1) NOT NULL,
    [ID_PRODUCTION_LINE]   INT           NOT NULL,
    [ID_METRICS]           INT           NOT NULL,
    [XML_FIELD_SETTINGS]   XML           NOT NULL,
    [ID_DEVICE_METRICS]    INT           NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_LINE_METRIC] PRIMARY KEY CLUSTERED ([ID_LINE_METRIC] ASC),
    CONSTRAINT [FK_C_LINE_METRIC_C_DEVICE_METRICS] FOREIGN KEY ([ID_DEVICE_METRICS]) REFERENCES [PRD].[C_DEVICE_METRICS] ([ID_DEVICE_METRICS]),
    CONSTRAINT [FK_C_LINE_METRIC_C_METRICS] FOREIGN KEY ([ID_METRICS]) REFERENCES [PRD].[C_METRICS] ([ID_METRICS]),
    CONSTRAINT [FK_C_LINE_METRIC_C_PRODUCTION_LINE] FOREIGN KEY ([ID_PRODUCTION_LINE]) REFERENCES [PRD].[C_PRODUCTION_LINE] ([ID_PRODUCTION_LINE])
);

