CREATE TABLE [PRD].[C_METRICS] (
    [ID_METRICS]           INT             IDENTITY (1, 1) NOT NULL,
    [KY_METRICS]           NVARCHAR (50)   NOT NULL,
    [NM_METRICS]           NVARCHAR (1000) NULL,
    [KY_FIELD_TYPE]        NVARCHAR (10)   NOT NULL,
    [FG_ENABLED]           BIT             CONSTRAINT [DF_C_METRICS_FG_ENABLED] DEFAULT ((1)) NOT NULL,
    [FG_REQUIRED]          BIT             CONSTRAINT [DF_C_METRICS_FG_REQUIRED] DEFAULT ((1)) NOT NULL,
    [DS_TOOLTIP]           NVARCHAR (1000) NULL,
    [ID_BRANCH_PLANT]      INT             NULL,
    [XML_FIELD_SETTINGS]   XML             NOT NULL,
    [NO_ORDER]             INT             NULL,
    [DT_CREATION]          DATETIME        NOT NULL,
    [DT_UPDATE]            DATETIME        NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)   NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)   NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)   NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_C_METRICS] PRIMARY KEY CLUSTERED ([ID_METRICS] ASC),
    CONSTRAINT [FK_C_METRICS_C_BRANCH_PLANT] FOREIGN KEY ([ID_BRANCH_PLANT]) REFERENCES [ADM].[C_BRANCH_PLANT] ([ID_BRANCH_PLANT])
);

