CREATE TABLE [PRD].[C_PRODUCTION_LINE_IP] (
    [ID_PRODUCTION_LINE_IP] INT           IDENTITY (1, 1) NOT NULL,
    [ID_PRODUCTION_LINE]    INT           NOT NULL,
    [NO_IP]                 NVARCHAR (40) NOT NULL,
    [DT_CREATION]           DATETIME      NOT NULL,
    [DT_UPDATE]             DATETIME      NULL,
    [KY_USER_APP_CREATION]  NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]    NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_PRODUCTION_LINE_IP] PRIMARY KEY CLUSTERED ([ID_PRODUCTION_LINE_IP] ASC),
    CONSTRAINT [FK_C_PRODUCTION_LINE_IP_C_PRODUCTION_LINE] FOREIGN KEY ([ID_PRODUCTION_LINE]) REFERENCES [PRD].[C_PRODUCTION_LINE] ([ID_PRODUCTION_LINE])
);

