CREATE TABLE [PRD].[C_PRODUCTION_LINE_OPERATOR] (
    [ID_PRODUCTION_LINE_OPERATOR] INT IDENTITY (1, 1) NOT NULL,
    [ID_EMPLOYEE]                 INT NOT NULL,
    [ID_PRODUCTION_LINE]          INT NOT NULL,
    CONSTRAINT [PK_C_PRODUCTION_LINE_OPERATOR] PRIMARY KEY CLUSTERED ([ID_PRODUCTION_LINE_OPERATOR] ASC),
    CONSTRAINT [FK_C_PRODUCTION_LINE_OPERATOR_C_EMPLOYEE] FOREIGN KEY ([ID_EMPLOYEE]) REFERENCES [ADM].[C_EMPLOYEE] ([ID_EMPLOYEE]),
    CONSTRAINT [FK_C_PRODUCTION_LINE_OPERATOR_C_PRODUCTION_LINE] FOREIGN KEY ([ID_PRODUCTION_LINE]) REFERENCES [PRD].[C_PRODUCTION_LINE] ([ID_PRODUCTION_LINE])
);

