CREATE TABLE [PRD].[C_SWITCH_REPORT] (
    [ID_REPORT]       INT           IDENTITY (1, 1) NOT NULL,
    [NM_REPORT]       VARCHAR (100) NULL,
    [FG_SWITCH]       BIT           NULL,
    [KY_BRANCH_PLANT] VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID_REPORT] ASC)
);

