CREATE TABLE [PRD].[C_TRANSITION] (
    [ID_TRANSITION]        INT             IDENTITY (1, 1) NOT NULL,
    [KY_TRANSITION]        NVARCHAR (50)   NOT NULL,
    [NM_TRANSITION]        NVARCHAR (100)  NOT NULL,
    [DS_TRANSITION]        NVARCHAR (1000) NULL,
    [NO_STANDARD_TIME]     INT             CONSTRAINT [DF_C_TRANSITION_NO_STANDARD_TIME] DEFAULT ((0)) NOT NULL,
    [FG_ACTIVE]            BIT             CONSTRAINT [DF_C_TRANSITION_FG_ACTIVE] DEFAULT ((1)) NOT NULL,
    [FG_IS_TOOL_CHANGE]    BIT             NULL,
    [DT_INACTIVE]          DATETIME        NULL,
    [DT_CREATION]          DATETIME        NOT NULL,
    [DT_UPDATE]            DATETIME        NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)   NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)   NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)   NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)   NULL,
    [ID_BRANCH_PLANT]      INT             NULL,
    CONSTRAINT [PK_C_TRANSITION] PRIMARY KEY CLUSTERED ([ID_TRANSITION] ASC),
    FOREIGN KEY ([ID_BRANCH_PLANT]) REFERENCES [ADM].[C_BRANCH_PLANT] ([ID_BRANCH_PLANT])
);

