CREATE TABLE [PRD].[K_DISTRIBUTION_LIST] (
    [ID_DISTRIBUTION_LIST] INT           IDENTITY (1, 1) NOT NULL,
    [NM_DISTRIBUTION]      VARCHAR (100) NULL,
    [KY_DISTRIBUTION]      VARCHAR (100) NULL,
    [KY_USER_APP_CREATION] VARCHAR (20)  NOT NULL,
    [KY_USER_APP_UPDATE]   VARCHAR (20)  NULL,
    [NM_PROGAM_CREATE]     VARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    VARCHAR (50)  NULL,
    [ID_TYPE_EVENT]        INT           NULL,
    PRIMARY KEY CLUSTERED ([ID_DISTRIBUTION_LIST] ASC)
);

