CREATE TABLE [PRD].[K_EVENT_TABLE] (
    [ID_EVENT]   INT           IDENTITY (1, 1) NOT NULL,
    [EVENT_NAME] VARCHAR (200) NOT NULL,
    [KEY_EVENT]  VARCHAR (200) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_EVENT] ASC)
);

