CREATE TABLE [PRD].[K_FORM_METRICS] (
    [ID_K_FORM_METRICS]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_K_FORM]            INT           NOT NULL,
    [ID_METRICS]           INT           NOT NULL,
    [XML_METRICS_VALUE]    XML           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_FORM_METRICS] PRIMARY KEY CLUSTERED ([ID_K_FORM_METRICS] ASC),
    CONSTRAINT [FK_K_FORM_METRICS_C_METRICS] FOREIGN KEY ([ID_METRICS]) REFERENCES [PRD].[C_METRICS] ([ID_METRICS]),
    CONSTRAINT [FK_K_FORM_METRICS_K_FORM] FOREIGN KEY ([ID_K_FORM]) REFERENCES [PRD].[K_FORM] ([ID_K_FORM])
);


GO
CREATE NONCLUSTERED INDEX [IX_K_FORM_METRICS_ID_K_FORM_ID_METRICS]
    ON [PRD].[K_FORM_METRICS]([ID_K_FORM] ASC, [ID_METRICS] ASC)
    INCLUDE([XML_METRICS_VALUE]);

