CREATE TABLE [PRD].[K_FOREMAN_AUTHORIZATION] (
    [ID_FOREMAN_AUTHORIZATION] INT           IDENTITY (1, 1) NOT NULL,
    [KY_USER_FOREMAN]          NVARCHAR (80) NOT NULL,
    [KY_SHIFT]                 NVARCHAR (50) NOT NULL,
    [DT_SYSTEM]                DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_FOREMAN_AUTHORIZATION] ASC)
);

