CREATE TABLE [PRD].[K_INSPECTION_SKID_LOG] (
    [ID_SKID_LOG]          INT            IDENTITY (1, 1) NOT NULL,
    [ID_INSPECTION_SKID]   INT            NOT NULL,
    [ID_WORK_ORDER]        INT            NOT NULL,
    [NO_SKID]              INT            NOT NULL,
    [KY_USER]              NVARCHAR (50)  NOT NULL,
    [XML_AUTHORIZER_USERS] XML            NULL,
    [DS_COMMENT]           NVARCHAR (500) NULL,
    [DT_CREATION]          DATETIME       NOT NULL,
    [DT_UPDATE]            DATETIME       NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)  NULL,
    [NM_ORIGIN_STATUS]     VARCHAR (50)   NULL,
    CONSTRAINT [PK_K_INSPECTION_SKID_LOG] PRIMARY KEY CLUSTERED ([ID_SKID_LOG] ASC),
    CONSTRAINT [FK_K_INSPECTION_SKID_LOG_K_INSPECTION_SKID] FOREIGN KEY ([ID_INSPECTION_SKID]) REFERENCES [PRD].[K_INSPECTION_SKID] ([ID_INSPECTION_SKID]),
    CONSTRAINT [FK_K_INSPECTION_SKID_LOG_K_WORK_ORDER] FOREIGN KEY ([ID_WORK_ORDER]) REFERENCES [PRD].[K_WORK_ORDER] ([ID_WORK_ORDER])
);

