CREATE TABLE [PRD].[K_ISSUE] (
    [ID_ISSUE]                    INT              IDENTITY (1, 1) NOT NULL,
    [KY_ISSUE]                    UNIQUEIDENTIFIER NULL,
    [ID_QA27]                     INT              NOT NULL,
    [ID_WORK_ORDER]               INT              NOT NULL,
    [ID_PRODUCTION_LINE]          INT              NULL,
    [ID_PROBLEM_AREA]             INT              NOT NULL,
    [ID_PROBLEM_CODE]             INT              NOT NULL,
    [DS_SYMPTOM]                  NVARCHAR (1000)  NOT NULL,
    [XML_POSITIONS_INVOLVED]      XML              NULL,
    [KY_USER_INVOLVED]            NVARCHAR (50)    NULL,
    [DS_ISSUE_EXPLANATION_OPEN]   TEXT             NULL,
    [DT_ISSUE]                    DATETIME         NOT NULL,
    [FG_CONFIRMED]                BIT              CONSTRAINT [DF_K_ISSUE_FG_CONFIRMED] DEFAULT ((0)) NOT NULL,
    [DT_CONFIRMED]                DATETIME         NULL,
    [ID_DEFECT_CATEGORY]          INT              NULL,
    [DS_EXPLANATION_EVENT_CLOSED] NVARCHAR (1000)  NULL,
    [DT_ISSUE_CLOSED]             DATETIME         NULL,
    [KY_STATUS]                   NVARCHAR (50)    NOT NULL,
    [NO_TIME_BEFORE_HELP]         INT              NULL,
    [FG_LINE_DOWN]                BIT              CONSTRAINT [DF_K_ISSUE_FG_LINE_DOWN] DEFAULT ((0)) NOT NULL,
    [DT_CREATION]                 DATETIME         NOT NULL,
    [DT_UPDATE]                   DATETIME         NULL,
    [KY_USER_APP_CREATION]        NVARCHAR (50)    NOT NULL,
    [KY_USER_APP_UPDATE]          NVARCHAR (50)    NULL,
    [NM_PROGAM_CREATE]            NVARCHAR (50)    NOT NULL,
    [NM_PROGRAM_UPDATE]           NVARCHAR (50)    NULL,
    [FG_EMAIL_SENDED]             BIT              NULL,
    CONSTRAINT [PK_K_ISSUE] PRIMARY KEY CLUSTERED ([ID_ISSUE] ASC),
    CONSTRAINT [FK_K_ISSUE_C_PROBLEM_AREA] FOREIGN KEY ([ID_PROBLEM_AREA]) REFERENCES [PRD].[C_PROBLEM_AREA] ([ID_PROBLEM_AREA]),
    CONSTRAINT [FK_K_ISSUE_C_PROBLEM_CODE] FOREIGN KEY ([ID_PROBLEM_CODE]) REFERENCES [PRD].[C_PROBLEM_CODE] ([ID_PROBLEM_CODE]),
    CONSTRAINT [FK_K_ISSUE_C_PRODUCTION_LINE] FOREIGN KEY ([ID_PRODUCTION_LINE]) REFERENCES [PRD].[C_PRODUCTION_LINE] ([ID_PRODUCTION_LINE]),
    CONSTRAINT [FK_K_ISSUE_C_USER] FOREIGN KEY ([KY_USER_INVOLVED]) REFERENCES [ADM].[C_USER] ([KY_USER]),
    CONSTRAINT [FK_K_ISSUE_K_QA27] FOREIGN KEY ([ID_QA27]) REFERENCES [PRD].[K_QA27] ([ID_QA27]),
    CONSTRAINT [FK_K_ISSUE_K_WORK_ORDER] FOREIGN KEY ([ID_WORK_ORDER]) REFERENCES [PRD].[K_WORK_ORDER] ([ID_WORK_ORDER])
);


GO
CREATE NONCLUSTERED INDEX [IX_K_ISSUE_FG_LINE_DOWN]
    ON [PRD].[K_ISSUE]([FG_LINE_DOWN] ASC)
    INCLUDE([ID_PRODUCTION_LINE], [DT_ISSUE], [DT_ISSUE_CLOSED]);


GO
CREATE NONCLUSTERED INDEX [IX_K_ISSUE_ID_WORK_ORDER_FG_LINE_DOWN]
    ON [PRD].[K_ISSUE]([ID_WORK_ORDER] ASC, [FG_LINE_DOWN] ASC);

