CREATE TABLE [PRD].[K_LOG] (
    [ID_LOG]               INT             IDENTITY (1, 1) NOT NULL,
    [LOG_TYPE]             NVARCHAR (50)   NULL,
    [DS_LOG]               NVARCHAR (1000) NOT NULL,
    [XML_REFERENCE]        XML             NOT NULL,
    [ID_BRANCH_PLANT]      INT             NULL,
    [DT_CREATION]          DATETIME        NOT NULL,
    [DT_UPDATE]            DATETIME        NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)   NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)   NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)   NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_K_LOG] PRIMARY KEY CLUSTERED ([ID_LOG] ASC),
    CONSTRAINT [FK_K_LOG_C_BRANCH_PLANT] FOREIGN KEY ([ID_BRANCH_PLANT]) REFERENCES [ADM].[C_BRANCH_PLANT] ([ID_BRANCH_PLANT])
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20180914-124332]
    ON [PRD].[K_LOG]([DT_CREATION] ASC);

