CREATE TABLE [PRD].[K_METRICS_READINGS] (
    [ID_K_METRICS_READINGS] INT           IDENTITY (1, 1) NOT NULL,
    [ID_K_READING]          INT           NOT NULL,
    [ID_METRICS]            INT           NOT NULL,
    [NO_VALUE]              FLOAT (53)    NOT NULL,
    [KY_STATUS_READING]     NCHAR (50)    NOT NULL,
    [DT_CREATION]           DATETIME      NOT NULL,
    [DT_UPDATE]             DATETIME      NULL,
    [KY_USER_APP_CREATION]  NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]    NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]      NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_METRICS_READINGS] PRIMARY KEY CLUSTERED ([ID_K_METRICS_READINGS] ASC),
    CONSTRAINT [FK_K_METRICS_READINGS_C_METRICS] FOREIGN KEY ([ID_METRICS]) REFERENCES [PRD].[C_METRICS] ([ID_METRICS]),
    CONSTRAINT [FK_K_METRICS_READINGS_K_READINGS] FOREIGN KEY ([ID_K_READING]) REFERENCES [PRD].[K_READINGS] ([ID_K_READING])
);

