CREATE TABLE [PRD].[K_PALLETX] (
    [ID_PALLET]                          INT            IDENTITY (1, 1) NOT NULL,
    [ID_QA27]                            INT            NOT NULL,
    [ID_WORK_ORDER]                      INT            NOT NULL,
    [NO_PALLET]                          INT            NOT NULL,
    [NO_QUANTITY]                        INT            NULL,
    [DT_INITIAL_TIME]                    DATETIME       NOT NULL,
    [DT_FINAL_TIME]                      DATETIME       NULL,
    [DT_FINAL_OPERATION_TIME]            DATETIME       NULL,
    [KY_STATUS]                          NVARCHAR (50)  NOT NULL,
    [KY_USER_INSPECTOR]                  NVARCHAR (50)  NULL,
    [ID_QUALITY_INSPECTOR_AGREEMENT]     INT            NULL,
    [NM_QUALITY_INSPECTOR_AGREEMENT]     NVARCHAR (200) NULL,
    [FG_INSPECTOR_AGREEMENT]             BIT            NOT NULL,
    [DT_INSPECTOR_AGREEMENT]             DATETIME       NULL,
    [DS_EXPLANATION_AGREEMENT]           TEXT           NULL,
    [KY_USER_LEADMAN]                    NVARCHAR (50)  NULL,
    [ID_LEADMAN]                         INT            NULL,
    [NM_LEADMAN]                         NVARCHAR (200) NULL,
    [FG_LEADMAN]                         BIT            NOT NULL,
    [DT_LEADMAN]                         DATETIME       NULL,
    [KY_FIRST_LEVEL_USER]                NVARCHAR (50)  NULL,
    [ID_FIRST_LEVEL_EMPLOYEE]            INT            NULL,
    [NM_FIRST_LEVEL_EMPLOYEE]            NVARCHAR (200) NULL,
    [FG_FIRST_LEVEL_EMPLOYEE]            BIT            NOT NULL,
    [DT_FIRST_LEVEL_EMPLOYEE]            DATETIME       NULL,
    [KY_SECOND_LEVEL_USER_REJECTION]     NVARCHAR (50)  NULL,
    [ID_SECOND_LEVEL_EMPLOYEE_REJECTION] INT            NULL,
    [NM_SECOND_LEVEL_EMPLOYEE_REJECTION] NVARCHAR (200) NULL,
    [FG_SECOND_LEVEL_EMPLOYEE_REJECTION] BIT            NOT NULL,
    [DT_SECOND_LEVEL_EMPLOYEE_REJECTION] DATETIME       NULL,
    [KY_THIRD_LEVEL_USER_REJECTION]      NVARCHAR (50)  NULL,
    [ID_THIRD_LEVEL_EMPLOYEE_REJECTION]  INT            NULL,
    [NM_THIRD_LEVEL_EMPLOYEE_REJECTION]  NVARCHAR (200) NULL,
    [FG_THIRD_LEVEL_EMPLOYEE_REJECTION]  BIT            NOT NULL,
    [DT_THIRD_LEVEL_EMPLOYEE_REJECTION]  DATETIME       NULL,
    [FG_SEND_FORM]                       BIT            NULL,
    [NO_PALLETS_OPENED]                  INT            NULL,
    [DT_CREATION]                        DATETIME       NOT NULL,
    [DT_UPDATE]                          DATETIME       NULL,
    [KY_USER_APP_CREATION]               NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]                 NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]                   NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]                  NVARCHAR (50)  NULL
);

