CREATE TABLE [PRD].[K_PALLET_COMMENT] (
    [ID_PALLET_COMMENT]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_PALLET]            INT           NOT NULL,
    [DS_COMMENT]           TEXT          NOT NULL,
    [DT_COMMENT]           DATETIME      NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_PALLET_COMMENT] PRIMARY KEY CLUSTERED ([ID_PALLET_COMMENT] ASC),
    CONSTRAINT [FK_K_PALLET_COMMENT_K_PALLET] FOREIGN KEY ([ID_PALLET]) REFERENCES [PRD].[K_PALLET] ([ID_PALLET])
);

