CREATE TABLE [PRD].[K_POSITION_SCALING] (
    [ID_POSITION_SCALING]  INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROBLEM_CODE]      INT           NULL,
    [ID_FORM]              INT           NULL,
    [ID_PALLET]            INT           NULL,
    [KY_PROCESS_PALLET]    NVARCHAR (50) NULL,
    [ID_POSITION]          INT           NULL,
    [KY_LEVEL_TYPE]        NVARCHAR (50) NULL,
    [NO_TIME_HOLD_ON]      INT           CONSTRAINT [DF_K_POSITION_SCALING_NO_TIME_HOLD_ON] DEFAULT ((15)) NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_POSITION_SCALING] PRIMARY KEY CLUSTERED ([ID_POSITION_SCALING] ASC),
    CONSTRAINT [FK_K_POSITION_SCALING_C_FORM] FOREIGN KEY ([ID_FORM]) REFERENCES [PRD].[C_FORM] ([ID_FORM]),
    CONSTRAINT [FK_K_POSITION_SCALING_C_POSITION] FOREIGN KEY ([ID_POSITION]) REFERENCES [ADM].[C_POSITION] ([ID_POSITION]),
    CONSTRAINT [FK_K_POSITION_SCALING_C_PROBLEM_CODE] FOREIGN KEY ([ID_PROBLEM_CODE]) REFERENCES [PRD].[C_PROBLEM_CODE] ([ID_PROBLEM_CODE]),
    CONSTRAINT [FK_K_POSITION_SCALING_K_PALLET] FOREIGN KEY ([ID_PALLET]) REFERENCES [PRD].[K_PALLET] ([ID_PALLET])
);

