CREATE TABLE [PRD].[K_SCALING] (
    [ID_SCALING]           INT           IDENTITY (1, 1) NOT NULL,
    [ID_SCALING_PROCESS]   INT           NOT NULL,
    [NO_LEVEL]             INT           NOT NULL,
    [DT_START_SCALING]     DATETIME      NULL,
    [NO_TIME_HOLD_ON]      INT           NOT NULL,
    [KY_STATUS]            NVARCHAR (10) NOT NULL,
    [DT_SCALING]           DATETIME      NOT NULL,
    [DT_SEND]              DATETIME      NULL,
    [ID_POSITION]          INT           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [FK_K_SCALING_C_POSITION] FOREIGN KEY ([ID_POSITION]) REFERENCES [ADM].[C_POSITION] ([ID_POSITION])
);

