CREATE TABLE [PRD].[K_SCALING_PROCESS] (
    [ID_SCALING_PROCESS]   INT           IDENTITY (1, 1) NOT NULL,
    [ID_ISSUE]             INT           NULL,
    [ID_FORM]              INT           NULL,
    [ID_PALLET]            INT           NULL,
    [ID_K_FORM]            INT           NULL,
    [ID_BRANCH_PLANT]      INT           NULL,
    [DT_SCALING_PROCESS]   DATETIME      NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [FK_K_SCALING_PROCESS_K_FORM] FOREIGN KEY ([ID_K_FORM]) REFERENCES [PRD].[K_FORM] ([ID_K_FORM]),
    CONSTRAINT [FK_K_SCALING_PROCESS_K_PALLET] FOREIGN KEY ([ID_PALLET]) REFERENCES [PRD].[K_PALLET] ([ID_PALLET])
);

