CREATE TABLE [PRD].[K_SHIFT_FOREMAN] (
    [ID_SHIFT_FOREMAN] INT           IDENTITY (1, 1) NOT NULL,
    [KY_SHIFT_TIME]    NVARCHAR (80) NOT NULL,
    [KY_USER]          NVARCHAR (80) NOT NULL,
    [DT_SYSTEM]        DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_SHIFT_FOREMAN] ASC)
);

