CREATE TABLE [PRD].[K_SKIPPED_WORK_ORDER_LOG] (
    [ID_SKIPPED_WORK_ORDER_LOG] INT            IDENTITY (1, 1) NOT NULL,
    [ID_WORK_ORDER]             INT            NOT NULL,
    [DS_EXPLANATION]            NVARCHAR (512) NOT NULL,
    [ID_ISSUE]                  INT            NULL,
    [KY_AUTHORIZER_USER]        NVARCHAR (50)  NOT NULL,
    [ID_QA27]                   INT            NOT NULL,
    [DT_CREATION]               DATETIME       NOT NULL,
    [DT_UPDATE]                 DATETIME       NULL,
    [KY_USER_APP_CREATION]      NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]        NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]          NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]         NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_SKIPPED_WORK_ORDER_LOG] PRIMARY KEY CLUSTERED ([ID_SKIPPED_WORK_ORDER_LOG] ASC),
    CONSTRAINT [FK_K_SKIPPED_WORK_ORDER_LOG_K_ISSUE] FOREIGN KEY ([ID_ISSUE]) REFERENCES [PRD].[K_ISSUE] ([ID_ISSUE]),
    CONSTRAINT [FK_K_SKIPPED_WORK_ORDER_LOG_K_QA27] FOREIGN KEY ([ID_QA27]) REFERENCES [PRD].[K_QA27] ([ID_QA27]),
    CONSTRAINT [FK_K_SKIPPED_WORK_ORDER_LOG_K_WORK_ORDER] FOREIGN KEY ([ID_WORK_ORDER]) REFERENCES [PRD].[K_WORK_ORDER] ([ID_WORK_ORDER])
);

