CREATE TABLE [PRD].[K_UMNT_AUTHORIZATION] (
    [ID_UMNT_AUTHORIZATION] INT           IDENTITY (1, 1) NOT NULL,
    [KY_USER_UMNT]          NVARCHAR (80) NOT NULL,
    [KY_SHIFT]              NVARCHAR (50) NOT NULL,
    [DT_SYSTEM]             DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_UMNT_AUTHORIZATION] ASC)
);

