CREATE TABLE [PRD].[K_WORK_ORDER_LOG] (
    [ID_WORK_ORDER_LOG]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_WORK_ORDER]        INT           NOT NULL,
    [DT_WORK_ORDER_LOG]    DATETIME      NOT NULL,
    [NO_SEQUENCE]          INT           NOT NULL,
    [KY_TYPE_DATE]         NVARCHAR (50) NOT NULL,
    [DT_START_WORK_ORDER]  DATETIME      NOT NULL,
    [DT_CLOSE_WORK_ORDER]  DATETIME      NOT NULL,
    [NO_QTY_ADDED]         INT           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_WORK_ORDER_LOG] PRIMARY KEY CLUSTERED ([ID_WORK_ORDER_LOG] ASC),
    CONSTRAINT [FK_K_WORK_ORDER_LOG_K_WORK_ORDER] FOREIGN KEY ([ID_WORK_ORDER]) REFERENCES [PRD].[K_WORK_ORDER] ([ID_WORK_ORDER])
);

