CREATE TABLE [PRD].[K_WORK_ORDER_COMMENT] (
    [ID_WORK_ORDER_COMMENT] INT           IDENTITY (1, 1) NOT NULL,
    [ID_WORK_ORDER]         INT           NOT NULL,
    [KY_TYPE_COMMENT]       NVARCHAR (50) NULL,
    [DS_COMMENT]            TEXT          NOT NULL,
    [DT_COMMENT]            DATETIME      NOT NULL,
    [FG_ACTIVE]             BIT           CONSTRAINT [DF_K_WORK_ORDER_COMMENT_FG_ACTIVE] DEFAULT ((1)) NOT NULL,
    [DT_LAST_INACTIVE]      DATETIME      NULL,
    [DT_CREATION]           DATETIME      NOT NULL,
    [DT_UPDATE]             DATETIME      NULL,
    [KY_USER_APP_CREATION]  NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]    NVARCHAR (50) NULL,
    [NM_PROGAM_CREATE]      NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_WORK_ORDER_COMMENT] PRIMARY KEY CLUSTERED ([ID_WORK_ORDER_COMMENT] ASC),
    CONSTRAINT [FK_K_WORK_ORDER_COMMENT_K_WORK_ORDER] FOREIGN KEY ([ID_WORK_ORDER]) REFERENCES [PRD].[K_WORK_ORDER] ([ID_WORK_ORDER])
);

