

CREATE VIEW [ADM].[VW_C_WORK_ORDER_STATUS] AS (
SELECT 1 ID_WORK_ORDER_STATUS, 'SCHEDULED' KY_WORK_ORDER_STATUS, 'Scheduled' NM_WORK_ORDER_STATUS, 'BLUE' NM_COLOR UNION ALL
SELECT 2 ID_WORK_ORDER_STATUS, 'COMPLETE' KY_WORK_ORDER_STATUS, 'Complete' NM_WORK_ORDER_STATUS, 'GREEN' NM_COLOR UNION ALL
SELECT 3 ID_WORK_ORDER_STATUS, 'DELAYED' KY_WORK_ORDER_STATUS, 'Delayed on start W.O' NM_WORK_ORDER_STATUS, 'BROWN' NM_COLOR UNION ALL
SELECT 4 ID_WORK_ORDER_STATUS, 'DISRUPTION' KY_WORK_ORDER_STATUS, 'Disruption during a W.O' NM_WORK_ORDER_STATUS, 'RED' NM_COLOR UNION ALL
SELECT 5 ID_WORK_ORDER_STATUS, 'SETUP' KY_WORK_ORDER_STATUS, 'Set-up time for next W.O.' NM_WORK_ORDER_STATUS, 'ORANGE' NM_COLOR UNION ALL
SELECT 6 ID_WORK_ORDER_STATUS, 'READINGS' KY_WORK_ORDER_STATUS, 'Readings have not been completed as requested and/or values are out of specifications' NM_WORK_ORDER_STATUS, 'BLINKING WHITE' NM_COLOR UNION ALL
SELECT 7 ID_WORK_ORDER_STATUS, 'EQUIPMENT' KY_WORK_ORDER_STATUS, 'Line/equipment without specific prodution plan' NM_WORK_ORDER_STATUS, 'GRAY' NM_COLOR UNION ALL
SELECT 8 ID_WORK_ORDER_STATUS, 'WAITING' KY_WORK_ORDER_STATUS, 'Waiting' NM_WORK_ORDER_STATUS, 'YELLOW' NM_COLOR UNION ALL
SELECT 9 ID_WORK_ORDER_STATUS, 'RUNNING' KY_WORK_ORDER_STATUS, 'Running' NM_WORK_ORDER_STATUS, 'LIGTH GREEN' NM_COLOR UNION ALL
SELECT 10 ID_WORK_ORDER_STATUS, 'SKIPPED' KY_WORK_ORDER_STATUS, 'Skipped' NM_WORK_ORDER_STATUS, 'dark GREEN' NM_COLOR) UNION ALL
SELECT 11 ID_WORK_ORDER_STATUS, 'CLOSED' KY_WORK_ORDER_STATUS, 'Closed' NM_ROWK_ORDER_STATUS, 'BLACK' NM_COLOR
