CREATE VIEW [ADM].[VW_C_HYSTERESIS_TYPE] AS 
(
SELECT 1 ID_HYSTERESIS_TYPE, 'ABS' KY_HYSTERESIS_TYPE, 'Absolute' NM_HYSTERESIS_TYPE UNION ALL
SELECT 2 ID_HYSTERESIS_TYPE, 'PCT' KY_HYSTERESIS_TYPE, 'Percentage' NM_HYSTERESIS_TYPE UNION ALL
SELECT 3 ID_HYSTERESIS_TYPE, 'REL' KY_HYSTERESIS_TYPE, 'Relative' NM_HYSTERESIS_TYPE UNION ALL
SELECT 4 ID_HYSTERESIS_TYPE, 'NONE' KY_HYSTERESIS_TYPE, 'None' NM_HYSTERESIS_TYPE)
