CREATE VIEW [ADM].[VW_C_NOTIFICATION_ORIGIN] AS (
SELECT 1 ID_NOTIFICATION_ORIGIN, 'ISSUE' KY_NOTIFICATION_ORIGIN, 'Issue' NM_NOTIFICATION_ORIGIN UNION ALL
SELECT 2 ID_NOTIFICATION_ORIGIN, 'PALLET' KY_NOTIFICATION_ORIGIN, 'Pallet' NM_NOTIFICATION_ORIGIN)