CREATE VIEW [ADM].[VW_C_SHIFT_HOURS] AS (
SELECT 1 ID_SHIFT_HOURS, '1' NO_SHIFT_HOUR UNION ALL
SELECT 2 ID_SHIFT_HOURS, '2' NO_SHIFT_HOUR UNION ALL
SELECT 3 ID_SHIFT_HOURS, '3' NO_SHIFT_HOUR UNION ALL
SELECT 4 ID_SHIFT_HOURS, '4' NO_SHIFT_HOUR UNION ALL
SELECT 5 ID_SHIFT_HOURS, '5' NO_SHIFT_HOUR UNION ALL
SELECT 6 ID_SHIFT_HOURS, '6' NO_SHIFT_HOUR UNION ALL
SELECT 7 ID_SHIFT_HOURS, '7' NO_SHIFT_HOUR UNION ALL
SELECT 8 ID_SHIFT_HOURS, '8' NO_SHIFT_HOUR UNION ALL
SELECT 9 ID_SHIFT_HOURS, '9' NO_SHIFT_HOUR UNION ALL
SELECT 10 ID_SHIFT_HOURS, '10' NO_SHIFT_HOUR UNION ALL
SELECT 11 ID_SHIFT_HOURS, '11' NO_SHIFT_HOUR UNION ALL
SELECT 12 ID_SHIFT_HOURS, '12' NO_SHIFT_HOUR
)
