CREATE VIEW [ADM].[VW_C_NOTIFICATION_STATUS] AS (
SELECT 1 ID_NOTIFICATION_STATUS, 'SEND' KY_NOTIFICATION_STATUS, 'Sended' NM_NOTIFICATION_STATUS UNION ALL
SELECT 2 ID_NOTIFICATION_STATUS, 'WAIT' KY_NOTIFICATION_STATUS, 'Waiting' NM_NOTIFICATION_STATUS UNION ALL
SELECT 3 ID_NOTIFICATION_STATUS, 'CLOSE' KY_NOTIFICATION_STATUS, 'Close' NM_NOTIFICATION_STATUS)
