
CREATE VIEW [ADM].[VW_C_FIELD_TYPE] AS (
SELECT 1 ID_FIELD_TYPE, 'DATEPICKER' KY_FIELD_TYPE, 'Date' NM_FIELD_TYPE UNION ALL
SELECT 2 ID_FIELD_TYPE, 'COMBOBOX' KY_FIELD_TYPE, 'List' NM_FIELD_TYPE UNION ALL
SELECT 3 ID_FIELD_TYPE, 'NUMERICBOX' KY_FIELD_TYPE, 'Numeric' NM_FIELD_TYPE UNION ALL
SELECT 4 ID_FIELD_TYPE, 'TEXTBOX' KY_FIELD_TYPE, 'Text' NM_FIELD_TYPE UNION ALL
SELECT 5 ID_FIELD_TYPE, 'CHECKBOX' KY_FIELD_TYPE, 'Yes/No' NM_FIELD_TYPE)
