


CREATE VIEW [ADM].[VW_C_ISSUE_STATUS] AS (		
SELECT 1 ID_ISSUE_STATUS, 'CREATED' KY_ISSUE_STATUS, 'Created' NM_ISSUE_STATUS UNION ALL		
SELECT 2 ID_ISSUE_STATUS, 'CLOSED' KY_ISSUE_STATUS, 'Closed' NM_ISSUE_STATUS UNION ALL		
SELECT 3 ID_ISSUE_STATUS, 'HOLD_ON' KY_ISSUE_STATUS, 'Hold on' NM_ISSUE_STATUS UNION ALL		
SELECT 4 ID_ISSUE_STATUS, 'CHANGE_SHIFT' KY_ISSUE_STATUS, 'Change shift' NM_ISSUE_STATUS)