CREATE VIEW [ADM].[VW_C_DATA_ACQUISITION_ORIGIN] AS (
SELECT 1 ID_DATA_ACQUISITION_ORIGIN, 'NONE' KY_DATA_ACQUISITION_ORIGIN, 'None' NM_DATA_ACQUISITION_ORIGIN UNION ALL
SELECT 2 ID_DATA_ACQUISITION_ORIGIN, 'PROTABLE' KY_DATA_ACQUISITION_ORIGIN, 'Protable' NM_DATA_ACQUISITION_ORIGIN UNION ALL
SELECT 3 ID_DATA_ACQUISITION_ORIGIN, 'DEVICE' KY_DATA_ACQUISITION_ORIGIN, 'Device' NM_DATA_ACQUISITION_ORIGIN)