CREATE VIEW [ADM].[VW_C_QA27_STATUS] AS (
SELECT 1 ID_QA27_STATUS, 'COMPLETE' KY_QA27_STATUS, 'Complete' NM_QA27_STATUS UNION ALL
SELECT 2 ID_QA27_STATUS, 'HOLD_ON' KY_QA27_STATUS, 'Hold on' NM_QA27_STATUS UNION ALL
SELECT 3 ID_QA27_STATUS, 'RUNNING' KY_QA27_STATUS, 'Running' NM_QA27_STATUS UNION ALL
SELECT 4 ID_QA27_STATUS, 'CHANGE_SHIFT' KY_QA27_STATUS, 'Change shift' NM_QA27_STATUS)