CREATE VIEW [ADM].[VW_C_LEVEL_TYPE] AS (
SELECT 1 ID_LEVEL_TYPE, 'LEV1' KY_LEVEL_TYPE, 'LEVEL 1' NM_LEVEL_TYPE UNION ALL
SELECT 2 ID_LEVEL_TYPE, 'LEV2' KY_LEVEL_TYPE, 'LEVEL 2' NM_LEVEL_TYPE UNION ALL
SELECT 3 ID_LEVEL_TYPE, 'LEV3' KY_LEVEL_TYPE, 'LEVEL 3' NM_LEVEL_TYPE UNION ALL
SELECT 4 ID_LEVEL_TYPE, 'LEV4' KY_LEVEL_TYPE, 'LEVEL 4' NM_LEVEL_TYPE)

