



CREATE VIEW [ADM].[VW_C_CODE_TYPE] AS (
SELECT 1 ID_CODE_TYPE, 'DEV' KY_CODE_TYPE, 'Development' NM_CODE_TYPE,  'DEVELOPMENT' DS_CODE_TYPE, 7 NO_ORDER, 'B' KY_GROUP UNION ALL
SELECT 2 ID_CODE_TYPE, 'DCHG' KY_CODE_TYPE, 'Die Change' NM_CODE_TYPE, 'DIE CHANGE' DS_CODE_TYPE, 2 NO_ORDER, 'A' KY_GROUP UNION ALL
SELECT 3 ID_CODE_TYPE, 'OTHER' KY_CODE_TYPE, 'Other Setup' NM_CODE_TYPE, 'OTHER SETUP' DS_CODE_TYPE, 4 NO_ORDER, 'A' KY_GROUP UNION ALL
SELECT 4 ID_CODE_TYPE, 'RCHG' KY_CODE_TYPE, 'Roll Change' NM_CODE_TYPE, 'ROLL CHANGE' DS_CODE_TYPE, 3 NO_ORDER, 'A' KY_GROUP UNION ALL
SELECT 5 ID_CODE_TYPE, 'SMNT' KY_CODE_TYPE, 'Scheduled Maintenance' NM_CODE_TYPE, 'SCH. MAINT.' DS_CODE_TYPE, 6 NO_ORDER, 'B' KY_GROUP UNION ALL
SELECT 6 ID_CODE_TYPE, 'UMNT' KY_CODE_TYPE, 'Unscheduled Maintenance' NM_CODE_TYPE, 'UNSCH. MAINT.' DS_CODE_TYPE, 5 NO_ORDER, 'B' KY_GROUP UNION ALL
SELECT 7 ID_CODE_TYPE, 'IDLE' KY_CODE_TYPE, 'IDLE' NM_CODE_TYPE, 'IDLE' DS_CODE_TYPE, 8 NO_ORDER, 'B' KY_GROUP UNION ALL
SELECT 8 ID_CODE_TYPE, 'PROD' KY_CODE_TYPE, 'Production' NM_CODE_TYPE, 'PRODUCTION' DS_CODE_TYPE, 1 NO_ORDER, 'A' KY_GROUP)