CREATE VIEW [ADM].[VW_S_PRODUCTION_LINE_TYPE] AS (
SELECT 1 ID_PRODUCTION_LINE_TYPE, 'LE' KY_PRODUCTION_LINE_TYPE, 'Extrusion' NM_PRODUCTION_LINE_TYPE UNION ALL
SELECT 2 ID_PRODUCTION_LINE_TYPE, 'LF' KY_PRODUCTION_LINE_TYPE, 'Fabrication' NM_PRODUCTION_LINE_TYPE)

