CREATE VIEW [ADM].[VW_SCALING_TYPE] AS (		
SELECT 1 ID_SCALING_TYPE, 'NONE' KY_SCALING_TYPE, 'None' NM_SCALING_TYPE UNION ALL		
SELECT 2 ID_SCALING_TYPE, 'LINEAR' KY_SCALING_TYPE, 'Linear' NM_SCALING_TYPE)