-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez
-- CRETAE date: 02/05/2018
-- Description: Update status of an sample
-- =============================================
CREATE PROCEDURE    [LAB].[SPE_UPDATE_STATUS_SAMPLE] 
    	     @XML_RESULT XML = '' OUT ,    -- --0 TO ERROR AND 1 TO CORRECT
			 @PIN_ID_SAMPLE as int = null
			, @PIN_KY_SAMPLE_STATUS as nvarchar(50)
			, @PIN_KY_USER_APP_UPDATE AS nvarchar(50)
			, @PIN_NM_PROGRAM_UPDATE AS nvarchar(50)

AS 
BEGIN  
	----WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE
	DECLARE @V_EXIST_TRAN BIT = 0, @CFE_SISTEMA DATETIME = GETDATE()

	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
	IF (@@TRANCOUNT = 0) 
	BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
		BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
		SET @V_EXIST_TRAN = 1
	END	
		--WE VERIFY IF THE SPE IS GOING TO EXECUTE A UPDATE OR INSERT

	UPDATE [LAB].[K_SAMPLE]
		SET [KY_SAMPLE_STATUS] = @PIN_KY_SAMPLE_STATUS
			,[DT_UPDATE] = @CFE_SISTEMA
			,[KY_USER_APP_UPDATE] = @PIN_KY_USER_APP_UPDATE
			,[NM_PROGRAM_UPDATE] = @PIN_NM_PROGRAM_UPDATE
		WHERE ID_SAMPLE = @PIN_ID_SAMPLE

		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')

		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = ERROR_MESSAGE()
	
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		
			
	END CATCH
END

