create PROCEDURE  [LAB].[SPE_GET_READING_DEVICE_CONFIGURATION]
	@PIN_ID_DEVICE AS INT = NULL
AS
BEGIN

	--DECLARE @PIN_ID_DEVICE AS INT = NULL
	SELECT 
		DC.ID,
		DC.NM_DEVICE,
		DC.FG_STATUS,
		DC.FG_ENABLED,
		DC.NM_REASON
	FROM LAB.K_READING_DEVICE_CONFIGURATION DC
	WHERE
	@PIN_ID_DEVICE IS NULL OR (@PIN_ID_DEVICE IS NOT NULL AND DC.ID = @PIN_ID_DEVICE)

END