-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázque Torres
-- CREATE date: 02/05/2018
-- Description: Delete a sample
-- =============================================
CREATE PROCEDURE    [LAB].[SPE_DELETE_SAMPLE]
	@XML_RESULT XML = '' OUT  ,      --0 TO ERROR AND 1 TO CORRECT
	@PIN_NO_WORK_ORDER INT = NULL,
	@PIN_NO_PALLET INT = NULL,
	@PIN_ID_SAMPLE INT = NULL,
	@PIN_ID_K_FORM INT = NULL

AS   
BEGIN
	--WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE
	DECLARE @V_EXIST_TRAN BIT = 0
	BEGIN TRY		   			
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1
		END	
		--DELETE THE REGISTER ON THE SQL TABLE LAB.K_SAMPLE
		
		--IF @PIN_NO_PALLET IS NOT NULL  BEGIN
		--	DELETE FROM [LAB].[K_SAMPLE] WHERE NO_PALLET = @PIN_NO_PALLET;
		--END
				
		--IF @PIN_NO_WORK_ORDER IS NOT NULL BEGIN
		--	DELETE FROM [LAB].[K_SAMPLE] WHERE NO_WORK_ORDER = @PIN_NO_WORK_ORDER;
		--END

		--IF @PIN_ID_SAMPLE IS NOT NULL BEGIN
		--	DELETE FROM [LAB].[K_SAMPLE] WHERE ID_SAMPLE = @PIN_ID_SAMPLE;
		--END

		--((@ID_K_FORM IS NULL AND KS.NO_PALLET = @V_NO_PALLET)  OR (@ID_K_FORM IS NOT NULL AND ( KS.ID_FORM = @ID_K_FORM)))

		IF @PIN_ID_K_FORM IS NOT NULL
		BEGIN
			DELETE FROM [LAB].[K_SAMPLE] 
			WHERE NO_WORK_ORDER = @PIN_NO_WORK_ORDER
			  AND ID_FORM = @PIN_ID_K_FORM
		END

		IF @PIN_NO_PALLET IS NOT NULL
		BEGIN
			DELETE FROM [LAB].[K_SAMPLE] 
			WHERE NO_WORK_ORDER = @PIN_NO_WORK_ORDER
			  AND NO_PALLET = @PIN_NO_PALLET
		END



		--WE RETURN A VARIABLE THAT INDICATES THAT EVERYTHING WAS PERFORMED OKAY.
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Se eliminó el idioma satisfactoriamente', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successfully deleted employee', 'EN')
		
		--IN THIS BLOCK ALL TRANSACTIONS WILL DELETED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT				
	END TRY
	BEGIN CATCH			
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK

		SET @XML_RESULT = DBO.F_ERROR_MESSAGES(ERROR_NUMBER(), ERROR_MESSAGE())

	END CATCH	
END

