-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 28/05/2018
-- Description: get users for labs application
-- =============================================
CREATE PROCEDURE    [LAB].[SPE_GET_USER_LABS]
	 @PIN_ID_BRANCH_PLANT INT = NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @ID_BRANCH_PLANT INT = 1  --PENDING TO GET FROM XML CONFIGURATION
		, @XML_CONFIGURATION XML 
		, @XML_BRANCH_PLANT_SELECTED XML
		, @ID_POSITION_OPERATOR INT = NULL
		, @ID_POSITION_QUALITY_INSPECTOR INT = NULL

	SELECT TOP 1 @XML_CONFIGURATION = XML_CONFIGURATION FROM ADM.S_CONFIGURATION

	SELECT @XML_BRANCH_PLANT_SELECTED = msgs.msg.query('.')
	FROM @XML_CONFIGURATION.nodes('CONFIGURATIONS/ESPECIFIC_CONFIGURATION/child::node()') msgs(msg)	
	WHERE msgs.msg.value('@ID_BRANCH_PLANT', 'nvarchar(max)') = CAST(@ID_BRANCH_PLANT AS NVARCHAR(MAX))

	SELECT @ID_POSITION_OPERATOR = msgs.msg.value('@ID_POSITION', 'nvarchar(max)') 
	FROM @XML_BRANCH_PLANT_SELECTED.nodes('BRANCH_PLANT/QUALITY_PROCESS/OPERATOR') msgs(msg)	

	SELECT @ID_POSITION_QUALITY_INSPECTOR = msgs.msg.value('@ID_POSITION', 'nvarchar(max)')
	FROM @XML_BRANCH_PLANT_SELECTED.nodes('BRANCH_PLANT/QUALITY_PROCESS/QUALITY_INSPECTOR') msgs(msg)	


	SELECT CU.KY_USER
		, CU.NM_USER
		, CE.ID_POSITION
		, CP.KY_POSITION
		, 'OPERATOR' AS NM_POSITION --CP.NM_POSITION,
     FROM ADM.C_USER CU
		INNER JOIN ADM.C_EMPLOYEE CE 
			ON CU.ID_EMPLOYEE = CE.ID_EMPLOYEE
		INNER JOIN ADM.C_POSITION CP 
			ON CE.ID_POSITION = CP.ID_POSITION
		INNER JOIN ADM.C_ROLE CR 
			ON CR.ID_ROLE = CU.ID_ROLE
		INNER JOIN ADM.C_ROLE_FUNCTION CRF 
			ON CR.ID_ROLE = CRF.ID_ROLE
		INNER JOIN ADM.S_FUNCTION SF 
			ON CRF.ID_FUNCTION = SF.ID_FUNCTION
		LEFT JOIN ADM.C_BRANCH_PLANT BP 
			ON BP.ID_BRANCH_PLANT = CU.ID_BRANCH_PLANT
		INNER JOIN PRD.K_SHIFT KS 
			ON CU.KY_USER = KS.KY_USER
	WHERE SF.KY_FUNCTION = 'ADH'  ---- KEY FUNCTION TO ALLOW OPERATE MACHINE
		AND CU.FG_ACTIVE = 1  
		AND CE.FG_ACTIVE = 1
		AND CU.ID_BRANCH_PLANT = @ID_BRANCH_PLANT 
		AND KS.FG_STATUS = 1

UNION ALL

	SELECT CU.KY_USER
		, CU.NM_USER
		, CE.ID_POSITION
		, CP.KY_POSITION
		, 'QUALITY INSPECTOR' AS NM_POSITION --CP.NM_POSITION
	FROM ADM.C_USER CU
		INNER JOIN ADM.C_EMPLOYEE CE 
			ON CU.ID_EMPLOYEE = CE.ID_EMPLOYEE
		INNER JOIN ADM.C_POSITION CP 
			ON CE.ID_POSITION = CP.ID_POSITION
	WHERE CE.ID_BRANCH_PLANT = @ID_BRANCH_PLANT
		AND CE.ID_POSITION = @ID_POSITION_QUALITY_INSPECTOR
		AND CU.FG_ACTIVE = 1
		AND CE.FG_ACTIVE = 1  






END

