-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Gabriel Vázquez Torres
-- CREATE date: 02/05/2018
-- Description: get samples by sample id, workorder number, pallet number or all
-- =============================================
CREATE PROCEDURE    [LAB].[SPE_GET_SAMPLES]
	-- Add the parameters for the stored procedure here
	 @PIN_ID_SAMPLE INT = NULL
	,@PIN_NO_WORK_ORDER INT = NULL
	,@PIN_NO_PALLET INT = NULL
	,@PIN_K_ID_FORM INT = NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @XML_THICKNESS XML

	SELECT ID_SAMPLE
		, NO_SAMPLE
		, DT_WIDTH
		, ID_WIDTH_METRIC
		, NO_WIDTH_VALUE
		, DT_LENGTH
		, ID_LENGTH_METRIC
		, NO_LENGTH_VALUE
		, DT_THICKNESS
		, ID_THICKNESS_METRIC
		, NO_THICKNESS_VALUE
		, DT_LIGHT_TRANSMISSION
		, ID_LIGHT_TRANSMISSION_METRIC
		, NO_LIGHT_TRANSMISSION_VALUE
		, DT_WEIGHT
		, ID_WEIGHT_METRIC
		, NO_WEIGHT_VALUE
		, DT_GLOSS
		, ID_GLOSS_METRIC
		, NO_GLOSS_VALUE
		, NO_PALLET
		, NO_WORK_ORDER
		, ID_FORM
		, KY_SAMPLE_STATUS
		, CASE 
			WHEN (DATEDIFF(SECOND,DT_LENGTH, LEAD(DT_LENGTH) OVER(ORDER BY NO_SAMPLE)) <= 10
				OR DATEDIFF(SECOND,DT_WIDTH, LEAD(DT_WIDTH) OVER(ORDER BY NO_SAMPLE)) <= 10
				OR DATEDIFF(SECOND,DT_GLOSS, LEAD(DT_GLOSS) OVER(ORDER BY NO_SAMPLE)) <= 10
				OR DATEDIFF(SECOND,DT_LIGHT_TRANSMISSION, LEAD(DT_LIGHT_TRANSMISSION) OVER(ORDER BY NO_SAMPLE)) <= 10)
			THEN 1 
			ELSE 0 
		END AS DIF_BETWEEN_DT
		, @XML_THICKNESS AS XML_THICKNESS_READINGS
	FROM LAB.K_SAMPLE KS
	WHERE (@PIN_ID_SAMPLE IS NULL OR (@PIN_ID_SAMPLE IS NOT NULL AND KS.ID_SAMPLE = @PIN_ID_SAMPLE)) AND
	--(@PIN_NO_WORK_ORDER IS NULL OR (@PIN_NO_WORK_ORDER IS NOT NULL AND KS.NO_WORK_ORDER = @PIN_NO_WORK_ORDER AND KS.NO_PALLET IS NULL)) AND
	(@PIN_NO_WORK_ORDER IS NULL OR (@PIN_NO_WORK_ORDER IS NOT NULL AND KS.NO_WORK_ORDER = @PIN_NO_WORK_ORDER)) AND
	(@PIN_NO_PALLET IS NULL OR (@PIN_NO_PALLET IS NOT NULL AND KS.NO_PALLET =  @PIN_NO_PALLET)) AND
	(@PIN_K_ID_FORM IS NULL OR (@PIN_K_ID_FORM IS NOT NULL AND KS.ID_FORM = @PIN_K_ID_FORM)) 

END

