CREATE TABLE [ADM].[C_BRANCH_PLANT_FUNCTION] (
    [ID_FUNCTION]        INT            NOT NULL,
    [KY_FUNCTION]        VARCHAR (60)   NOT NULL,
    [NM_FUNCTION]        VARCHAR (60)   NOT NULL,
    [KY_TYPE_FUNCTION]   VARCHAR (60)   NULL,
    [ID_PARENT_FUNCTION] INT            NULL,
    [NM_URL]             NVARCHAR (200) NULL,
    [XML_CONFIGURATION]  XML            NULL,
    [NO_ORDER]           INT            NULL,
    [ID_BRANCH_PLANT]    INT            NOT NULL,
    CONSTRAINT [FK_C_BRANCH_PLANT_FUNCTION_C_BRANCH_PLANT] FOREIGN KEY ([ID_BRANCH_PLANT]) REFERENCES [ADM].[C_BRANCH_PLANT] ([ID_BRANCH_PLANT]),
    CONSTRAINT [UC_C_BRANCH_PLANT_FUNCTION_ID_FUNCTION] UNIQUE NONCLUSTERED ([ID_FUNCTION] ASC),
    CONSTRAINT [UC_C_BRANCH_PLANT_FUNCTION_NM_FUNCTION] UNIQUE NONCLUSTERED ([NM_FUNCTION] ASC)
);

