CREATE TABLE [ADM].[C_CUSTOMER] (
    [KY_CUSTOMER]        INT           NOT NULL,
    [NM_CUSTOMER]        VARCHAR (80)  NULL,
    [DT_CREATION]        DATETIME      NULL,
    [KY_USER_APP_CREATE] NVARCHAR (80) NULL,
    [NM_PROGRAM_CREATE]  NVARCHAR (80) NULL,
    [DT_UPDATE]          DATETIME      NULL,
    [KY_USER_APP_UPDATE] NVARCHAR (80) NULL,
    [NM_PROGRAM_UPDATE]  NVARCHAR (80) NULL,
    PRIMARY KEY CLUSTERED ([KY_CUSTOMER] ASC)
);

