CREATE TABLE [ADM].[C_CUSTOMER_SAMPLES] (
    [ID_CUSTOMER_SAMPLE]   INT           IDENTITY (1, 1) NOT NULL,
    [ID_FORM]              INT           NOT NULL,
    [KY_CUSTOMER]          NVARCHAR (20) NOT NULL,
    [NO_LENGTH_SAMPLE]     INT           NOT NULL,
    [KY_SAMPLE_UNIT]       NVARCHAR (10) NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]    NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_CUSTOMER_SAMPLES] PRIMARY KEY CLUSTERED ([ID_CUSTOMER_SAMPLE] ASC)
);

