CREATE TABLE [ADM].[C_DYNAMIC_TABLE] (
    [ID_DYNAMIC_TABLE] INT            IDENTITY (1, 1) NOT NULL,
    [ID_TABLE_COLUMNS] INT            NULL,
    [ORDER_COLUMN]     VARCHAR (1000) NULL,
    [KY_USER]          VARCHAR (50)   NULL,
    [KY_NAME_ORDER]    VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([ID_DYNAMIC_TABLE] ASC),
    FOREIGN KEY ([ID_TABLE_COLUMNS]) REFERENCES [ADM].[C_TABLE_COLUMNS] ([ID_TABLE_COLUMN])
);

