CREATE TABLE [ADM].[C_HELP] (
    [ID_HELP]              INT            IDENTITY (1, 1) NOT NULL,
    [KY_HELP]              NVARCHAR (50)  NOT NULL,
    [NM_HELP]              NVARCHAR (100) NOT NULL,
    [XML_HELP]             XML            NOT NULL,
    [ID_HELP_FATHER]       INT            NULL,
    [DT_CREATION]          DATETIME       NOT NULL,
    [DT_UPDATE]            DATETIME       NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)  NULL,
    [NM_PROGRAM_CREATE]    NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK__C_HELP__7E1499D339DD2749] PRIMARY KEY CLUSTERED ([ID_HELP] ASC),
    CONSTRAINT [IX_C_HELP] UNIQUE NONCLUSTERED ([KY_HELP] ASC)
);

