CREATE TABLE [ADM].[C_ROLE_FUNCTION] (
    [ID_ROLE]     INT NOT NULL,
    [ID_FUNCTION] INT NOT NULL,
    CONSTRAINT [FK_C_ROLE_FUNCTION_C_ROLE] FOREIGN KEY ([ID_ROLE]) REFERENCES [ADM].[C_ROLE] ([ID_ROLE])
);

