CREATE TABLE [ADM].[C_ROLE] (
    [ID_ROLE]              INT            IDENTITY (1, 1) NOT NULL,
    [KY_ROLE]              NVARCHAR (30)  NOT NULL,
    [NM_ROLE]              NVARCHAR (100) NOT NULL,
    [FG_ACTIVE]            BIT            CONSTRAINT [DF_C_ROLE_FG_ACTIVE] DEFAULT ((1)) NOT NULL,
    [DT_INACTIVE]          DATETIME       NULL,
    [DT_CREATION]          DATETIME       NOT NULL,
    [DT_UPDATE]            DATETIME       NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_ROLE] PRIMARY KEY CLUSTERED ([ID_ROLE] ASC)
);

