CREATE TABLE [ADM].[K_FUNCTION_HELP] (
    [ID_FUNCTION]          INT           NOT NULL,
    [ID_HELP]              INT           NOT NULL,
    [DT_CREATION]          DATETIME      NOT NULL,
    [DT_UPDATE]            DATETIME      NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]    NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_FUNCTION_HELP] PRIMARY KEY CLUSTERED ([ID_FUNCTION] ASC),
    CONSTRAINT [FK_K_FUNCTION_HELP_C_HELP] FOREIGN KEY ([ID_HELP]) REFERENCES [ADM].[C_HELP] ([ID_HELP])
);

