CREATE TABLE [ADM].[K_USER_ACCESS_LOG] (
    [ID_USER_ACCESS_LOG]   INT            IDENTITY (1, 1) NOT NULL,
    [KY_USER]              NVARCHAR (50)  NOT NULL,
    [NM_USER]              NVARCHAR (300) NOT NULL,
    [ID_EMPLOYEE]          INT            NULL,
    [ID_POSITION]          INT            NULL,
    [KY_POSITION]          NVARCHAR (50)  NULL,
    [NM_POSITION]          NVARCHAR (300) NULL,
    [DT_USER_ACCESS]       DATETIME       NULL,
    [KY_IP_ACCESS_FROM]    NVARCHAR (50)  NULL,
    [FG_IS_FOREMAN]        BIT            CONSTRAINT [DF_K_USER_ACCESS_LOG_FG_IS_FOREMAN] DEFAULT ((0)) NOT NULL,
    [DT_CREATION]          DATETIME       NOT NULL,
    [DT_UPDATE]            DATETIME       NULL,
    [KY_USER_APP_CREATION] NVARCHAR (50)  NOT NULL,
    [KY_USER_APP_UPDATE]   NVARCHAR (50)  NULL,
    [NM_PROGAM_CREATE]     NVARCHAR (50)  NOT NULL,
    [NM_PROGRAM_UPDATE]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_USER_ACCESS_LOG] PRIMARY KEY CLUSTERED ([ID_USER_ACCESS_LOG] ASC)
);

