CREATE TABLE [ADM].[S_CONFIGURATION] (
    [XML_CONFIGURATION] XML           NOT NULL,
    [DT_UPDATE]         DATETIME      NOT NULL,
    [KY_USER_UPDATE]    NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE] NVARCHAR (50) NOT NULL
);

