-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Vitek - 2020
-- Author: Aideé Alvarez.
-- CREATE date: 07/15/2020.
-- Description: GET C_SHIFT DATA.
-- =============================================
CREATE PROCEDURE  [ADM].[SPE_GET_C_SHIFT] 
		@PIN_ID_SHIFT AS INT = NULL,
		@PIN_ID_BRANCH_PLANT INT = NULL
AS   
	--IT'S TIME TO SEND YOUR DATA!
	SELECT 
	ID_SHIFT, KY_SHIFT, NM_SHIFT, NO_SHIFT_TIME,
	convert(VARCHAR, INITIAL_SHIFT_TIME, 108) INITIAL_SHIFT_TIME,
	convert(VARCHAR, FINAL_SHIFT_TIME, 108) FINAL_SHIFT_TIME,
	ID_BRANCH_PLANT,
	convert(VARCHAR, TS_START_SHIFT, 108) TS_START_SHIFT,
	convert(VARCHAR, TS_END_SHIFT, 108) TS_END_SHIFT
	FROM ADM.VW_C_SHIFT
	WHERE
		 (@PIN_ID_SHIFT IS NULL OR (@PIN_ID_SHIFT IS NOT NULL AND ID_SHIFT = @PIN_ID_SHIFT))
		 AND (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))