-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 07/03/2017
-- Description: get all position catalogs
-- =============================================

CREATE PROCEDURE    [ADM].[SPE_GET_POSITION_CATALOGS] 
	    @PIN_ID_POSITION AS int = NULL,
	    @PIN_ID_BRANCH_PLANT AS int = NULL

AS   
	BEGIN
	DECLARE 
        @V_KY_POSITION AS nvarchar(50),
        @V_NM_POSITION AS nvarchar(300),
        @V_DS_POSITION AS nvarchar(500),
		@V_DS_AREA AS nvarchar(500),
        @V_KY_EMAIL AS nvarchar(500),
        @V_KY_TELEGRAM AS nvarchar(15),
		@ID_DEPARTMENT AS int,
		@V_ID_BRANCH_PLANT AS int
		  ,@XML_BRANCHPLANTS AS XML
		  ,@XML_DEPARTMENTS AS XML
		  ,@XML_CATALOGS AS XML


		SET @XML_BRANCHPLANTS = (
		SELECT 	    
	    BP.ID_BRANCH_PLANT  AS "@ID_BRANCH_PLANT",
        BP.KY_BRANCH_PLANT  AS "@KY_BRANCH_PLANT",
        BP.NM_BRANCH_PLANT  AS "@NM_BRANCH_PLANT",
        BP.DS_BRANCH_PLANT  AS "@DS_BRANCH_PLANT",
        BP.ID_FILE  AS "@ID_FILE"
		FROM ADM.C_BRANCH_PLANT BP
		ORDER BY  BP.KY_BRANCH_PLANT
		FOR XML PATH ('BRANCHPLANT'), ROOT ('BRANCHPLANTS')
	)

	SET @XML_DEPARTMENTS = (
		SELECT 	    
	    CD.ID_DEPARTMENT  AS "@ID_DEPARTMENT",
        CD.KY_DEPARTMENT  AS "@KY_DEPARTMENT",
        CD.NM_DEPARTMENT  AS "@NM_DEPARTMENT",
        CD.DS_DEPARTMENT  AS "@DS_DEPARTMENT",
		CASE CD.FG_ACTIVE WHEN 1 THEN 'Yes' ELSE 'No' END  AS "@FG_ACTIVE"
		FROM ADM.C_DEPARTMENT CD
		WHERE FG_ACTIVE = 1
		ORDER BY  CD.KY_DEPARTMENT
		FOR XML PATH ('DEPARTMENT'), ROOT ('DEPARTMENTS')
	)

	
	       SET @XML_CATALOGS = (
		SELECT 
			 @XML_BRANCHPLANTS
		   , @XML_DEPARTMENTS
		FOR XML PATH ('CATALOGS')
	)


	SELECT 
		@V_KY_POSITION=P.KY_POSITION,
        @V_NM_POSITION =P.NM_POSITION,
        @V_DS_POSITION =P.DS_POSITION,
		@V_DS_AREA =P.DS_AREA,
		@V_KY_EMAIL=P.KY_EMAIL,
		@V_KY_TELEGRAM=P.KY_TELEGRAM,
		@V_ID_BRANCH_PLANT=P.ID_BRANCH_PLANT,
		@ID_DEPARTMENT=CD.ID_DEPARTMENT
		FROM ADM.C_POSITION P
		LEFT OUTER JOIN ADM.C_BRANCH_PLANT CC ON CC.ID_BRANCH_PLANT = P.ID_BRANCH_PLANT
		LEFT OUTER JOIN ADM.C_DEPARTMENT CD ON CD.ID_DEPARTMENT = P.ID_DEPARTMENT
		WHERE P.ID_POSITION = @PIN_ID_POSITION 
		--AND (P.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR P.ID_BRANCH_PLANT  = NULL)



		SELECT  @PIN_ID_POSITION AS ID_POSITION,
			    @V_KY_POSITION AS KY_POSITION,
				@V_NM_POSITION AS NM_POSITION,
				@V_DS_POSITION AS DS_POSITION,
				@V_DS_AREA AS DS_AREA,
				@V_KY_EMAIL AS KY_EMAIL,
				@V_KY_TELEGRAM AS KY_TELEGRAM,
				@V_ID_BRANCH_PLANT AS ID_BRANCH_PLANT,
				@ID_DEPARTMENT AS ID_DEPARTMENT
			  ,@XML_CATALOGS AS XML_CATALOGS
END

