-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Vitek - 2020
-- Author: Aideé Alvarez.
-- CREATE date: 07/15/2020.
-- Description: GET C_SHIFT_TIME DATA.
-- =============================================
CREATE PROCEDURE  [ADM].[SPE_GET_C_SHIFT_TIME] 
		@PIN_ID_SHIFT AS INT = NULL,
		@PIN_ID_SHIFT_TIME AS INT = NULL
AS   

	SELECT 
	ID_SHIFT_TIME,ID_SHIFT, KY_SHIFT, KY_SHIFT_TIME,NM_SHIFT_TIME, 
	NM_SHIFT, NO_SHIFT_TIME,
	convert(VARCHAR, INITIAL_SHIFT_TIME, 108) INITIAL_SHIFT_TIME,
	convert(VARCHAR, FINAL_SHIFT_TIME, 108) FINAL_SHIFT_TIME,
	ID_BRANCH_PLANT
	FROM ADM.VW_C_SHIFT_TIME
	WHERE
	 (@PIN_ID_SHIFT IS NULL OR (@PIN_ID_SHIFT IS NOT NULL AND ID_SHIFT = @PIN_ID_SHIFT)) AND 
	 (@PIN_ID_SHIFT_TIME IS NULL OR (@PIN_ID_SHIFT_TIME IS NOT NULL AND ID_SHIFT_TIME = @PIN_ID_SHIFT_TIME)) 
