-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 01/02/2018
-- Description: Insert directory
-- =============================================

CREATE PROCEDURE    [ADM].[SPE_INSERT_DIRECTORY]
   	  @XML_RESULT XML = '' OUT   
	, @PIN_NM_DIRECTORY VARCHAR(255)
	, @PIN_ID_PARENT_DIRECTORY UNIQUEIDENTIFIER

AS
BEGIN       
	DECLARE @V_EXIST_TRAN BIT = 0
	,@DT_SYSTEM DATETIME = GETDATE()

   	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1
		END	

		DECLARE @ID_PARENT_PATH NVARCHAR(MAX) = (SELECT TOP 1 file_stream.GetFileNamespacePath(1) FROM ADM.FS_DOCUMENT_MANAGEMENT WHERE STREAM_ID = @PIN_ID_PARENT_DIRECTORY)

		IF @PIN_ID_PARENT_DIRECTORY IS NULL
			SET @ID_PARENT_PATH = FileTableRootPath('ADM.FS_DOCUMENT_MANAGEMENT')

		INSERT INTO ADM.FS_DOCUMENT_MANAGEMENT (NAME, IS_DIRECTORY, PATH_LOCATOR)
		SELECT @PIN_NM_DIRECTORY, 1, dbo.GetNewPathLocator(GETPATHLOCATOR(@ID_PARENT_PATH))

		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = 	 ERROR_MESSAGE()
	
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		
			
	END CATCH
END

