-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CRETAE date: 07/03/2017
-- Description: Insert or update a employee
-- =============================================
CREATE PROCEDURE    [ADM].[SPE_INSERT_UPDATE_EMPLOYEE] 
    	    @XML_RESULT XML = '' OUT ,    -- --0 TO ERROR AND 1 TO CORRECT
			@PIN_ID_EMPLOYEE AS int = NULL,
			@PIN_KY_EMPLOYEE AS nvarchar(50) = NULL,
			@PIN_NM_FIRST_NAME AS nvarchar(300) = NULL,
			@PIN_NM_LAST_NAME AS nvarchar(500) = NULL,
			@PIN_XML_PHONE AS xml = NULL,
			@PIN_KY_EMAIL AS nvarchar(500) = NULL,
			@PIN_ID_BRANCH_PLANT AS int = NULL,
			@PIN_ID_POSITION AS int = NULL,
			--@PIN_ID_DEPARTMENT AS int = NULL,
			@PIN_FG_ACTIVE AS BIT =NULL
		  , @PIN_KY_USER_APP_CREATE AS nvarchar(50)
		  , @PIN_KY_USER_APP_UPDATE AS nvarchar(50)
		  , @PIN_NM_PROGRAM_CREATE AS nvarchar(50)
		  , @PIN_NM_PROGRAM_UPDATE AS nvarchar(50)
		  , @PIN_TYPE_TRANSACTION CHAR(1)             --I=INSERT   U=UPDATE

AS 
BEGIN  
	----WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE
	DECLARE @V_EXIST_TRAN BIT = 0
	,@CFE_SISTEMA DATETIME = GETDATE()

    	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1
		END	
		--WE VERIFY IF THE SPE IS GOING TO EXECUTE A UPDATE OR INSERT
		IF @PIN_TYPE_TRANSACTION='I'
	    	BEGIN
			--WE INSERT THE REGISTER ON THE TABLE  ADM.C_EMPLOYEE
			INSERT INTO ADM.C_EMPLOYEE
					   ( [KY_EMPLOYEE]
						,[NM_FIRST_NAME]
						,[NM_LAST_NAME]
						,[XML_PHONE]
						,[KY_EMAIL]
						,[ID_BRANCH_PLANT]
						,[ID_POSITION]
						--,[ID_DEPARTMENT]
						,[FG_ACTIVE]
						,[DT_CREATION]
						,[KY_USER_APP_CREATION]
						,[NM_PROGAM_CREATE]
					)
			VALUES
					     (@PIN_KY_EMPLOYEE
						, @PIN_NM_FIRST_NAME
						, @PIN_NM_LAST_NAME
						, @PIN_XML_PHONE
						, @PIN_KY_EMAIL
						, @PIN_ID_BRANCH_PLANT
						, @PIN_ID_POSITION
						--, @PIN_ID_DEPARTMENT
						, @PIN_FG_ACTIVE
						, @CFE_SISTEMA
						, @PIN_KY_USER_APP_CREATE
						, @PIN_NM_PROGRAM_CREATE
					)			
		END ELSE BEGIN
			-- WE UPDATE THE REGISTER ON THE TABLE ADM.C_EMPLOYEE
			UPDATE ADM.C_EMPLOYEE SET
   				  [KY_EMPLOYEE] = @PIN_KY_EMPLOYEE
				, [NM_FIRST_NAME] = @PIN_NM_FIRST_NAME
				, [NM_LAST_NAME] =@PIN_NM_LAST_NAME
				, [XML_PHONE] = @PIN_XML_PHONE
				, [KY_EMAIL] = @PIN_KY_EMAIL
				, [ID_BRANCH_PLANT] = @PIN_ID_BRANCH_PLANT
				, [ID_POSITION] = @PIN_ID_POSITION
				--, [ID_DEPARTMENT] = @PIN_ID_DEPARTMENT
				, [FG_ACTIVE] = @PIN_FG_ACTIVE
				, [DT_UPDATE] =@CFE_SISTEMA
				, [KY_USER_APP_UPDATE] = @PIN_KY_USER_APP_UPDATE
				, [NM_PROGRAM_UPDATE] = @PIN_NM_PROGRAM_UPDATE
			WHERE [ID_EMPLOYEE] = @PIN_ID_EMPLOYEE
									
		END
		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = 	 ERROR_MESSAGE()
	
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		
			
	END CATCH
END

