-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 07/03/2017
-- Description: get all employees
-- =============================================
-- 15/08/2017 JDR The PIN_CL_FILTER parameter is added
-- =============================================



CREATE PROCEDURE  [ADM].[SPE_GET_EMPLOYEE] 
	    @PIN_ID_EMPLOYEE AS int = NULL,
        @PIN_KY_EMPLOYEE AS nvarchar(50) = NULL,
        @PIN_NM_FIRST_NAME AS nvarchar(300) = NULL,
        @PIN_NM_LAST_NAME AS nvarchar(500) = NULL,
        @PIN_KY_EMAIL AS nvarchar(500) = NULL,
        @PIN_ID_BRANCH_PLANT AS int = NULL,
        @PIN_ID_POSITION AS int = NULL,
        --@PIN_ID_DEPARTMENT AS int = NULL,
        @PIN_FG_ACTIVE AS BIT = NULL
		--@PIN_CL_FILTER AS NVARCHAR(30) = NULL

AS   

	DECLARE @T_POSITION TABLE (
		ID_POSITION INT
	)

	--IF @PIN_CL_FILTER = 'PRODUCTION_LINE_OPERATORS' BEGIN
	--	DECLARE @XML_BRANCH_PLANT XML = (SELECT TOP 1 XML_CONFIGURATION.query('/CONFIGURATIONS[1]/ESPECIFIC_CONFIGURATION[1]/BRANCH_PLANT[@ID_BRANCH_PLANT= sql:variable("@PIN_ID_BRANCH_PLANT") ][1]/QUALITY_PROCESS[1]') FROM ADM.S_CONFIGURATION)

	--	INSERT INTO @T_POSITION (ID_POSITION)
	--	SELECT T.C.value('@ID_POSITION', 'INT')
	--	FROM @XML_BRANCH_PLANT.nodes('/QUALITY_PROCESS/OPERATOR') T(C)
	--END

	SELECT 
	    CE.ID_EMPLOYEE,
        CE.KY_EMPLOYEE,
        CE.NM_FIRST_NAME,
        CE.NM_LAST_NAME,
		US.KY_EMAIL,
		CE.ID_BRANCH_PLANT,
		CC.KY_BRANCH_PLANT,
		ISNULL(CC.NM_BRANCH_PLANT,'All') AS NM_BRANCH_PLANT,
		CC.DS_BRANCH_PLANT,
		CE.ID_POSITION,
		CP.NM_POSITION,
		CP.DS_POSITION,
		--CE.ID_DEPARTMENT,
		--CD.NM_DEPARTMENT,
		--CD.DS_DEPARTMENT,
		CE.XML_PHONE,
		CE.FG_ACTIVE,
		CASE CE.FG_ACTIVE WHEN 1 THEN 'Yes' ELSE 'No' END AS KY_ACTIVE,
		US.KY_USER

	FROM ADM.C_EMPLOYEE CE
	LEFT OUTER JOIN ADM.C_BRANCH_PLANT CC ON CC.ID_BRANCH_PLANT = CE.ID_BRANCH_PLANT
	LEFT OUTER JOIN ADM.C_POSITION CP ON CP.ID_POSITION = CE.ID_POSITION
	LEFT OUTER JOIN ADM.C_USER US ON CE.ID_EMPLOYEE = US.ID_EMPLOYEE
	--LEFT OUTER JOIN ADM.C_DEPARTMENT CD ON CD.ID_DEPARTMENT = CE.ID_DEPARTMENT
	
	WHERE (@PIN_ID_EMPLOYEE IS NULL OR (@PIN_ID_EMPLOYEE IS NOT NULL AND CE.ID_EMPLOYEE = @PIN_ID_EMPLOYEE)) AND 
			(@PIN_KY_EMPLOYEE IS NULL OR (@PIN_KY_EMPLOYEE IS NOT NULL AND CE.KY_EMPLOYEE = @PIN_KY_EMPLOYEE)) AND 
			(@PIN_NM_FIRST_NAME IS NULL OR (@PIN_NM_FIRST_NAME IS NOT NULL AND CE.NM_FIRST_NAME = @PIN_NM_FIRST_NAME)) AND 
    		(@PIN_NM_LAST_NAME IS NULL OR (@PIN_NM_LAST_NAME IS NOT NULL AND CE.NM_LAST_NAME = @PIN_NM_LAST_NAME)) AND 
			(@PIN_KY_EMAIL IS NULL OR (@PIN_KY_EMAIL IS NOT NULL AND CE.KY_EMAIL = @PIN_KY_EMAIL)) AND
			(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND (CE.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR CE.ID_BRANCH_PLANT IS NULL))) AND
			(@PIN_ID_POSITION IS NULL OR (@PIN_ID_POSITION IS NOT NULL AND CE.ID_POSITION = @PIN_ID_POSITION)) AND
			(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND CE.FG_ACTIVE = @PIN_FG_ACTIVE)) --AND
			--(@PIN_CL_FILTER IS NULL OR (@PIN_CL_FILTER = 'PRODUCTION_LINE_OPERATORS' AND EXISTS (SELECT TOP 1 1 FROM @T_POSITION TP WHERE CE.ID_POSITION = TP.ID_POSITION)))

