-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 10/03/2017
-- Description: get alL LIST CATALOG 
-- =============================================
CREATE PROCEDURE    [ADM].[SPE_GET_CATALOG_VALUES] 
	    @PIN_ID_CATALOG_VALUES AS int = NULL,
        @PIN_KY_CATALOG_VALUES AS nvarchar(50) = NULL,
        @PIN_NM_CATALOG_VALUES AS nvarchar(300) = NULL,
        @PIN_DS_CATALOG_VALUES AS nvarchar(500) = NULL,
		@PIN_FG_ACTIVE AS bit = NULL,
		@PIN_ID_LIST_CATALOG AS int = NULL,
		@PIN_NM_LIST_CATALOG As nvarchar(50) = null,
		@PIN_ID_BRANCH_PLANT as int = null

AS   
	SELECT 
	    ID_VALUE_CATALOG,
        KY_VALUE_CATALOG,
        NM_VALUE_CATALOG,
        DS_VALUE_CATALOG,
		CLC.ID_LIST_CATALOG,
		CLC.NM_LIST_CATALOG,
		CASE CVC.FG_ACTIVE WHEN 1 THEN 'Yes' ELSE 'No' END AS KY_ACTIVE
	FROM ADM.C_LIST_CATALOG CLC
	JOIN ADM.C_VALUE_CATALOG CVC ON CLC.ID_LIST_CATALOG = CVC.ID_LIST_CATALOG
	WHERE (@PIN_ID_CATALOG_VALUES IS NULL OR (@PIN_ID_CATALOG_VALUES IS NOT NULL AND ID_VALUE_CATALOG = @PIN_ID_CATALOG_VALUES )) AND 
			(@PIN_KY_CATALOG_VALUES IS NULL OR (@PIN_KY_CATALOG_VALUES IS NOT NULL AND KY_VALUE_CATALOG = @PIN_KY_CATALOG_VALUES )) AND 
			(@PIN_NM_CATALOG_VALUES IS NULL OR (@PIN_NM_CATALOG_VALUES IS NOT NULL AND NM_VALUE_CATALOG = @PIN_NM_CATALOG_VALUES )) AND 
    		(@PIN_DS_CATALOG_VALUES IS NULL OR (@PIN_DS_CATALOG_VALUES IS NOT NULL AND DS_VALUE_CATALOG = @PIN_DS_CATALOG_VALUES )) AND 
			(@PIN_NM_LIST_CATALOG IS NULL OR (@PIN_NM_LIST_CATALOG IS NOT NULL AND NM_LIST_CATALOG = @PIN_NM_LIST_CATALOG)) AND
			(@PIN_ID_LIST_CATALOG IS NULL OR (@PIN_ID_LIST_CATALOG IS NOT NULL AND CLC.ID_LIST_CATALOG = @PIN_ID_LIST_CATALOG )) AND 
			(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND CVC.FG_ACTIVE = @PIN_FG_ACTIVE)) and
			(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CVC.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

			ORDER BY NM_VALUE_CATALOG