-- =============================================
-- Author:		Gabriel Vázquez Torres
-- Create date: 06/07/2018
-- Description:	Get the transitions suggested for branch plant
-- =============================================
CREATE PROCEDURE    [ADM].[SPE_GET_BRANCH_PLANT_TRANSITIONS]
	-- Add the parameters for the stored procedure here
	@PIN_ID_BRANCH_PLANT_TRANSITION INT,
	@PIN_ID_BRANCH_PLANT INT,
	@PIN_ID_TRANSITION INT

AS
BEGIN
	

	SELECT BPT.ID_BRANCH_PLANT_TRANSITION, BPT.ID_BRANCH_PLANT, BPT.ID_TRANSITION, CT.KY_TRANSITION, CT.NM_TRANSITION, CT.DS_TRANSITION, CT.NO_STANDARD_TIME
	FROM [ADM].[C_BRANCH_PLANT_TRANSITION] BPT
		INNER JOIN PRD.C_TRANSITION CT ON BPT.ID_TRANSITION = CT.ID_TRANSITION
	WHERE 
		(@PIN_ID_BRANCH_PLANT_TRANSITION IS NULL OR (@PIN_ID_BRANCH_PLANT_TRANSITION IS NOT NULL AND BPT.ID_BRANCH_PLANT_TRANSITION = @PIN_ID_BRANCH_PLANT_TRANSITION)) AND
		(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND BPT.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT)) AND
		(@PIN_ID_TRANSITION IS NULL OR (@PIN_ID_TRANSITION IS NOT NULL AND BPT.ID_TRANSITION = @PIN_ID_TRANSITION))

END

