
CREATE PROCEDURE    [ADM].[SPE_GET_VALUE_CATALOG] 
 
		@PIN_ID_LIST_CATALOG INT = NULL

AS

SELECT  ID_VALUE_CATALOG,
		KY_VALUE_CATALOG,
		NM_VALUE_CATALOG,
		DS_VALUE_CATALOG,
		ID_LIST_CATALOG,
		FG_ACTIVE,
		DT_CREATION,
		DT_UPDATE,
		KY_USER_APP_CREATION,
		KY_USER_APP_UPDATE,
		NM_PROGAM_CREATE,
		NM_PROGRAM_UPDATE
FROM ADM.C_VALUE_CATALOG
WHERE (@PIN_ID_LIST_CATALOG IS NULL OR (@PIN_ID_LIST_CATALOG IS NOT NULL AND UPPER(ID_LIST_CATALOG) = UPPER(@PIN_ID_LIST_CATALOG ))) 
	  AND FG_ACTIVE=1

