-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 02/03/2017
-- Description: get all branch plants 
-- =============================================
-- 24/01/2018 JDR ID_TIME_ZONE and TZ_OFFSET columns were added
-- 09/27/2018 JDR ID_CARTON_ITEM_CATALOG and ID_THICKNESS_METRIC columns were added
-- =============================================


CREATE PROCEDURE    [ADM].[SPE_GET_BRANCH_PLANT] 
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
        @PIN_KY_BRANCH_PLANT AS nvarchar(50) = NULL,
        @PIN_NM_BRANCH_PLANT AS nvarchar(300) = NULL,
        @PIN_DS_BRANCH_PLANT AS nvarchar(500) = NULL,
        @PIN_ID_FILE AS nvarchar(255) = NULL
AS   

	SELECT CC.ID_BRANCH_PLANT
		, CC.KY_BRANCH_PLANT
		, CC.NM_BRANCH_PLANT
		, CC.DS_BRANCH_PLANT
		, CC.ID_FILE
		, CC.ID_TIME_ZONE
		, CC.TZ_OFFSET
		, CC.FG_QUALITY_INSPECTOR
		, FSS.name AS NM_FILE
		, FSS.file_stream AS FS_FILE
		, CC.ID_WIDTH_METRIC
		, CC.NO_WIDTH_MIN_VALUE
		, CC.NO_WIDTH_MAX_VALUE
		, CC.ID_LENGTH_METRIC
		, CC.NO_LENGTH_MIN_VALUE
		, CC.NO_LENGTH_MAX_VALUE
		, CC.ID_WEIGHT_METRIC
		, CC.NO_WEIGHT_MIN_VALUE
		, CC.NO_WEIGHT_MAX_VALUE
		, CC.ID_CUT_TIME_METRIC
		, CC.ID_TOTAL_CUT_WEIGHT_METRIC
		, CC.ID_LBS_PER_HOUR_METRIC
		, CC.ID_PARTS_EXT_METRIC
		, CC.ID_WEB_WIDTH_METRIC
		, CC.ID_DIE_PUMP_METRIC
		, CC.ID_THICKNESS_METRIC
		, CC.ID_CARTON_ITEM_CATALOG
	FROM ADM.C_BRANCH_PLANT CC
		LEFT OUTER JOIN ADM.FS_FILE_SYSTEM FSS 
			ON FSS.stream_id = cc.ID_FILE
	WHERE (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND (CC.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR CC.ID_BRANCH_PLANT IS NULL))) 
		AND (@PIN_KY_BRANCH_PLANT IS NULL OR (@PIN_KY_BRANCH_PLANT IS NOT NULL AND CC.KY_BRANCH_PLANT = @PIN_KY_BRANCH_PLANT)) 
		AND (@PIN_NM_BRANCH_PLANT IS NULL OR (@PIN_NM_BRANCH_PLANT IS NOT NULL AND CC.NM_BRANCH_PLANT = @PIN_NM_BRANCH_PLANT)) 
		AND (@PIN_DS_BRANCH_PLANT IS NULL OR (@PIN_DS_BRANCH_PLANT IS NOT NULL AND CC.DS_BRANCH_PLANT = @PIN_DS_BRANCH_PLANT)) 
		AND (@PIN_ID_FILE IS NULL OR (@PIN_ID_FILE IS NOT NULL AND CC.ID_FILE = @PIN_ID_FILE))
	ORDER BY CC.KY_BRANCH_PLANT

