-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares	
-- CRETAE date: 04/05/2018
-- Description: Insert or update FUNCTION HELP
-- =============================================
CREATE PROCEDURE    [ADM].[SPE_INSERT_UPDATE_FUNCTION_HELP] 
	@XML_RESULT				XML = '' OUT ,    -- --0 TO ERROR AND 1 TO CORRECT
	@PIN_ID_FUNCTION		AS int = NULL,
	@PIN_ID_HELP			AS int = NULL,
	@PIN_KY_USER_APP		AS nvarchar(50),
	@PIN_NM_PROGRAM			AS nvarchar(50),
	@PIN_TYPE_TRANSACTION	CHAR(1)             --I=INSERT   U=UPDATE

AS 
BEGIN  
	----WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE
	DECLARE @V_EXIST_TRAN BIT = 0
	,@CFE_SISTEMA DATETIME = GETDATE()
	,@ID_FUNCTION INT
    	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1
		END	

		SELECT @ID_FUNCTION = FH.ID_FUNCTION
		  FROM ADM.K_FUNCTION_HELP FH
		 WHERE FH.ID_FUNCTION = @PIN_ID_FUNCTION


		--WE VERIFY IF THE SPE IS GOING TO EXECUTE A UPDATE OR INSERT
		IF @ID_FUNCTION IS NULL
	    	BEGIN
			--WE INSERT THE REGISTER ON THE TABLE  ADM.C_EMPLOYEE
			INSERT INTO ADM.K_FUNCTION_HELP
					   ( 
						 [ID_FUNCTION],
						 [ID_HELP],
						 [DT_CREATION],
						 [KY_USER_APP_CREATION],
						 [NM_PROGRAM_CREATE]
					)
			VALUES
					     (
						  @PIN_ID_FUNCTION,
						  @PIN_ID_HELP,
						  @CFE_SISTEMA,
						  @PIN_KY_USER_APP,
						  @PIN_NM_PROGRAM
					)			
		END ELSE BEGIN
			-- WE UPDATE THE REGISTER ON THE TABLE ADM.C_EMPLOYEE
			UPDATE ADM.K_FUNCTION_HELP
			   SET [ID_HELP] =@PIN_ID_HELP,
				   [DT_UPDATE] =@CFE_SISTEMA,
				   [KY_USER_APP_UPDATE] = @PIN_KY_USER_APP,
				   [NM_PROGRAM_UPDATE] = @PIN_NM_PROGRAM
			WHERE [ID_FUNCTION] =@PIN_ID_FUNCTION
									
		END
		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = 	 ERROR_MESSAGE()
	
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		--SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		--SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,@ERROR_MESSAGE)
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, @ERROR_MESSAGE)
		
			
	END CATCH
END

