-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 07/03/2017
-- Description: get all user catalogs
-- =============================================
-- 22/01/2018 JDR CE.NM_FIRST_NAME AND CE.NM_LAST_NAME columns added to the projection
-- =============================================


CREATE PROCEDURE    [ADM].[SPE_GET_USER_CATALOGUES] 
	    @PIN_KY_USER AS VARCHAR(100) = NULL

AS   
	BEGIN
		DECLARE @PIN_NM_USER AS nvarchar(300) = NULL
			, @PIN_KY_EMAIL AS nvarchar(500) = NULL
			, @PIN_NM_PASSWORD AS nvarchar(100) = NULL
			, @PIN_DT_CHANGE_PASSWORD AS DATETIME = NULL
			, @PIN_KY_CHANGE_PASSWORD AS nvarchar(100) = NULL
			, @PIN_FG_CHANGE_PASSWORD AS BIT = NULL
			, @PIN_ID_ROLE AS INT = NULL
			, @PIN_ID_EMPLOYEE AS INT = NULL
			, @PIN_NM_FIRST_NAME AS NVARCHAR(300) = NULL
			, @PIN_NM_LAST_NAME AS NVARCHAR(500) = NULL
			, @PIN_FG_ACTIVE AS bit = NULL
			, @PIN_ID_BRANCH_PLANT AS INT = NULL
			, @PIN_DT_INACTIVE AS DATETIME = NULL
			, @XML_BRANCHPLANTS AS XML
			, @XML_ROLES AS XML
			, @XML_CATALOGS AS XML

		SET @XML_BRANCHPLANTS = (
			SELECT 	    
				BP.ID_BRANCH_PLANT  AS "@ID_BRANCH_PLANT",
				BP.KY_BRANCH_PLANT  AS "@KY_BRANCH_PLANT",
				BP.NM_BRANCH_PLANT  AS "@NM_BRANCH_PLANT",
				BP.DS_BRANCH_PLANT  AS "@DS_BRANCH_PLANT",
				BP.ID_FILE  AS "@ID_FILE"
			FROM ADM.C_BRANCH_PLANT BP
			FOR XML PATH ('BRANCHPLANT'), ROOT ('BRANCHPLANTS')
		)

		SET @XML_ROLES = (
			SELECT 	    
				CR.[ID_ROLE]  AS "@ID_ROLE",
				CR.[KY_ROLE]  AS "@KY_ROLE",
				CR.[NM_ROLE] AS "@NM_ROLE",
				CR.[FG_ACTIVE]  AS "@FG_ACTIVE",
				CR.[DT_INACTIVE]  AS "@DT_INACTIVE",
				CR.[DT_CREATION]  AS "@DT_CREATION"
			FROM ADM.C_ROLE CR
			FOR XML PATH ('ROLE'), ROOT ('ROLES')
		)


		SET @XML_CATALOGS = (
			SELECT @XML_BRANCHPLANTS,@XML_ROLES
			FOR XML PATH ('CATALOGS')
		)


		SELECT @PIN_KY_USER = CU.KY_USER
			, @PIN_NM_USER = CU.NM_USER
			, @PIN_KY_EMAIL = CU.KY_EMAIL
			, @PIN_NM_PASSWORD = CU.NM_PASSWORD
			, @PIN_DT_CHANGE_PASSWORD = CU.DT_CHANGE_PASSWORD
			, @PIN_KY_CHANGE_PASSWORD = CU.KY_CHANGE_PASSWORD
			, @PIN_FG_CHANGE_PASSWORD = CU.FG_CHANGE_PASSWORD
			, @PIN_ID_ROLE = CU.ID_ROLE
			, @PIN_ID_EMPLOYEE = CU.ID_EMPLOYEE
			, @PIN_NM_FIRST_NAME = CE.NM_FIRST_NAME
			, @PIN_NM_LAST_NAME = CE.NM_LAST_NAME
			, @PIN_FG_ACTIVE = CU.FG_ACTIVE
			, @PIN_ID_BRANCH_PLANT = CU.ID_BRANCH_PLANT
			, @PIN_DT_INACTIVE = CU.DT_INACTIVE
		FROM ADM.C_USER CU
			LEFT OUTER JOIN ADM.C_ROLE CR 
				ON CR.ID_ROLE = CU.ID_ROLE
			LEFT OUTER JOIN ADM.C_EMPLOYEE CE 
				ON CE.ID_EMPLOYEE = CU.ID_EMPLOYEE
			LEFT OUTER JOIN ADM.C_BRANCH_PLANT BP 
				ON BP.ID_BRANCH_PLANT = CU.ID_BRANCH_PLANT
		WHERE CU.KY_USER = @PIN_KY_USER


		SELECT  @PIN_KY_USER AS KY_USER
			, @PIN_NM_USER AS NM_USER
			, @PIN_KY_EMAIL AS KY_EMAIL
			, @PIN_NM_PASSWORD AS NM_PASSWORD
			, @PIN_DT_CHANGE_PASSWORD AS DT_CHANGE_PASSWORD
			, @PIN_KY_CHANGE_PASSWORD AS KY_CHANGE_PASSWORD
			, @PIN_FG_CHANGE_PASSWORD AS FG_CHANGE_PASSWORD
			, @PIN_ID_ROLE AS ID_ROLE
			, @PIN_ID_EMPLOYEE AS ID_EMPLOYEE
			, @PIN_NM_FIRST_NAME AS NM_FIRST_NAME
			, @PIN_NM_LAST_NAME AS NM_LAST_NAME
			, @PIN_FG_ACTIVE AS FG_ACTIVE
			, @PIN_ID_BRANCH_PLANT AS ID_BRANCH_PLANT
			, @PIN_DT_INACTIVE AS DT_INACTIVE
			,@XML_CATALOGS AS XML_CATALOGS
END

