-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 04/05/2018
-- Description: get help per function
-- =============================================

CREATE PROCEDURE    [ADM].[SPE_GET_FUNCTION_HELP]
 	  @PIN_ID_FUNCTION		AS INT = NULL
	, @PIN_ID_HELP			AS INT = NULL
	, @PIN_NM_HELP			AS NVARCHAR(100) = NULL
	, @PIN_KY_FUNCTION		AS NVARCHAR(50) = NULL
AS   
	SELECT SF.ID_FUNCTION, 
		   SF.NM_FUNCTION, 
		   SF.KY_FUNCTION,
		   FH.ID_HELP, 
		   CH.KY_HELP, 
		   CH.NM_HELP
		 FROM ADM.S_FUNCTION SF
	LEFT JOIN ADM.K_FUNCTION_HELP FH ON SF.ID_FUNCTION = FH.ID_FUNCTION
	LEFT JOIN ADM.C_HELP CH ON FH.ID_HELP = CH.ID_HELP
		WHERE SF.KY_TYPE_FUNCTION = 'MENUGRAL'
		  AND (@PIN_ID_FUNCTION IS NULL OR (@PIN_ID_FUNCTION IS NOT NULL AND SF.ID_FUNCTION = @PIN_ID_FUNCTION)) 
		  AND (@PIN_ID_HELP IS NULL OR (@PIN_ID_HELP IS NOT NULL AND FH.ID_HELP = @PIN_ID_HELP)) 
		  AND (@PIN_NM_HELP IS NULL OR (@PIN_NM_HELP IS NOT NULL AND CH.NM_HELP = @PIN_NM_HELP))
		  AND (@PIN_KY_FUNCTION IS NULL OR (@PIN_KY_FUNCTION IS NOT NULL AND SF.KY_FUNCTION= @PIN_KY_FUNCTION ))
	 ORDER BY SF.KY_FUNCTION

