-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 27/02/2017
-- Description: Get the data from the S_CONFIGURATION table 
-- =============================================
CREATE PROCEDURE    [ADM].[SPE_GET_CONFIGURATION] 
	  @PIN_XML_CONFIGURATION AS xml = NULL
	, @PIN_KY_USER_UPDATE AS nvarchar(50) = NULL
	
AS   

	DECLARE @XML_SHIFTS XML;
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	DECLARE @XML_CONFIGURATION XML = (
		SELECT TOP 1 XML_CONFIGURATION FROM ADM.S_CONFIGURATION
	)			

	DECLARE @FI_LOGOTYPE VARBINARY(MAX) = (
		SELECT TOP 1 file_stream FROM ADM.FS_FILE_SYSTEM WHERE NAME = @XML_CONFIGURATION.value('/CONFIGURATIONS[1]/ESPECIFIC_CONFIGURATION[1]/BRANCH_PLANT[1]/LOGOTYPE[1]/@NM_FILE[1]', 'VARCHAR(200)')
	)

	    SET @XML_SHIFTS = (
		SELECT 	    
	    CS.ID_SHIFT  AS "@ID_SHIFT",
        CS.KY_SHIFT  AS "@KY_SHIFT",
        CS.NM_SHIFT  AS "@NM_SHIFT",
        CS.INITIAL_SHIFT_TIME  AS "@INITIAL_SHIFT_TIME",
        CS.FINAL_SHIFT_TIME  AS "@FINAL_SHIFT_TIME"
		FROM [ADM].[VW_C_SHIFT] CS
		FOR XML PATH ('SHIFT'), ROOT ('SHIFTS')
	)

	SELECT @XML_CONFIGURATION AS XML_CONFIGURATION
		, @FI_LOGOTYPE AS FI_LOGOTYPE
		, @XML_SHIFTS AS XML_SHIFTS

