-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 02/02/2018
-- Description: Get production lines by document management
-- =============================================

CREATE PROCEDURE    [ADM].[SPE_GET_PRODUCTION_LINES_DOCUMENT_MANAGEMENT]
	@PIN_ID_STREAM UNIQUEIDENTIFIER
	, @PIN_ID_BRANCH_PLANT INT

AS
	SELECT CDPL.ID_DOCUMENT_PRODUCTION_LINE, CPL.ID_PRODUCTION_LINE, CPL.KY_PRODUCTION_LINE, CPL.NM_PRODUCTION_LINE, CPL.NO_POUNDS_PER_HOUR, VSPLT.NM_PRODUCTION_LINE_TYPE
	FROM PRD.C_PRODUCTION_LINE CPL
		INNER JOIN ADM.C_DOCUMENT_PRODUCTION_LINE CDPL
			ON CPL.ID_PRODUCTION_LINE = CDPL.ID_PRODUCTION_LINE
			AND CDPL.ID_STREAM = @PIN_ID_STREAM
			AND CPL.FG_ACTIVE = 1
		INNER JOIN ADM.VW_S_PRODUCTION_LINE_TYPE VSPLT
			ON CPL.ID_PRODUCTION_LINE_TYPE = VSPLT.ID_PRODUCTION_LINE_TYPE
	WHERE (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CPL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

