





CREATE VIEW [PRD].[VW_C_PROCESS_NOTIFICATION] AS (
SELECT 1 ID_PROCESS_NOTIFICATION, 'ISSUE_CREATED' KY_PROCESS, 'WorkOrders' NM_FORM, 'There is a lost time event in the line @NM_PRODUCTION_LINE with the leadman @NM_LEADMAN about the problem code @PIN_NM_PROBLEM_CODE,in the problem area @PIN_NM_PROBLEM_AREA' DS_BODY, 'Issue Notification' DS_TITLE, 'Issue Notification' DS_SUBJECT ,'/PRD/ConfirmUserWindow.aspx' NM_URL ,'?ID_ISSUE=@NM_URL_PARAMETERS' NM_URL_PARAMETERS, '500' NO_WIDTH, '470' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '0' FG_ALERT, '1' FG_FORM UNION ALL
SELECT 2 ID_PROCESS_NOTIFICATION, 'ISSUE_SCALING' KY_PROCESS, 'Default' NM_FORM, 'The @USER_INVOLVED has not been finished the lost time in the line: @LINE' DS_BODY, 'Issue Notification' DS_TITLE, 'Issue Notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '300' NO_WIDTH, '140' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 3 ID_PROCESS_NOTIFICATION, 'FORM' KY_PROCESS, 'Default' NM_FORM, 'The @USER_INVOLVED has not been captures the readings in the line: @LINE' DS_BODY, 'Form Notification' DS_TITLE, 'Form Notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '380' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 4 ID_PROCESS_NOTIFICATION, 'FORM_ERROR' KY_PROCESS, 'Default' NM_FORM, 'Readings with errors have been captured on @LINE with work order number: @WO' DS_BODY, 'Readings Notification' DS_TITLE, 'Readings Notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '300' NO_WIDTH, '140' NO_HEIGHT, '1' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 5 ID_PROCESS_NOTIFICATION, 'FORM_ERROR_RETURN' KY_PROCESS, 'Default' NM_FORM, 'The readings have been successfully captured(with errors in metrics)' DS_BODY, 'Readings Notification' DS_TITLE, 'Readings Notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '300' NO_WIDTH, '140' NO_HEIGHT, '1' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 6 ID_PROCESS_NOTIFICATION, 'CLOSE_PALLET' KY_PROCESS, 'ALL' NM_FORM, 'The leadman @NM_LEADMAN has closed a pallet with the number @NO_PALLET in the production line @NM_PRODUCTION_LINE ,please inspect it.' DS_BODY, 'Close Pallet' DS_TITLE, 'Close pallet' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 7 ID_PROCESS_NOTIFICATION, 'CLOSE_PALLET_SCALING' KY_PROCESS, 'ALL' NM_FORM, 'The quality inspector @NM_QUALITY_INSPECTOR has not inspected the pallet number @PIN_NO_PALLET in the production line  @NM_PRODUCTION_LINE.' DS_BODY, 'Close Pallet' DS_TITLE, 'Close pallet' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 8 ID_PROCESS_NOTIFICATION, 'VERDICT' KY_PROCESS, 'ALL' NM_FORM, 'The Quality inspector @QUALITY_INSPECTOR has not accepted the pallet # @NO_PALLET , please get together to make a final decision.' DS_BODY, 'Skid verdict' DS_TITLE, 'Skid verdict' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '1' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 9 ID_PROCESS_NOTIFICATION, 'VERDICT_SCALING' KY_PROCESS, 'ALL' NM_FORM, 'No leadman or set-up tech has attended the skid #@NO_PALLET in the line @NM_PRODUCTION_LINE' DS_BODY, 'Skid verdict' DS_TITLE, 'Skid verdict' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '140' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 10 ID_PROCESS_NOTIFICATION, 'MBR_RESOLUTION' KY_PROCESS, 'ALL' NM_FORM, 'A skid #@NO_PALLET from #@ID_WORK_ORDER was placed on hold but non acceptance status remains due to "@DS_EXPLANATION". Please meet to determine disposition' DS_BODY, 'MRB' DS_TITLE, 'MRB' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 11 ID_PROCESS_NOTIFICATION, 'MBR_RESOLUTION_SCALING' KY_PROCESS, 'ALL' NM_FORM, 'The Quality inspector @QUALITY_INSPECTOR has not accepted the pallet # @NO_PALLET , please get together to make a final decision.' DS_BODY, 'Skid verdict' DS_TITLE, 'Skid verdict' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 12 ID_PROCESS_NOTIFICATION, 'SCHEDULER' KY_PROCESS, 'ALL' NM_FORM, 'The Line: @LINE has a schedule problem whith the Work Order:@NO_WORK_ORDER' DS_BODY, 'Scheduled Notification' DS_TITLE, 'Scheduled Notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '500' NO_WIDTH, '310' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM) UNION ALL
SELECT 13 ID_PROCESS_NOTIFICATION, 'OPEN_PALLET' KY_PROCESS, 'ALL' NM_FORM, 'The leadman @NM_LEADMAN has opened a skid with the number @NO_PALLET in the production line @NM_PRODUCTION_LINE ,please inspect it.' DS_BODY, 'Open Pallet' DS_TITLE, 'Open Pallet' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '1' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM UNION ALL
SELECT 14 ID_PROCESS_NOTIFICATION, 'DOC_SENDED' KY_PROCESS, 'ALL' NM_FORM, 'You have a document to read.' DS_BODY, 'Document sended' DS_TITLE, 'Document sended' DS_SUBJECT ,'/Administration/DocumentManagement/NotifierDocumentViewer.aspx' NM_URL ,'?idDocument' NM_URL_PARAMETERS, '0' NO_WIDTH, '0' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '0' FG_ALERT, '1' FG_FORM UNION ALL
SELECT 10 ID_PROCESS_NOTIFICATION, 'BACK_TO_REVIEW' KY_PROCESS, 'ALL' NM_FORM, 'The follows pallets @PALLETS has been returned from the warehouse to check again ,please attend it.' DS_BODY, 'Veredict' DS_TITLE, 'Back to review pallet notification' DS_SUBJECT ,NULL NM_URL ,NULL NM_URL_PARAMETERS, '400' NO_WIDTH, '180' NO_HEIGHT, '0' FG_EMAIL, '0' FG_TELEGRAM, '1' FG_ALERT, '0' FG_FORM