





CREATE VIEW [PRD].[VW_K_WORK_ORDER_JDEDWARDS] AS (
SELECT ID_WORK_ORDER
	, KY_CUSTOMER
	, ISNULL(NM_CUSTOMER, '') AS NM_CUSTOMER
	, NO_WORK_ORDER
	, NO_ORDER
	, NO_SEQ
	, ID_ITEM
	, KY_ITEM
	, NM_ITEM
	, ID_PRODUCTION_LINE
	, KY_PRODUCTION_LINE
	, NM_PRODUCTION_LINE
	, KY_BRANCH_PLANT
	, CAST(DATEADD(YEAR, FLOOR(DT_WORK_ORDER/1000),0) + (DT_WORK_ORDER % 1000) - 1 AS DATE) AS DT_WORK_ORDER
	, NO_RUN_QTY
	, NO_BOX_QTY
	, NM_MATERIAL
	, NM_COLOR
	, NO_LENGHT
	, NO_WIDTH
	, NO_THICKNESS
	, KY_PACKAGE
	, CONVERT(INT, PACKED) AS PACKED
	, NO_QTY_SKID
	, CONVERT(INT, NO_SHIPING_WEIGHT_PER_HR) AS NO_SHIPING_WEIGHT_PER_HR
	, CAST(DATEADD(YEAR, FLOOR(DT_REQ_DATE / 1000), 0) + (DT_REQ_DATE % 1000) - 1 AS DATE) AS DT_REQ_DATE
	, CL_STATUS
FROM OPENQUERY (JDEPROD, '
SELECT W.WADOCO AS ID_WORK_ORDER
	, W.WAAN8 AS KY_CUSTOMER
	, CN.ABALPH AS NM_CUSTOMER
	, W.WADOCO AS NO_WORK_ORDER
	, W.WARESC AS NO_ORDER
	, W.WARESC AS NO_SEQ
	, W.WAITM AS ID_ITEM
	, W.WALITM AS KY_ITEM
	, W.WADL01 AS NM_ITEM
	, W.WAANSA AS ID_PRODUCTION_LINE
	, W.WAPARS AS KY_PRODUCTION_LINE
	, PL.ABALPH AS NM_PRODUCTION_LINE
	, LTRIM(RTRIM(W.WAMCU)) AS KY_BRANCH_PLANT
	, W.WASTRT AS DT_WORK_ORDER
	, W.WAUORG AS NO_RUN_QTY
	, BQ.UMCONV / 10000000 AS NO_BOX_QTY
	, W.WAWR02 AS NM_MATERIAL
	, W.WAWR01 AS NM_COLOR
	, M.IQGWID / 10000 AS NO_LENGHT
	, M.IQGDEP / 10000 AS NO_WIDTH
	, M.IQGHET / 10000 AS NO_THICKNESS
	, SQ.UMCONV / 10000000 AS KY_PACKAGE
	, 0 AS PACKED
	, SQ.UMCONV / 10000000 AS NO_QTY_SKID
	, W.WARORN AS NO_SHIPING_WEIGHT_PER_HR
	, W.WADRQJ AS DT_REQ_DATE
	, W.WASRST AS CL_STATUS
FROM PRODDTA.F4801 W
	LEFT JOIN PRODDTA.F0101 CN
		ON W.WAAN8 = CN.ABAN8
	LEFT JOIN PRODDTA.F0101 PL
		ON W.WAANSA = PL.ABAN8
	LEFT JOIN PRODDTA.F46011 M
		ON W.WAITM = M.IQITM
		AND W.WAMCU = M.IQMCU
	LEFT JOIN PRODDTA.F41002 BQ
		ON W.WAITM = BQ.UMITM
		AND BQ.UMUM = ''CT''
		AND BQ.UMRUM = ''EA''
	LEFT JOIN PRODDTA.F41002 SQ
		ON W.WAITM = SQ.UMITM
		AND SQ.UMUM = ''PL''
		AND SQ.UMRUM IN (''CT'', ''EA'')
WHERE W.WASRST = ''45''
')

	--SELECT W.WADOCO AS ID_WORK_ORDER
	--, W.WAAN8 AS KY_CUSTOMER
	--, CN.ABALPH AS NM_CUSTOMER
	--, W.WADOCO AS NO_WORK_ORDER
	--, W.WARESC AS NO_ORDER
	--, W.WARESC AS NO_SEQ
	--, W.WAITM AS ID_ITEM
	--, W.WALITM AS KY_ITEM
	--, W.WADL01 AS NM_ITEM
	--, W.WAANSA AS ID_PRODUCTION_LINE
	--, W.WAPARS AS KY_PRODUCTION_LINE
	--, PL.ABALPH AS NM_PRODUCTION_LINE
	--, LTRIM(RTRIM(W.WAMCU)) AS KY_BRANCH_PLANT
	--, CAST(DATEADD(YEAR, FLOOR(W.WASTRT/1000),0) + (W.WASTRT % 1000) - 1 AS DATE) AS DT_WORK_ORDER
	--, W.WAUORG AS NO_RUN_QTY
	--, BQ.UMCONV / 10000000 AS NO_BOX_QTY
	--, W.WAWR02 AS NM_MATERIAL
	--, W.WAWR01 AS NM_COLOR
	--, M.IQGWID / 10000 AS NO_LENGHT
	--, M.IQGDEP / 10000 AS NO_WIDTH
	--, M.IQGHET / 10000 AS NO_THICKNESS
	--, SQ.UMCONV / 10000000 AS KY_PACKAGE
	--, CONVERT(INT, 0) AS PACKED
	--, SQ.UMCONV / 10000000 AS NO_QTY_SKID
	--, CONVERT(INT, W.WARORN) AS NO_SHIPING_WEIGHT_PER_HR
	--, CAST(DATEADD(YEAR, FLOOR(W.WADRQJ/1000),0) + (W.WADRQJ % 1000) - 1 AS DATE) AS DT_REQ_DATE
	--, W.WASRST AS CL_STATUS
	----, M.*
	--FROM JDEPROD..PRODDTA.F4801 W
	--	INNER JOIN JDEPROD..PRODDTA.F0101 CN
	--		ON W.WAAN8 = CN.ABAN8
	--		AND W.WASRST = '45'
	--	LEFT JOIN JDEPROD..PRODDTA.F0101 PL
	--		ON W.WAANSA = PL.ABAN8
	--	LEFT JOIN JDEPROD..PRODDTA.F46011 M
	--		ON W.WAITM = M.IQITM
	--		AND W.WAMCU = M.IQMCU
	--	LEFT JOIN JDEPROD..PRODDTA.F41002 BQ
	--		ON W.WAITM = BQ.UMITM
	--		AND BQ.UMUM = 'CT'
	--		AND BQ.UMRUM = 'EA'
	--	LEFT JOIN JDEPROD..PRODDTA.F41002 SQ
	--		ON W.WAITM = SQ.UMITM
	--		AND SQ.UMUM = 'PL'
	--		AND SQ.UMRUM IN ('CT', 'EA')
)