
-- =============================================
-- Author:		Javier Díaz Barrón
-- Create date: 24/04/2017
-- Description:	Function to Get the time elapsed by w.o. or Line
-- =============================================
CREATE FUNCTION [dbo].[F_GET_TIME_ELAPSED]
(	
	 @PIN_ID_WORK_ORDER INT
	,@PIN_ID_PRODUCTION_LINE INT
	,@PIN_PROCESS NVARCHAR(50) --'WORK_ORDER' , 'LINE'
)
RETURNS INT
AS
BEGIN
	DECLARE @RESULT INT
	IF @PIN_PROCESS = 'WORK_ORDER'
	BEGIN
		SELECT 	
			@RESULT=(
				DATEDIFF(MINUTE,
							(SELECT DT_INITIAL_TIME FROM  PRD.K_QA27  
								WHERE 
									ID_QA27 =(SELECT MIN(ID_QA27) FROM PRD.K_QA27 WHERE ID_WORK_ORDER=WO.ID_WORK_ORDER)),
							(SELECT ISNULL(DT_FINAL_TIME,GETDATE()) FROM  PRD.K_QA27  
								WHERE 
									ID_QA27 =(SELECT MAX(ID_QA27) FROM PRD.K_QA27 WHERE ID_WORK_ORDER=WO.ID_WORK_ORDER)))
		   	-
				ISNULL((SELECT SUM(CAST(LTRIM(DATEDIFF(MINUTE, DT_ISSUE, ISNULL(DT_ISSUE_CLOSED,GETDATE()))) AS INT)) FROM PRD.K_ISSUE 
					WHERE 
						ID_WORK_ORDER = WO.ID_WORK_ORDER),0)
			)		
			FROM PRD.K_WORK_ORDER WO			
			WHERE 
				(@PIN_ID_WORK_ORDER IS NULL OR (1 IS NOT NULL AND WO.ID_WORK_ORDER = @PIN_ID_WORK_ORDER))  AND 
			   	WO.KY_STATUS NOT IN ('SCHEDULED')
	END
	ELSE
	BEGIN
		   						
		SELECT 
			@RESULT=(
				ISNULL(DATEDIFF(MINUTE,ISNULL(KF.DT_FORM,GETDATE()) ,GETDATE()),0)
				---
				--ISNULL((SELECT SUM(CAST(LTRIM(DATEDIFF(MINUTE, DT_ISSUE, ISNULL(DT_ISSUE_CLOSED,GETDATE()))) AS INT)) FROM PRD.K_ISSUE 
				--		WHERE 
				--			ID_WORK_ORDER = WO.ID_WORK_ORDER),0)
			)
		FROM PRD.K_WORK_ORDER WO
		LEFT JOIN PRD.K_FORM KF ON KF.ID_PRODUCTION_LINE = WO.ID_PRODUCTION_LINE
		WHERE 
		WO.ID_PRODUCTION_LINE=@PIN_ID_PRODUCTION_LINE AND WO.KY_STATUS='RUNNING' 
		AND KF.ID_K_FORM =(SELECT MAX(ID_K_FORM) FROM PRD.K_FORM WHERE ID_PRODUCTION_LINE =@PIN_ID_PRODUCTION_LINE)
		
	
	
	
	END
	
		   
	
		RETURN @RESULT
END