-- =============================================
-- Author:		Javier Díaz Barrón
-- Create date: 19/05/2017
-- Description:	Function to Get the time elapsed by w.o. or Line
-- =============================================
CREATE FUNCTION [dbo].[F_GET_SHIFT_MINUTES]
(	
	 @CURRENT_TIME DATETIME	=NULL
	,@PIN_DT_INITIAL_SHIFT_TIME AS DATETIME=NULL
	,@PIN_DT_FINAL_SHIFT_TIME AS DATETIME=NULL
	)
RETURNS INT
AS
BEGIN
   
   	DECLARE @MINUTES INT
	
	 ;WITH TB_TIME AS (
		SELECT 	
		CAST(@PIN_DT_INITIAL_SHIFT_TIME AS TIME) INITIAL_TIME,CAST(@PIN_DT_FINAL_SHIFT_TIME AS TIME) FINAL_TIME,CAST(@CURRENT_TIME AS TIME) CURRENT_TIME_VALUE
		,CASE  
			WHEN CAST(@CURRENT_TIME AS DATE) > CAST(@PIN_DT_FINAL_SHIFT_TIME AS DATE)
				THEN (SELECT TOP 1 NO_SHIFT_TIME * 60 FROM ADM.VW_C_SHIFT)
			WHEN CAST(@PIN_DT_INITIAL_SHIFT_TIME AS TIME) > CAST(@PIN_DT_FINAL_SHIFT_TIME AS TIME) AND CAST(@CURRENT_TIME AS TIME) < CAST(@PIN_DT_INITIAL_SHIFT_TIME AS TIME)
				THEN DATEDIFF(MI,CAST(@PIN_DT_INITIAL_SHIFT_TIME AS TIME),'23:59:59') + DATEDIFF(MI,'00:00:00',CAST(@CURRENT_TIME AS TIME)) + 1
			WHEN @CURRENT_TIME > @PIN_DT_FINAL_SHIFT_TIME
				THEN (SELECT TOP 1 NO_SHIFT_TIME * 60 FROM ADM.VW_C_SHIFT)
			WHEN @CURRENT_TIME < @PIN_DT_INITIAL_SHIFT_TIME
				THEN (SELECT TOP 1 NO_SHIFT_TIME * 60 FROM ADM.VW_C_SHIFT)
			ELSE
				abs(DATEDIFF(MI,CAST(@PIN_DT_INITIAL_SHIFT_TIME AS TIME),CAST(@CURRENT_TIME AS TIME)))
		  END MINUTES
		)
		
		SELECT 				
			@MINUTES=CASE
				WHEN MINUTES > (SELECT TOP 1 NO_SHIFT_TIME * 60 FROM ADM.VW_C_SHIFT)
					THEN (SELECT TOP 1 NO_SHIFT_TIME * 60 FROM ADM.VW_C_SHIFT)
				ELSE
					MINUTES
			   END
		 FROM TB_TIME
	
		RETURN @MINUTES
END