CREATE PROCEDURE [PRD].[SPE_INSERT_REPORT]
@PIN_DT_REPORT DATE,
@PIN_NM_SHIFT NVARCHAR(50),
@PIN_REPORT text,
@PIN_SAVEREPORT text
AS
BEGIN
	DECLARE @EXIST AS INT
	DECLARE @IDREP  AS INT
	SET @EXIST = (SELECT COUNT(*) FROM PRD.SAVEREPORT WHERE DT_REPORT = @PIN_DT_REPORT AND NM_SHIFT = @PIN_NM_SHIFT)

	IF (@EXIST > 0)
	BEGIN
		SET @IDREP = (SELECT ID_REPORT FROM PRD.SAVEREPORT WHERE DT_REPORT = @PIN_DT_REPORT AND NM_SHIFT = @PIN_NM_SHIFT)
		UPDATE PlaskoliteQA.PRD.SAVEREPORT SET REPORT = @PIN_REPORT,SAVEREPORT = @PIN_SAVEREPORT WHERE ID_REPORT = @IDREP
		select 'true'
	END
	IF (@EXIST = 0)
	BEGIN
		INSERT INTO PlaskoliteQA.PRD.SAVEREPORT(DT_REPORT,NM_SHIFT,REPORT,SAVEREPORT) VALUES(@PIN_DT_REPORT,@PIN_NM_SHIFT,@PIN_REPORT,@PIN_SAVEREPORT)
		select 'true'
	END

END
