-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 07/06/2018
-- Description: get alL WORK ORDERS PER LINE.
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_ALL_WORK_ORDER_DATA]
		@PIN_ID_WORK_ORDER AS INT = NULL,
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_ID_PRODUCTION_LINE AS int = NULL
AS  

	DECLARE @V_WORK_ORDER_PROGRESS AS NVARCHAR(MAX) = ''
		, @V_INITIAL_MESSAGE_ONE_PALLET AS NVARCHAR(MAX) = ''

	IF @PIN_ID_WORK_ORDER IS NOT NULL BEGIN 
		SET @V_WORK_ORDER_PROGRESS = (SELECT PRD.F_GET_PROGRESS_WORK_ORDER(@PIN_ID_WORK_ORDER))
	END	

	SELECT KWO.NO_WORK_ORDER
		, KWO.ID_WORK_ORDER
		, '' AS KY_USER
		, KWO.KY_CUSTOMER
		, KWO.NM_CUSTOMER
		, CI.ID_ITEM
		, CI.KY_ITEM
		, CI.NM_ITEM
		, CPL.ID_PRODUCTION_LINE
		, CPL.KY_PRODUCTION_LINE
		, CPL.NM_PRODUCTION_LINE
		, KWO.NM_MATERIAL
		, KWO.NM_COLOR
		, (KWO.NO_RUN_QTY + KWO.NO_QTY_ADDED) AS NO_RUN_QTY
		, KWO.NO_LENGHT
		, KWO.NO_WIDTH
		, KWO.NO_THICKNESS
		, (KWO.NO_ASSIGNED_TIME + ISNULL(KWO.NO_STANDARD_TIME,0)) NO_ASSIGNED_TIME
		, CONVERT(VARCHAR(10),KWO.DT_WORK_ORDER,101) DT_WORK_ORDER
		, CONVERT(VARCHAR, KWO.DT_WORK_ORDER, 108) DT_INITIAL_TIME
		, KWO.KY_STATUS
		, @V_WORK_ORDER_PROGRESS AS DS_PROGRESS_WORK_ORDER
		, KWO.NO_ORDER
		, KWO.DT_ORDER
		, CI.KY_UPC
		, (SELECT NM_TRANSITION AS li
			FROM PRD.K_WORK_ORDER_TRANSITIONS WOT
			WHERE WOT.ID_WORK_ORDER = KWO.ID_WORK_ORDER
			FOR XML RAW (''), ROOT ('ul'), ELEMENTS
		) AS XML_TRANSITIONS
	FROM PRD.K_WORK_ORDER KWO
		INNER JOIN PRD.C_ITEM CI 
			ON KWO.ID_ITEM = CI.ID_ITEM
		INNER JOIN PRD.C_PRODUCTION_LINE CPL 
			ON KWO.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
	WHERE (@PIN_ID_WORK_ORDER IS NULL OR(@PIN_ID_WORK_ORDER IS NOT NULL AND KWO.ID_WORK_ORDER = @PIN_ID_WORK_ORDER ))
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR(@PIN_ID_BRANCH_PLANT IS NOT NULL AND KWO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT ))
		AND (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND KWO.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE ))
	ORDER BY KWO.DT_ORDER DESC

