-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 25/05/2018
-- Description: get notifications history per user
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_NOTIFICATIONS_HISTORY]
	  @PIN_ID_NOTIFICATIION AS INT = NULL
	, @PIN_KY_USER AS NVARCHAR(50) = NULL
	, @KY_PROCESS_TYPE AS NVARCHAR(50) = NULL
	, @PIN_KY_STATUS AS NVARCHAR(50) = NULL
	, @PIN_NO_MONTS_AGO AS INT = NULL

AS   
	 SELECT NOTI.ID_NOTIFICATION,
			NOTI.KY_USER,
			NOTI.KY_PROCESS_TYPE,
			NOTI.KY_STATUS,
			NOTI.USER_RECIPENT,
			NOTI.NM_NAME,
			NOTI.NM_TITLE,
			--ISNULL(NOTI.DS_MESSAGE, NOTI.NM_TITLE) DS_MESSAGE,
			CASE WHEN NOTI.DS_MESSAGE IS NULL THEN NOTI.NM_TITLE
				 WHEN NOTI.DS_MESSAGE = '' THEN NOTI.NM_TITLE
				 ELSE NOTI.DS_MESSAGE
			END AS DS_MESSAGE,
			NOTI.XML_PROCESS_CONFIGURATION,
			NOTI.FG_ATTENDED,
			NOTI.KY_ATTENDED
	   FROM(
			SELECT 
				   NS.ID_NOTIFICATION_SENDED AS ID_NOTIFICATION,
				   NS.KY_USER,
				   NS.KY_PROCESS_TYPE,
				   NS.KY_STATUS,
				   NS.FG_ATTENDED,
				   CASE NS.FG_ATTENDED
						WHEN NULL THEN 'Yes'
						WHEN 1 THEN 'Yes'
						WHEN 0 THEN 'No'
					END AS KY_ATTENDED,
				   (SELECT TOP 1 msgs.msg.value('@TO', 'nvarchar(max)') TO_USER FROM NS.XML_PROCESS_CONFIGURATION.nodes('NOTIFICATIONS/RECIPIENTS/child::node()') msgs(msg) WHERE msgs.msg.value('@TO' , 'nvarchar(max)') = @PIN_KY_USER) 
				   AS USER_RECIPENT,
				   (SELECT top 1 msgs.msg.value('@NAME', 'nvarchar(max)') NM_NAME FROM NS.XML_PROCESS_CONFIGURATION.nodes('NOTIFICATIONS/child::node()') msgs(msg) WHERE msgs.msg.value('@NAME', 'nvarchar(max)') IS NOT NULL) 
				   as NM_NAME,
				   (SELECT top 1 msgs.msg.value('@TITLE', 'nvarchar(max)') NM_TITLE FROM NS.XML_PROCESS_CONFIGURATION.nodes('NOTIFICATIONS/child::node()') msgs(msg) WHERE msgs.msg.value('@TITLE', 'nvarchar(max)')  IS NOT NULL ) 
					as NM_TITLE,
					(--SELECT MS. FROM (
							SELECT top 1 msgs.msg.value('@MESSAGE', 'nvarchar(max)')  DS_MSG FROM Ns.XML_PROCESS_CONFIGURATION.nodes('NOTIFICATIONS/child::node()') msgs(msg)  WHERE msgs.msg.value('@MESSAGE', 'nvarchar(max)') IS NOT NULL
						--) MS
					) 
					as DS_MESSAGE,
				   NS.XML_PROCESS_CONFIGURATION
			  FROM PRD.K_NOTIFICATIONS_SENDED NS
			 WHERE CAST(NS.DT_NOTIFICATION AS date) > DATEADD(MONTH, - @PIN_NO_MONTS_AGO , CAST(GETDATE() AS date))
		   )
		   NOTI
		WHERE NOTI.USER_RECIPENT = @PIN_KY_USER
		  AND (@PIN_ID_NOTIFICATIION IS NULL OR (@PIN_ID_NOTIFICATIION IS NOT NULL AND NOTI.ID_NOTIFICATION = @PIN_ID_NOTIFICATIION))
		  AND (@KY_PROCESS_TYPE IS NULL OR (@KY_PROCESS_TYPE IS NOT NULL AND NOTI.KY_PROCESS_TYPE = @KY_PROCESS_TYPE))
		  AND (@PIN_KY_STATUS IS NULL OR (@PIN_KY_STATUS IS NOT NULL AND NOTI.KY_STATUS = @PIN_KY_STATUS))
		ORDER BY 1 DESC

