-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 15/03/2017
-- Description: get all PROBLEM CODES 
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_PROBLEM_CODE] 
	    @PIN_ID_PROBLEM_CODE AS int = NULL,
        @PIN_KY_PROBLEM_CODE AS nvarchar(50) = NULL,
        @PIN_NM_PROBLEM_CODE AS nvarchar(300) = NULL,
        @PIN_FG_ACTIVE AS BIT = NULL,
        @PIN_ID_BRANCH_PLANT AS int = NULL,
        @PIN_KY_CODE_TYPE AS nvarchar(50) = NULL,
        @PIN_ID_PROBLEM_AREA AS int = NULL

AS   
	SELECT 
       PC.[ID_PROBLEM_CODE]
      ,PC.[KY_PROBLEM_CODE]
      ,PC.[NM_PROBLEM_CODE]
      ,PC.[FG_ACTIVE]
      ,PC.[ID_BRANCH_PLANT]
	  ,CT.NM_CODE_TYPE
      ,PC.[ID_PROBLEM_AREA]
      ,PA.[NM_PROBLEM_AREA]
	FROM [PRD].[C_PROBLEM_CODE] PC
	LEFT OUTER JOIN ADM.C_BRANCH_PLANT BP ON PC.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
	LEFT OUTER JOIN PRD.C_PROBLEM_AREA PA ON PC.ID_PROBLEM_AREA = PA.ID_PROBLEM_AREA
	LEFT OUTER JOIN ADM.VW_C_CODE_TYPE CT ON CT.KY_CODE_TYPE = PC.KY_CODE_TYPE
	WHERE (@PIN_ID_PROBLEM_CODE IS NULL OR (@PIN_ID_PROBLEM_CODE IS NOT NULL AND PC.[ID_PROBLEM_CODE] = @PIN_ID_PROBLEM_CODE)) AND 
			(@PIN_KY_PROBLEM_CODE IS NULL OR (@PIN_KY_PROBLEM_CODE IS NOT NULL AND PC.[KY_PROBLEM_CODE] = @PIN_KY_PROBLEM_CODE)) AND 
			(@PIN_NM_PROBLEM_CODE IS NULL OR (@PIN_NM_PROBLEM_CODE IS NOT NULL AND PC.[NM_PROBLEM_CODE] = @PIN_NM_PROBLEM_CODE)) AND 
    		(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND PC.[FG_ACTIVE] = @PIN_FG_ACTIVE)) AND 
			(@PIN_KY_CODE_TYPE IS NULL OR (@PIN_KY_CODE_TYPE IS NOT NULL AND PC.[KY_CODE_TYPE] = @PIN_KY_CODE_TYPE)) AND
			(@PIN_ID_PROBLEM_AREA IS NULL OR (@PIN_ID_PROBLEM_AREA IS NOT NULL AND PC.[ID_PROBLEM_AREA] = @PIN_ID_PROBLEM_AREA)) AND
			(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND (PC.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR PC.ID_BRANCH_PLANT IS NULL)))

