-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Vitek - 2020
-- Author: Daniel Dávalos Romero
-- CREATE date: 15/08/2020
-- Description: Get running work order information for reach skid process
-- =============================================

CREATE PROCEDURE  [PRD].[SPE_GET_RUNNING_WORK_ORDERS_REACH] 
	@PIN_KY_STATUS VARCHAR(50) = NULL,
	@PIN_ID_BRANCH_PLANT INT = NULL
AS
BEGIN
	SELECT 
		WO.NM_PRODUCTION_LINE, 
		WO.ID_WORK_ORDER, 
		IT.KY_ITEM, 
		WO.NM_CUSTOMER, 
		COUNT(PA.KY_STATUS) AS CURRENT_SKID,
		SUM(CASE 
			WHEN PA.KY_STATUS = 'HOLD_ON' THEN 1 
			WHEN PA.KY_STATUS = 'NON_CONFORMANCE' THEN 1 
			WHEN PA.KY_STATUS = 'MRB_RESOLUTION' THEN 1 
			WHEN PA.KY_STATUS = 'BACK_TO_REVIEW' THEN 1 
			ELSE 0 END) AS HOLD_SKIDS,
		SUM(CASE 
			WHEN PA.KY_STATUS = 'ACCEPTED' THEN 1 
			WHEN PA.KY_STATUS = 'SAVE_AS_IS' THEN 1 
			WHEN PA.KY_STATUS = 'NON_INSPECTED' THEN 1 
			WHEN PA.KY_STATUS = 'CUSTOMER_WAIVER' THEN 1 
			ELSE 0 END) AS NO_SAVED_SKIDS,
		CEILING((WO.NO_RUN_QTY + WO.NO_QTY_ADDED) / WO.NO_QTY_SKID) AS TOTAL_SKIDS,
		CEILING((NO_RUN_QTY + NO_QTY_ADDED) / NO_QTY_SKID) - (SUM(CASE 
			WHEN PA.KY_STATUS = 'ACCEPTED' THEN 1 
			WHEN PA.KY_STATUS = 'SAVE_AS_IS' THEN 1 
			WHEN PA.KY_STATUS = 'NON_INSPECTED' THEN 1 
			WHEN PA.KY_STATUS = 'CUSTOMER_WAIVER' THEN 1 
			ELSE 0 END)) AS NO_REMAINING_SKIDS 
	FROM PRD.K_WORK_ORDER WO
	INNER JOIN PRD.C_ITEM IT ON WO.ID_ITEM = IT.ID_ITEM
	INNER JOIN PRD.K_PALLET PA ON PA.ID_WORK_ORDER = WO.ID_WORK_ORDER
	WHERE 
		(@PIN_KY_STATUS IS NULL OR (@PIN_KY_STATUS IS NOT NULL AND WO.KY_STATUS = @PIN_KY_STATUS)) AND
		(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND WO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
	GROUP BY WO.ID_PRODUCTION_LINE, WO.NM_PRODUCTION_LINE, WO.ID_WORK_ORDER, IT.KY_ITEM, WO.NM_CUSTOMER, WO.NO_RUN_QTY, WO.NO_QTY_ADDED, WO.NO_QTY_SKID
	ORDER BY WO.ID_PRODUCTION_LINE ASC

END
