-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 08/05/2018
-- Description: Get variable acquisition type
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_VARIABLE_ACQUISITION_TYPE]
		@PIN_ID_VARIABLE_ACQUISITION_TYPE AS INT = NULL,
		@PIN_KY_VARIABLE_ACQUISITION_TYPE AS NVARCHAR(300) = NULL,
        @PIN_NM_VARIABLE_ACQUISITION_TYPE AS NVARCHAR(50) = NULL

AS   
		  SELECT VSU.ID_VARIABLE_ACQUISITION_TYPE,
				 VSU.KY_VARIABLE_ACQUISITION_TYPE,
				 VSU.NM_VARIABLE_ACQUISITION_TYPE
			FROM ADM.VW_C_VARIABLE_ACQUISITION_TYPE VSU
					
		   WHERE (@PIN_ID_VARIABLE_ACQUISITION_TYPE IS NULL OR (@PIN_ID_VARIABLE_ACQUISITION_TYPE IS NOT NULL AND VSU.ID_VARIABLE_ACQUISITION_TYPE = @PIN_ID_VARIABLE_ACQUISITION_TYPE)) AND 
				 (@PIN_KY_VARIABLE_ACQUISITION_TYPE IS NULL OR (@PIN_KY_VARIABLE_ACQUISITION_TYPE IS NOT NULL AND VSU.KY_VARIABLE_ACQUISITION_TYPE = @PIN_KY_VARIABLE_ACQUISITION_TYPE)) AND 
				 (@PIN_NM_VARIABLE_ACQUISITION_TYPE IS NULL OR (@PIN_NM_VARIABLE_ACQUISITION_TYPE IS NOT NULL AND VSU.NM_VARIABLE_ACQUISITION_TYPE = @PIN_NM_VARIABLE_ACQUISITION_TYPE))

