-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - VITEK - 2019
-- 
-- CREATE date: 10/11/2019
-- Description: Get work orders by production line Order DESC
-- =============================================
-- 12/20/2018 JDR XML_SCHEDULER_COMMENTS and NO_RUN_LBS columns added
-- =============================================
-- valid ID_QA27 adn n_skids 
-- 07/22/2019 DELLC 
-- 03/18/2020 : We fixed show all status. by AA
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_WORK_ORDER_BY_PRODUCTION_LINE_CC] 
	@PIN_ID_PRODUCTION_LINE INT
	,@PIN_KY_STATUS_WORK_ORDER XML

AS
BEGIN
	DECLARE @T_WORK_ORDER_STATUS TABLE (
		KY_WORK_ORDER_STATUS NVARCHAR(20)
	)

	INSERT INTO @T_WORK_ORDER_STATUS (KY_WORK_ORDER_STATUS)
	SELECT x.ref.value('@KY_STATUS', 'VARCHAR(20)') KY_STATUS_WORK_ORDER 
	FROM @PIN_KY_STATUS_WORK_ORDER.nodes('/STATUS/ST') x(ref)
	
	DECLARE @T_WORK_ORDER TABLE (
		ID_BRANCH_PLANT INT
		, ID_QA27 INT
		, ID_WORK_ORDER INT
		, ID_ITEM INT
		, KY_ITEM NVARCHAR(50)
		, NM_CUSTOMER NVARCHAR(200)
		, NO_RUN_QTY INT
		, DT_WORK_ORDER DATETIME
		, DT_CLOSE_WORK_ORDER DATETIME
		, NO_SKIDS NVARCHAR(20)
		, NO_QTY_ADDED NVARCHAR(20)
		, NO_QTY_SKID NVARCHAR(20)
		, KY_WORK_ORDER_STATUS NVARCHAR(50)
		, NM_MATERIAL NVARCHAR(200)
		, NM_COLOR NVARCHAR(100)
		, NO_LENGTH DECIMAL(13,4)
		, NO_WIDTH DECIMAL(13,4)
		, NO_THICKNESS DECIMAL(13,4)
		, NO_SEQUENCE INT
		, XML_TRANSITIONS XML
		, XML_SCHEDULER_COMMENTS XML
		, NO_ASSIGNED_TIME INT
		, KY_USER NVARCHAR(50)
		, NO_RUN_LBS DECIMAL(13,4)
		, SKIDS_ON_HOLD INT--ADDED
	)

	INSERT INTO @T_WORK_ORDER (
		ID_BRANCH_PLANT
		, ID_QA27
		, ID_WORK_ORDER
		, ID_ITEM
		, KY_ITEM
		, NM_CUSTOMER
		, NO_RUN_QTY
		, DT_WORK_ORDER
		, DT_CLOSE_WORK_ORDER
		, NO_SKIDS
		, NO_QTY_ADDED
		, NO_QTY_SKID
		, KY_WORK_ORDER_STATUS
		, NM_MATERIAL
		, NM_COLOR
		, NO_SEQUENCE
		, XML_TRANSITIONS
		, XML_SCHEDULER_COMMENTS
		, NO_ASSIGNED_TIME
		, KY_USER
		, NO_RUN_LBS
		, SKIDS_ON_HOLD
	)

	SELECT KWO.ID_BRANCH_PLANT
		, (SELECT TOP 1 QA.ID_QA27 FROM PRD.K_QA27 QA WHERE  QA.ID_WORK_ORDER = KWO.ID_WORK_ORDER  ORDER BY QA.ID_QA27 DESC) AS  ID_QA27
		, KWO.ID_WORK_ORDER
		, CI.ID_ITEM
		, CI.KY_ITEM
		, KWO.NM_CUSTOMER
		, KWO.NO_RUN_QTY + KWO.NO_QTY_ADDED AS NO_RUN_QTY
		, KWO.DT_WORK_ORDER
		, KWO.DT_CLOSE_WORK_ORDER
		-- quit flag
		, (SELECT TOP 1 NO_PALLET  FROM PRD.K_PALLET KP WHERE KP.ID_WORK_ORDER = KWO.ID_WORK_ORDER ORDER BY ID_PALLET DESC) AS NO_SKIDS
		, KWO.NO_QTY_ADDED
		, KWO.NO_QTY_SKID
		, KWO.KY_STATUS
		, KWO.NM_MATERIAL
		, KWO.NM_COLOR
		, KWO.NO_ORDER
		, (SELECT NM_TRANSITION AS li
			FROM PRD.K_WORK_ORDER_TRANSITIONS WOT
			WHERE WOT.ID_WORK_ORDER = KWO.ID_WORK_ORDER
			FOR XML RAW (''), ROOT ('ul'), ELEMENTS
		) AS XML_TRANSITIONS
		, (SELECT DS_COMMENT AS li
			FROM PRD.K_WORK_ORDER_COMMENT KWOC
			WHERE KWOC.ID_WORK_ORDER = KWO.ID_WORK_ORDER
				AND KWOC.KY_TYPE_COMMENT = 'SCHEDULER'
				AND KWOC.FG_ACTIVE = 1
			FOR XML RAW (''), ROOT ('ul'), ELEMENTS
		) AS XML_SCHEDULER_COMMENTS
		, KWO.NO_ASSIGNED_TIME
		, CU.KY_USER
		, ISNULL(CONVERT(DECIMAL(13,2), NULLIF(CIC.XML_FIELD_SETTINGS.value('(/SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 
		         'NVARCHAR(100)'), '')), CI.NO_POUNDS_PER_ITEM) * (NO_RUN_QTY + NO_QTY_ADDED)
		, COALESCE((SELECT COUNT(*) FROM PRD.K_INSPECTION_SKID KIS
		INNER JOIN PRD.K_PALLET KP ON KP.ID_WORK_ORDER = KIS.ID_WORK_ORDER AND KP.NO_PALLET = KIS.NO_PALLET
		WHERE KIS.ID_WORK_ORDER = KWO.ID_WORK_ORDER 
		 AND KP.KY_STATUS IN ('HOLD_ON','BACK_TO_REVIEW')),0) AS SKIDS_ON_HOLD
	FROM PRD.K_WORK_ORDER KWO 
		INNER JOIN PRD.C_ITEM CI
			ON KWO.ID_ITEM = CI.ID_ITEM
		INNER JOIN ADM.C_BRANCH_PLANT CBP
			ON KWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT
		LEFT JOIN PRD.C_ITEM_CHARACTERISTIC CIC
			ON CIC.ID_ITEM = CI.ID_ITEM
			AND CIC.ID_METRICS = CBP.ID_WEIGHT_METRIC
		INNER JOIN PRD.K_QA27 KQ
			ON KQ.ID_QA27 = (SELECT TOP 1 ID_QA27
         FROM   PRD.K_QA27
         WHERE   ID_WORK_ORDER = KWO.ID_WORK_ORDER)
			---edited
			---  KQ.ID_WORK_ORDER = KWO.ID_WORK_ORDER
			 --AND KWO.KY_STATUS= KQ.KY_STATUS
		LEFT JOIN ADM.C_USER CU
			ON KQ.ID_LEADMAN = CU.ID_EMPLOYEE
			AND CU.FG_ACTIVE = 1
	WHERE KWO.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE
	AND EXISTS (SELECT TOP 1 1 FROM @T_WORK_ORDER_STATUS TWOS WHERE TWOS.KY_WORK_ORDER_STATUS = KWO.KY_STATUS ORDER BY KWO.DT_CLOSE_WORK_ORDER DESC)
	 --ORDER BY KWO.DT_CLOSE_WORK_ORDER DESC
	

	UPDATE TWO
	SET NO_LENGTH = XML_FIELD_SETTINGS.value('(/SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'DECIMAL(13,4)')
	FROM @T_WORK_ORDER TWO
		INNER JOIN ADM.C_BRANCH_PLANT CBP
			ON TWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT
		INNER JOIN PRD.C_ITEM_CHARACTERISTIC CIC
			ON TWO.ID_ITEM = CIC.ID_ITEM
			AND CIC.ID_METRICS = CBP.ID_LENGTH_METRIC

	UPDATE TWO
	SET NO_WIDTH = XML_FIELD_SETTINGS.value('(/SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'DECIMAL(13,4)')
	FROM @T_WORK_ORDER TWO
		INNER JOIN ADM.C_BRANCH_PLANT CBP
			ON TWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT
		INNER JOIN PRD.C_ITEM_CHARACTERISTIC CIC
			ON TWO.ID_ITEM = CIC.ID_ITEM
			AND CIC.ID_METRICS = CBP.ID_WIDTH_METRIC

	UPDATE TWO
	SET NO_THICKNESS = XML_FIELD_SETTINGS.value('(/SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'DECIMAL(13,4)')
	FROM @T_WORK_ORDER TWO
		INNER JOIN ADM.C_BRANCH_PLANT CBP
			ON TWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT
		INNER JOIN PRD.C_ITEM_CHARACTERISTIC CIC
			ON TWO.ID_ITEM = CIC.ID_ITEM
			AND CIC.ID_METRICS = CBP.ID_THICKNESS_METRIC

	SELECT  ID_BRANCH_PLANT
		, ID_QA27
		, ID_WORK_ORDER
		, ID_ITEM
		, KY_ITEM
		, NM_CUSTOMER
		, NO_RUN_QTY
		, DT_WORK_ORDER
		--, DT_CLOSE_WORK_ORDER
		, NO_SKIDS
		, KY_WORK_ORDER_STATUS
		, NM_MATERIAL
		, NM_COLOR
		, NO_LENGTH
		, NO_WIDTH
		, NO_THICKNESS
		, NO_SEQUENCE
		, XML_TRANSITIONS
		, XML_SCHEDULER_COMMENTS
		, NO_ASSIGNED_TIME
		, KY_USER
		, NO_RUN_LBS
		, CEILING((NO_RUN_QTY + NO_QTY_ADDED) / NO_QTY_SKID) AS NO_TOTAL_SKIDS
		, SKIDS_ON_HOLD
	FROM @T_WORK_ORDER TWO
	ORDER BY TWO.DT_WORK_ORDER DESC

END

