-- =============================================
-- Author:		DELLC
-- Create date: 05/01/2020
-- Description:	UPDATE LEADMAN IN THE SAME ESHIFT 
-- =============================================
CREATE PROCEDURE   [PRD].[SPE_UPDATE_LEADMAN_QA27] 
	@XML_RESULT XML = '' OUT,
	@KY_USER VARCHAR(30),
	@ID_QA27 INT
AS
BEGIN
	DECLARE
	@V_EXIST_TRAN BIT = 0,
	@NM_USER VARCHAR(50),
	@ID_EMPLOYEE INT
	BEGIN TRY
	IF (@@TRANCOUNT = 0) BEGIN
				--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			SET @V_EXIST_TRAN = 1
	END
	
	SELECT @NM_USER=U.NM_USER, @ID_EMPLOYEE = E.ID_EMPLOYEE FROM ADM.C_USER U INNER JOIN ADM.C_EMPLOYEE E 
	ON  U.ID_EMPLOYEE = E.ID_EMPLOYEE WHERE U.KY_USER= @KY_USER


	UPDATE PRD.K_QA27 SET NM_LEADMAN = @NM_USER, ID_LEADMAN= @ID_EMPLOYEE, KY_USER_APP_UPDATE = @KY_USER WHERE ID_QA27= @ID_QA27

	UPDATE PRD.K_SHIFT SET KY_USER = @KY_USER WHERE ID_SHIFT = (SELECT ID_SHIFT FROM  PRD.K_QA27  WHERE ID_QA27 = @ID_QA27)

		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
			SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 0, 'SUCCESSFUL')
			SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
			SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')		
	
	IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY

	BEGIN CATCH
	IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES(ERROR_NUMBER(), ERROR_MESSAGE())
	END CATCH 
	
END
