

CREATE PROCEDURE    [PRD].[SPE_GET_WEIGHT_SKIDS]
 @SKIDS AS VARCHAR(2000)
AS
BEGIN

DECLARE @SQLQ NVARCHAR(1000)
SET @SQLQ = 'SELECT  DISTINCT  KP.NO_PALLET, kF.ID_PALLET, KP.NO_QUANTITY,  KMR.NO_VALUE  FROM PRD.K_READINGS KR
INNER JOIN
        ( SELECT  DISTINCT  *   FROM   PRD.K_METRICS_READINGS WHERE ID_METRICS=36  
        ) KMR ON
KR.ID_K_READING= KMR.ID_K_READING 
 INNER JOIN PRD.K_FORM KF ON 
 KF.ID_INSPECTION_SKID = KR.ID_INSPECTION_SKID OR KF.ID_K_FORM = KR.ID_K_FORM
 INNER JOIN PRD.K_PALLET KP ON 
 KF.ID_PALLET = KP.ID_PALLET 
 WHERE ( KR.ID_K_FORM IS NOT NULL OR  KR.ID_INSPECTION_SKID IS NOT NULL) ';
DECLARE @Description AS nvarchar(20)
DECLARE ProdInfo CURSOR FOR SELECT * FROM dbo.splitstring(@SKIDS)
OPEN ProdInfo
	FETCH NEXT FROM ProdInfo INTO @Description
	SET @SQLQ += 'AND( KF.ID_PALLET = '+ @Description 
WHILE @@fetch_status = 0
BEGIN
   
	SET @SQLQ += ' OR KF.ID_PALLET = '+ @Description
    FETCH NEXT FROM ProdInfo INTO @Description
END

CLOSE ProdInfo
SET @SQLQ += ')'
 PRINT @SQLQ
DEALLOCATE ProdInfo

Execute SP_ExecuteSQL  @SQLQ
END

