CREATE PROCEDURE    [PRD].[SPE_GET_MEMBER_LIST]
	@PIN_ID_DISTRIBUTION_LIST AS INT = NULL,
	@PIN_ID_BRANCH_PLANT AS INT = NULL
AS
BEGIN
	SELECT 
		KDL.ID_DISTRIBUTION_LIST,
		KMDL.ID_MEMBER,
		KMDL.FG_ACTIVE,
		CU.KY_USER,
		CU.NM_USER,
		CU.KY_EMAIL
	FROM K_DISTRIBUTION_LIST KDL INNER JOIN K_MEMBER_IN_LIST_DISTRIBUTION KMDL
	ON KDL.ID_DISTRIBUTION_LIST = KMDL.ID_DISTRIBUTION
	INNER JOIN ADM.C_USER CU ON KMDL.KY_USER = CU.KY_USER 
	WHERE KMDL.ID_DISTRIBUTION = @PIN_ID_DISTRIBUTION_LIST 
	AND KMDL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT

END

