-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Tavares
-- CREATE date: 23/05/2017
-- Description: Unused production lines.
-- =============================================
-- 18/08/2017 JDR Change subquery to use CTE
-- 18/08/2017 JDR FG_EMPLOYEE_AUTHORIZED and KY_EMPLOYEE_AUTHORIZED columns added
-- 26/05/2018 JDR Join with C_PRODUCTION_LINE_ID to get the P.L. releated with machine ip
-- 18/05/2019  disable valid shift is null and kyUser to response  dellc 
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_UNUSED_PRODUCTION_LINE]
	    @PIN_ID_PRODUCTION_LINE AS int = NULL,
		@PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_FG_ACTIVE AS BIT = NULL,
		@PIN_ID_EMPLOYEE AS INT = NULL,
		@PIN_NO_IP AS NVARCHAR(40) = NULL,
		@PIN_NM_HOST AS NVARCHAR(100) = NULL
AS   

	--; WITH T_SHIFT AS (
	--	SELECT *
	--	FROM  PRD.K_SHIFT KS
	--	WHERE GETDATE() BETWEEN KS.DT_START_SHIFT AND KS.DT_END_SHIFT
	--		AND KS.FG_STATUS = 1
	--		AND KS.KY_USER IS NOT NULL
	--), T_PRODUCTION_LINE_AUTHORIZED AS (
	--	SELECT ID_PRODUCTION_LINE
	--	FROM PRD.C_PRODUCTION_LINE_OPERATOR
	--	WHERE ID_EMPLOYEE = @PIN_ID_EMPLOYEE
	--)

	SELECT CPL.ID_PRODUCTION_LINE,
		CPL.KY_PRODUCTION_LINE,
		CPL.NM_PRODUCTION_LINE,
		CPL.DS_PRODUCTION_LINE,
		CPL.FG_ACTIVE,
		TPLA.ID_SHIFT,
		TPLA.KY_SHIFT,
		TPLA.DT_SHIFT_HISTORY,
		TPLA.KY_USER,
		CASE WHEN TPLA.ID_PRODUCTION_LINE IS NOT NULL THEN 1 ELSE 0 END AS FG_EMPLOYEE_AUTHORIZED,
		CASE WHEN TPLA.ID_PRODUCTION_LINE IS NOT NULL THEN 'Yes' ELSE 'No' END AS KY_EMPLOYEE_AUTHORIZED
	FROM PRD.C_PRODUCTION_LINE CPL
		INNER JOIN PRD.C_PRODUCTION_LINE_IP CPLI ON CPL.ID_PRODUCTION_LINE = CPLI.ID_PRODUCTION_LINE
		--LEFT JOIN T_SHIFT TS 
		--	ON CPL.ID_PRODUCTION_LINE = TS.ID_PRODUCTION_LINE
		INNER JOIN PRD.K_SHIFT TPLA
			ON CPL.ID_PRODUCTION_LINE = TPLA.ID_PRODUCTION_LINE				
	WHERE 
	--TS.ID_SHIFT IS NULL AND
	   TPLA.FG_STATUS = @PIN_FG_ACTIVE 
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CPL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT)) 
		AND (@PIN_NO_IP IS NULL OR (@PIN_NO_IP IS NOT NULL AND (CPLI.NO_IP = @PIN_NO_IP OR CPLI.NO_IP = @PIN_NM_HOST)))
	ORDER BY CPL.KY_PRODUCTION_LINE

