-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez Torres
-- CREATE date: 29/05/2018
-- Description: Get the skipped wor orders
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_SKIPPED_WORK_ORDER] 
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_ID_PRODUCTION_LINE AS int = NULL,
		@PIN_ID_LEADMAN AS INT = NULL,
		@PIN_ID_WORK_ORDER AS INT = NULL,
		@PIN_ID_QA27 AS INT = NULL

AS  


	SELECT KWO.NO_WORK_ORDER
		, KWO.ID_WORK_ORDER
		, 0 AS ID_QA27
		, 'N/A' AS KY_USER
		, KWO.KY_CUSTOMER
		, KWO.NM_CUSTOMER
		, CI.ID_ITEM
		, CI.KY_ITEM
		, CI.NM_ITEM
		, CPL.ID_PRODUCTION_LINE
		, CPL.KY_PRODUCTION_LINE
		, CPL.NM_PRODUCTION_LINE
		, KWO.NM_MATERIAL
		, KWO.NM_COLOR
		, (KWO.NO_RUN_QTY + KWO.NO_QTY_ADDED) AS NO_RUN_QTY
		, KWO.NO_LENGHT
		, KWO.NO_WIDTH
		, KWO.NO_THICKNESS
		, (KWO.NO_ASSIGNED_TIME + ISNULL(KWO.NO_STANDARD_TIME,0)) NO_ASSIGNED_TIME
		, CONVERT(VARCHAR(10),KWO.DT_WORK_ORDER,101) DT_WORK_ORDER
		, CONVERT(VARCHAR, KWO.DT_WORK_ORDER, 108) DT_INITIAL_TIME
		, KWO.KY_STATUS
		, 0 AS ID_PALLET
		, 0 AS NO_PALLET
		, '' AS KY_STATUS_PALLET
		, KI.DS_EXPLANATION_EVENT_CLOSED
		, KI.DT_ISSUE_CLOSED
		, CPC.NM_PROBLEM_CODE
	FROM PRD.K_WORK_ORDER KWO
		INNER JOIN PRD.C_ITEM CI  ON KWO.ID_ITEM = CI.ID_ITEM
		INNER JOIN PRD.C_PRODUCTION_LINE CPL ON KWO.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
		--LEFT JOIN PRD.K_QA27 KQA ON KWO.ID_WORK_ORDER = KQA.ID_WORK_ORDER  --AND KQA.KY_STATUS = @PIN_KY_STATUS_QA27
		--LEFT JOIN ADM.C_USER CU ON KQA.ID_LEADMAN = CU.ID_EMPLOYEE
		LEFT JOIN PRD.K_ISSUE KI  ON KI.ID_WORK_ORDER = KWO.ID_WORK_ORDER AND KI.ID_ISSUE = KWO.ID_ISSUE_CAUSE_SKIPPED
		LEFT JOIN PRD.C_PROBLEM_CODE CPC ON KI.ID_PROBLEM_CODE = CPC.ID_PROBLEM_CODE
	WHERE  KWO.KY_STATUS = 'SKIPPED' --AND KQA.KY_STATUS = 'SKIPPED'
		AND (@PIN_ID_WORK_ORDER IS NULL OR(@PIN_ID_WORK_ORDER IS NOT NULL AND KWO.ID_WORK_ORDER = @PIN_ID_WORK_ORDER ))
		--AND (@PIN_ID_QA27 IS NULL OR(@PIN_ID_QA27 IS NOT NULL AND KQA.ID_QA27 = @PIN_ID_QA27 ))
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR(@PIN_ID_BRANCH_PLANT IS NOT NULL AND KWO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT ))
		AND (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND KWO.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE ))
		--AND (@PIN_KY_STATUS_QA27 IS NULL OR (@PIN_KY_STATUS_QA27 IS NOT NULL AND KQA.KY_STATUS = @PIN_KY_STATUS_QA27 ))
		--AND (@PIN_ID_LEADMAN IS NULL OR (@PIN_ID_LEADMAN IS NOT NULL AND KQA.ID_LEADMAN = @PIN_ID_LEADMAN ))
	ORDER BY KWO.KY_STATUS, KWO.ID_WORK_ORDER

