-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez 
-- CREATE date: 06/07/2017
-- Description: get all transitions by work order
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_WORK_ORDER_TRANSITIONS] 
	    @PIN_ID_WORK_ORDER_TRANSITION INT = NULL,
	    @PIN_ID_WORK_ORDER INT = NULL,
	    @PIN_ID_TRANSITION INT = NULL

AS   

	SELECT 
	   WOT.ID_WORK_ORDER_TRANSITION
      ,WOT.ID_WORK_ORDER
      ,WOT.ID_TRANSITION
      ,WOT.KY_TRANSITION
      ,WOT.NM_TRANSITION
      ,WOT.NO_STANDARD_TIME

	FROM [PRD].[K_WORK_ORDER_TRANSITIONS] WOT
		INNER JOIN PRD.K_WORK_ORDER WO ON WO.ID_WORK_ORDER = WOT.ID_WORK_ORDER
		INNER JOIN PRD.C_TRANSITION T ON T.ID_TRANSITION = WOT.ID_TRANSITION
	WHERE
		(@PIN_ID_WORK_ORDER_TRANSITION IS NULL OR (@PIN_ID_WORK_ORDER_TRANSITION IS NOT NULL AND WOT.[ID_WORK_ORDER_TRANSITION] = @PIN_ID_WORK_ORDER_TRANSITION)) AND 
		(@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND WOT.ID_WORK_ORDER = @PIN_ID_WORK_ORDER)) AND
		(@PIN_ID_TRANSITION IS NULL OR (@PIN_ID_TRANSITION IS NOT NULL AND WOT.ID_TRANSITION = @PIN_ID_TRANSITION))

