-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 01/30/2019
-- Description: Get users for work order notification
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_USERS_FOR_WORK_ORDER_NOTIFICATION] 
	@PIN_ID_WORK_ORDER INT
AS

DECLARE @ID_BRANCH_PLANT INT = (SELECT TOP 1 ID_BRANCH_PLANT FROM PRD.K_WORK_ORDER WHERE ID_WORK_ORDER = @PIN_ID_WORK_ORDER)

DECLARE @ID_SCHEDULER_POSITION INT = (SELECT TOP 1 XML_CONFIGURATION.value('(/CONFIGURATIONS/ESPECIFIC_CONFIGURATION/BRANCH_PLANT[@ID_BRANCH_PLANT=sql:variable("@ID_BRANCH_PLANT")]/QUALITY_PROCESS/SCHEDULER/@ID_POSITION)[1]', 'INT') FROM ADM.S_CONFIGURATION)


SELECT CU.KY_USER
	, CU.KY_EMAIL
FROM ADM.C_EMPLOYEE CE 
	INNER JOIN ADM.C_USER CU
		ON CE.ID_EMPLOYEE = CU.ID_EMPLOYEE
		AND CE.FG_ACTIVE = 1
WHERE CE.ID_POSITION = @ID_SCHEDULER_POSITION

