-- ================================================================
-- Proyecto: Plaskolite v2
-- Copyright (c) - Vitek - 2019
-- Author: Aideé Alvarez
-- CREATE date: 12/17/2019
-- Description: GET SCHEDULED WORK ORDERS AND THEIR TRANSITIONS.
-- =================================================================
CREATE PROCEDURE   [PRD].[SPE_GET_SCHEDULED_WO] 
	 @BP INT
	AS
BEGIN
		SELECT KWO.ID_WORK_ORDER, NO_ASSIGNED_TIME, CPL.ID_PRODUCTION_LINE,WOT.NM_TRANSITION,
		WOT.NO_STANDARD_TIME, KWO.NO_ORDER, KWO.NO_TRANSITIONS_TIME 
		FROM PRD.K_WORK_ORDER AS KWO
		INNER JOIN PRD.C_PRODUCTION_LINE AS CPL ON
		CPL.ID_PRODUCTION_LINE = KWO.ID_PRODUCTION_LINE
		LEFT JOIN PRD.K_WORK_ORDER_TRANSITIONS AS WOT ON
		WOT.ID_WORK_ORDER = KWO.ID_WORK_ORDER
		WHERE KY_STATUS = 'SCHEDULED' AND KWO.ID_BRANCH_PLANT = @BP
		ORDER BY DT_WORK_ORDER, NO_ORDER
END
