-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 02/07/2019
-- Description: Get work orders for Scheduler's Screen
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_WORK_ORDERS_FOR_SCHEDULERS] 
AS  
BEGIN
	SELECT KWO.ID_WORK_ORDER
		, KWO.ID_PRODUCTION_LINE
		, KWO.KY_STATUS
		, KWO.NO_WORK_ORDER
		, KWO.KY_CUSTOMER
		, CI.KY_ITEM
		, CI.NM_ITEM
		, CPL.KY_PRODUCTION_LINE
		, KWO.DT_WORK_ORDER
		, KWO.NO_RUN_QTY
		, KWO.NO_BOX_QTY
		, KWO.NM_MATERIAL
		, KWO.NM_COLOR
		, KWO.NO_LENGHT
		, KWO.NO_WIDTH
		, KWO.NO_THICKNESS
		, VCWOS.NM_WORK_ORDER_STATUS
	FROM PRD.K_WORK_ORDER KWO
		INNER JOIN PRD.C_ITEM CI
			ON CI.ID_ITEM = KWO.ID_ITEM
		INNER JOIN PRD.C_PRODUCTION_LINE CPL
			ON KWO.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
		INNER JOIN ADM.VW_C_WORK_ORDER_STATUS VCWOS
			ON KY_STATUS = VCWOS.KY_WORK_ORDER_STATUS
	WHERE KWO.KY_STATUS IN ('SCHEDULED', 'RUNNING') 
END

