CREATE PROCEDURE  [PRD].[SPE_GET_SWITCH_REPORT]
	@PIN_NM_REPORT AS varchar(100) = NULL,
	@PIN_KY_BRANCH_PLANT as varchar(100) = null
AS
BEGIN

	--DECLARE @PIN_ID_DEVICE AS INT = NULL
	SELECT 
		SR.ID_REPORT,
		SR.NM_REPORT,
		SR.FG_SWITCH,
		SR.KY_BRANCH_PLANT
	FROM PRD.C_SWITCH_REPORT SR
	WHERE
	(@PIN_NM_REPORT IS NULL OR (@PIN_NM_REPORT IS NOT NULL AND SR.NM_REPORT = @PIN_NM_REPORT))
	AND (@PIN_KY_BRANCH_PLANT IS NULL OR (@PIN_KY_BRANCH_PLANT IS NOT NULL AND SR.KY_BRANCH_PLANT = @PIN_KY_BRANCH_PLANT))

END