-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 07/04/2017
-- Description: get all pallets
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_PALLET]
	@PIN_ID_PALLET AS INT = NULL
	, @PIN_ID_QA27 AS INT = NULL
	, @PIN_ID_WORK_ORDER AS INT = NULL
	, @PIN_KY_STATUS AS NVARCHAR(50) = NULL
	, @PIN_ID_BRANCH_PLANT AS INT = NULL

AS   

DECLARE @ID_BRANCH_PLANT NVARCHAR(5)

SET @ID_BRANCH_PLANT = CASE WHEN @PIN_ID_BRANCH_PLANT IS NULL THEN 'ALL' ELSE CAST(@PIN_ID_BRANCH_PLANT AS nvarchar) END

--******* GET POSITION OF LEADMEN FROM CONFIGURATION ********		
	DECLARE @XML_CONFIGURATION XML 
		, @XML_BRANCH_PLANT_SELECTED XML
		, @V_NO_LENGTH_SAMPLE_QUALITY_FORM AS INT
		, @V_NM_SAMPLE_UNIT_QUALITY_FORM AS NVARCHAR(20)
		, @V_KY_SAMPLE_UNIT_QUALITY_FORM AS NVARCHAR(20)

		 
	SELECT TOP 1 @V_NO_LENGTH_SAMPLE_QUALITY_FORM = CF.NO_SAMPLE
		, @V_NM_SAMPLE_UNIT_QUALITY_FORM = VUS.NM_SAMPLE_UNIT
		, @V_KY_SAMPLE_UNIT_QUALITY_FORM = VUS.KY_SAMPLE_UNIT
	FROM PRD.C_FORM CF
		INNER JOIN ADM.VW_C_SAMPLE_UNIT VUS 
			ON CF.KY_SAMPLE_UNIT = VUS.KY_SAMPLE_UNIT
	WHERE CF.KY_PROCESS = 'QUALITY'
			

	SELECT @XML_CONFIGURATION = XML_CONFIGURATION 
	FROM ADM.S_CONFIGURATION

	SELECT @XML_BRANCH_PLANT_SELECTED = msgs.msg.query('.')
	FROM @XML_CONFIGURATION.nodes('CONFIGURATIONS/ESPECIFIC_CONFIGURATION/child::node()') msgs(msg)	
	WHERE msgs.msg.value('@ID_BRANCH_PLANT', 'nvarchar(max)') = @ID_BRANCH_PLANT

	  --******* GET METRICS OF CONFIGURATION *******
	;WITH TB_METRICS_CONFIGUTATION AS (
		SELECT msgs.msg.value('@ID_METRICS', 'nvarchar(max)') ID_METRICS
			, msgs.msg.value('local-name(.)', 'nvarchar(max)') NM_METRICS_CONFIGURATION
		FROM @XML_BRANCH_PLANT_SELECTED.nodes('BRANCH_PLANT/PROCESS_METRICS/child::node()') msgs(msg)
	)

	SELECT KP.ID_PALLET	
		, KP.ID_QA27
		, QA.KY_SHIFT AS QA27_KY_SHIFT
		, QA.KY_STATUS AS QA27_KY_STATUS
		, QA.ID_LEADMAN AS QA27_ID_LEADMAN
		, QA.NM_LEADMAN AS QA27_NM_LEADMAN
		, QA.ID_FOREMAN AS QA27_ID_FOREMAN
		, QA.NM_FOREMAN AS QA27_NM_FOREMAN
		, KP.ID_WORK_ORDER
		, WO.KY_CUSTOMER
		, WO.NM_CUSTOMER
		, WO.ID_ITEM
		, CI.KY_ITEM
		, WO.NM_ITEM
		, CI.DS_ITEM
		, CI.NO_PIECES_PER_PALLET
		, CASE WHEN CUSTOMER.KY_CUSTOMER IS NOT NULL THEN 
			CASE WHEN CUSTOMER.KY_SAMPLE_UNIT_CUSTOMER = 'PENCENT' THEN
										CAST(CEILING(CAST((ISNULL(KP.NO_QUANTITY,CI.NO_PIECES_PER_PALLET) * CUSTOMER.NO_LENGTH_SAMPLE_CUSTOMER) AS decimal(12,2))/100) AS INT)
			ELSE
				CUSTOMER.NO_LENGTH_SAMPLE_CUSTOMER
			END
		ELSE
			CASE WHEN ISNULL(@V_KY_SAMPLE_UNIT_QUALITY_FORM, 'PIECES') = 'PENCENT' THEN
				CAST(CEILING(CAST((ISNULL(KP.NO_QUANTITY,CI.NO_PIECES_PER_PALLET) * ISNULL(@V_NO_LENGTH_SAMPLE_QUALITY_FORM,0) ) AS decimal(12,2))/100) AS INT)
			ELSE
				ISNULL(@V_NO_LENGTH_SAMPLE_QUALITY_FORM,0)
			END
	    END AS NO_SAMPLE 
		, CASE WHEN CUSTOMER.KY_CUSTOMER IS NOT NULL THEN
			CUSTOMER.KY_SAMPLE_UNIT_CUSTOMER
		ELSE
			ISNULL(@V_KY_SAMPLE_UNIT_QUALITY_FORM, 'PIECES')
		END AS KY_SAMPLE_UNIT
		, CASE WHEN CUSTOMER.KY_CUSTOMER IS NOT NULL THEN 
			CUSTOMER.NM_SAMPLE_UNIT_CUSTOMER
		ELSE
			ISNULL(@V_NM_SAMPLE_UNIT_QUALITY_FORM, 'Pcs')
		END AS NM_SAMPLE_UNIT  --, VSU.NM_SAMPLE_UNIT
		, CASE WHEN CUSTOMER.KY_CUSTOMER IS NOT NULL THEN 
			CUSTOMER.NO_LENGTH_SAMPLE_CUSTOMER
		ELSE 
			@V_NO_LENGTH_SAMPLE_QUALITY_FORM
		END AS NO_LENGHT_SAMPLE
		, WO.ID_PRODUCTION_LINE
		, WO.NM_PRODUCTION_LINE
		, WO.NO_WORK_ORDER
		, WO.NO_ASSIGNED_TIME
		, WO.NO_BOX_QTY
		, WO.KY_STATUS AS KY_STATUS_WORK_ORDER
		, KP.NO_PALLET
		, KP.NO_QUANTITY
		, KP.DT_INITIAL_TIME
		, KP.DT_FINAL_TIME
		, KP.KY_STATUS
		, CPS.NM_PALLET_STATUS
		, KP.KY_USER_INSPECTOR
		, KP.ID_QUALITY_INSPECTOR_AGREEMENT
		, KP.NM_QUALITY_INSPECTOR_AGREEMENT
		, KP.FG_INSPECTOR_AGREEMENT
		, KP.DT_INSPECTOR_AGREEMENT
		, KP.DS_EXPLANATION_AGREEMENT
		, KP.KY_USER_LEADMAN
		, KP.ID_LEADMAN
		, KP.NM_LEADMAN
		, KP.FG_LEADMAN
		, KP.DT_LEADMAN
		, KP.KY_FIRST_LEVEL_USER
		, KP.ID_FIRST_LEVEL_EMPLOYEE
		, KP.NM_FIRST_LEVEL_EMPLOYEE
		, KP.FG_FIRST_LEVEL_EMPLOYEE
		, KP.DT_FIRST_LEVEL_EMPLOYEE
		, KP.KY_SECOND_LEVEL_USER_REJECTION
		, KP.ID_SECOND_LEVEL_EMPLOYEE_REJECTION
		, KP.NM_SECOND_LEVEL_EMPLOYEE_REJECTION
		, KP.FG_SECOND_LEVEL_EMPLOYEE_REJECTION
		, KP.DT_SECOND_LEVEL_EMPLOYEE_REJECTION
		, KP.KY_THIRD_LEVEL_USER_REJECTION
		, KP.ID_THIRD_LEVEL_EMPLOYEE_REJECTION
		, KP.NM_THIRD_LEVEL_EMPLOYEE_REJECTION
		, KP.FG_THIRD_LEVEL_EMPLOYEE_REJECTION
		, KP.DT_THIRD_LEVEL_EMPLOYEE_REJECTION
		, NULL AS XML_EVIDENCE--PRD.F_GET_PALLET_EVIDENCE_COMMENT(@PIN_ID_PALLET) AS XML_EVIDENCE
		, PRD.F_GET_USERS_BY_POSITION(KP.ID_FIRST_LEVEL_EMPLOYEE, KP.ID_SECOND_LEVEL_EMPLOYEE_REJECTION, KP.ID_THIRD_LEVEL_EMPLOYEE_REJECTION) AS XML_USERS
		, WO.ID_BRANCH_PLANT
		, KP.FG_SEND_FORM
	FROM PRD.K_PALLET KP
		LEFT OUTER JOIN PRD.K_WORK_ORDER 
			WO ON WO.ID_WORK_ORDER = KP.ID_WORK_ORDER
		LEFT OUTER JOIN PRD.K_QA27 QA 
			ON QA.ID_QA27 = KP.ID_QA27
		LEFT OUTER JOIN PRD.C_ITEM CI 
			ON CI.ID_ITEM = WO.ID_ITEM
		LEFT OUTER JOIN ADM.VW_C_PALLET_STATUS CPS 
			ON CPS.KY_PALLET_STATUS = KP.KY_STATUS
		LEFT JOIN ADM.VW_C_SAMPLE_UNIT VSU 
			ON CI.KY_SAMPLE_UNIT = VSU.KY_SAMPLE_UNIT
		LEFT JOIN (SELECT 
							   CS.KY_CUSTOMER,
							   CS.NO_LENGTH_SAMPLE AS NO_LENGTH_SAMPLE_CUSTOMER,
							   VUSC.KY_SAMPLE_UNIT AS KY_SAMPLE_UNIT_CUSTOMER,
							   VUSC.NM_SAMPLE_UNIT AS NM_SAMPLE_UNIT_CUSTOMER,
							   CF.KY_PROCESS
						  FROM (SELECT TOP 1 *
								  FROM PRD.C_FORM C
								 WHERE C.KY_PROCESS = 'QUALITY'
						      ) CF
						  JOIN ADM.VW_C_SAMPLE_UNIT VUS ON CF.KY_SAMPLE_UNIT = VUS.KY_SAMPLE_UNIT
					 LEFT JOIN ADM.C_CUSTOMER_SAMPLES CS ON CF.ID_FORM = CS.ID_FORM
					 LEFT JOIN ADM.VW_C_SAMPLE_UNIT VUSC ON CS.KY_SAMPLE_UNIT = VUSC.KY_SAMPLE_UNIT
					) CUSTOMER ON WO.KY_CUSTOMER = CUSTOMER.KY_CUSTOMER
	WHERE (@PIN_ID_PALLET IS NULL OR (@PIN_ID_PALLET IS NOT NULL AND KP.ID_PALLET = @PIN_ID_PALLET)) 
		AND (@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND KP.ID_WORK_ORDER = @PIN_ID_WORK_ORDER))
		AND (@PIN_KY_STATUS IS NULL OR (@PIN_KY_STATUS IS NOT NULL AND KP.KY_STATUS = @PIN_KY_STATUS))
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND WO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

