-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez Torres
-- CREATE date: 17/05/2018
-- Description: Report Acct. production
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_RPT_ACCT_PRODUCTION]
	  @PIN_DT_BEGIN				DATE
	, @PIN_DT_END				DATE	
	, @PIN_ID_BRANCH_PLANT		INT
	, @PIN_ID_PRODUCTION_LINE	INT
AS   
BEGIN

	SELECT 
		CBP.KY_BRANCH_PLANT,
		CBP.NM_BRANCH_PLANT,
		KWO.ID_PRODUCTION_LINE, 
		KWO.NM_PRODUCTION_LINE, 
		KWO.ID_ITEM, KWO.NM_ITEM, 
		KWO.ID_WORK_ORDER, 
		ABS(CHECKSUM(NewId())) % 1000 AS NO_PGRP,
		NO_RUN_QTY,
		ABS(CHECKSUM(NewId())) % 10000 AS NO_POUNDS_STD,
		ABS(CHECKSUM(NewId())) % 10000 AS NO_POUNDS_PROD,
		ABS(CHECKSUM(NewId())) % 10000 AS NO_POUNDS_EXT,
		ABS(CHECKSUM(NewId())) % 1000 AS NO_SAVING_RATE_STD,
		ABS(CHECKSUM(NewId())) % 1000 AS NO_SAVING_RATE_ACT,
		ABS(CHECKSUM(NewId())) % 100 AS PR_SAVING_RATE_STD,
		ABS(CHECKSUM(NewId())) % 100 AS PR_SAVING_RATE_YIELD,
		ABS(CHECKSUM(NewId())) % 1.100 AS NO_WEIGHT_STD,
		ABS(CHECKSUM(NewId())) % 1.100 AS NO_WEIGHT_ACT,
		ABS(CHECKSUM(NewId())) % 100.000 AS NO_WEIGHT_VAR_FU,
		ABS(CHECKSUM(NewId())) % 10 AS NO_HOURS_PROD,
		ABS(CHECKSUM(NewId())) % 10 AS NO_HOURS_SDR,
		ABS(CHECKSUM(NewId())) % 10 AS NO_HOURS_OTHER
	FROM PRD.K_WORK_ORDER KWO
		INNER JOIN ADM.C_BRANCH_PLANT CBP ON KWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT

END

