-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Díaz
-- Create date: 10/22/2018
-- Description: GET AUTHORIZED USERS FOR SPECIFIC PROCESS
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_AUTHORIZED_USERS]
	@PIN_KY_PROCESS NVARCHAR(50)
	, @PIN_ID_BRANCH_PLANT INT
AS 
BEGIN  

	DECLARE @T_AUTHORIZED_USERS TABLE (
		ID_POSITION INT
		, NM_POSITION NVARCHAR(500)
		, NM_FULL NVARCHAR(500)
		, KY_USER NVARCHAR(50)
	)

	DECLARE @T_AUHORIZED_POSITION TABLE (
		ID_POSITION INT,
		NM_POSITION NVARCHAR(50)
	)

	DECLARE @XML_CONFIGURATION XML 
		, @XML_BRANCH_PLANT_SELECTED XML

	SELECT TOP 1 @XML_CONFIGURATION = XML_CONFIGURATION FROM ADM.S_CONFIGURATION

	SELECT @XML_BRANCH_PLANT_SELECTED = msgs.msg.query('.') FROM @XML_CONFIGURATION.nodes('/CONFIGURATIONS/ESPECIFIC_CONFIGURATION/BRANCH_PLANT[@ID_BRANCH_PLANT=sql:variable("@PIN_ID_BRANCH_PLANT")]') msgs(msg)	

	IF @PIN_KY_PROCESS IN ('CANCEL_FORM', 'ENTER_OUT_OF_RANGE', 'SKIP_WORK_ORDER') BEGIN
		IF @PIN_KY_PROCESS IN ('CANCEL_FORM', 'SKIP_WORK_ORDER') BEGIN
			INSERT INTO @T_AUHORIZED_POSITION (
				ID_POSITION
				, NM_POSITION
			)
			SELECT x.ref.value('@ID_POSITION', 'INT') ID_POSITION
				, x.ref.value('@NM_POSITION', 'nvarchar(50)') NM_POSITION
			FROM @XML_BRANCH_PLANT_SELECTED.nodes('/BRANCH_PLANT/PRODUCTION_LINE_AUTHORIZERS/POSITION') x(ref)

		END

		IF @PIN_KY_PROCESS = 'ENTER_OUT_OF_RANGE' BEGIN
			INSERT INTO @T_AUHORIZED_POSITION (
				ID_POSITION
				, NM_POSITION
			)
			SELECT ID_POSITION
				, NM_POSITION
			FROM ADM.C_POSITION CP
			WHERE CP.ID_POSITION = @XML_BRANCH_PLANT_SELECTED.value('(/BRANCH_PLANT/QUALITY_PROCESS/SCHEDULER/@ID_POSITION)[1]', 'INT')

		END

		INSERT INTO @T_AUTHORIZED_USERS (
			ID_POSITION
			, NM_POSITION
			, NM_FULL
			, KY_USER
		)
		SELECT P.ID_POSITION
			 , P.NM_POSITION
			 , CE.NM_FIRST_NAME + ' ' + CE.NM_LAST_NAME AS NM_FULL
			 , CU.KY_USER
		FROM @T_AUHORIZED_POSITION P
			INNER JOIN ADM.C_EMPLOYEE CE 
				ON P.ID_POSITION = CE.ID_POSITION
			INNER JOIN ADM.C_USER CU 
				ON CE.ID_EMPLOYEE = CU.ID_EMPLOYEE
		WHERE CU.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT
			AND CE.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT
			AND CU.FG_ACTIVE = 1 
			AND CE.FG_ACTIVE = 1 
	END

	SELECT ID_POSITION
		, NM_POSITION
		, NM_FULL
		, KY_USER
	FROM @T_AUTHORIZED_USERS

END

