-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 8/05/2017
-- Description: get WORK ORDER REPORT
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_WORK_ORDER_REPORT] 
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_ID_WORK_ORDER AS int = NULL,
        @PIN_KY_STATUS AS XML = NULL,
		@PIN_ID_PRODUCTION_LINE AS int = NULL
		
	AS  
		 SELECT KWO.ID_WORK_ORDER
			   ,KWO.ID_PRODUCTION_LINE
			   ,KWO.NO_WORK_ORDER
			   ,CPL.KY_PRODUCTION_LINE
			   ,CPL.NM_PRODUCTION_LINE
			   ,CONVERT(VARCHAR(10),KWO.DT_WORK_ORDER,101) DT_WORK_ORDER
			   ,KWO.ID_ITEM
			   ,CI.KY_ITEM
			   ,CI.NM_ITEM
			   ,CONVERT(VARCHAR(10),KWO.DT_WORK_ORDER,101) DT_INITIAL_TIME
			   ,KI.SUMARY_LOST_TIME
			   ,KWO.NO_ASSIGNED_TIME SCHEDULE_TIME
			   ,KWO.KY_STATUS
			   ,VWS.NM_WORK_ORDER_STATUS
			   
		   FROM PRD.K_WORK_ORDER KWO
LEFT OUTER JOIN PRD.C_ITEM CI ON KWO.ID_ITEM = CI.ID_ITEM
LEFT OUTER JOIN PRD.C_PRODUCTION_LINE CPL ON KWO.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
LEFT OUTER JOIN ADM.VW_C_WORK_ORDER_STATUS VWS ON KWO.KY_STATUS = VWS.KY_WORK_ORDER_STATUS
LEFT OUTER JOIN (
				 SELECT KIS.ID_WORK_ORDER, SUM(DATEDIFF(hour, DT_CONFIRMED, DT_ISSUE_CLOSED)) SUMARY_LOST_TIME
				 FROM PRD.K_ISSUE KIS
				 GROUP BY ID_WORK_ORDER
				 ) KI ON KWO.ID_WORK_ORDER = KI.ID_WORK_ORDER
--JOIN (SELECT x.ref.value('@KY_STATUS', 'VARCHAR(20)') KY_STATUS_WORK_ORDER
--					  FROM @PIN_KY_STATUS_WORK_ORDER.nodes('/STATUS/ST') x(ref)
--					) G_STATUS ON KWO.KY_STATUS = G_STATUS.KY_STATUS_WORK_ORDER
		  WHERE
		  (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND KWO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT )) AND 
		  (@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND KWO.ID_WORK_ORDER = @PIN_ID_WORK_ORDER)) AND
		  (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND KWO.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE )) 
	  
	  ORDER BY DT_WORK_ORDER ASC

