-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Javier Diaz Barron
-- CREATE date: 14/06/2017
-- Description: get all form by pallet
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_FORM_PALLET] 
		@PIN_ID_PALLET AS int = NULL,
	    @PIN_ID_QA27 AS int = NULL,
	    @PIN_ID_WORK_ORDER AS int = NULL


AS   
	SELECT 
		 KP.[ID_PALLET]	
		,KP.[ID_QA27]			
		,KP.ID_WORK_ORDER				
		,KF.ID_K_FORM
		,CF.ID_FORM
		,CF.[KY_FORM]
		,CF.[NM_FORM]
		,CF.DS_FORM
		,(CAST(CF.NO_SAMPLE  AS NVARCHAR(5)) + ' ' + SU.NM_SAMPLE_UNIT) NO_SAMPLE 
		,CF.KY_SAMPLE_UNIT						
	FROM PRD.K_PALLET KP	
		INNER JOIN PRD.K_FORM KF ON KF.ID_PALLET = KP.ID_PALLET
		INNER JOIN PRD.C_FORM CF ON CF.ID_FORM = KF.ID_FORM	
		LEFT JOIN ADM.VW_C_SAMPLE_UNIT SU ON SU.KY_SAMPLE_UNIT = CF.KY_SAMPLE_UNIT
	WHERE KF.KY_STATUS_FORM NOT IN ('CANCELED') AND
		(@PIN_ID_PALLET IS NULL OR (@PIN_ID_PALLET IS NOT NULL AND KP.[ID_PALLET] = @PIN_ID_PALLET)) AND 
		(@PIN_ID_QA27 IS NULL OR (@PIN_ID_QA27 IS NOT NULL AND KP.[ID_QA27] = @PIN_ID_QA27)) AND 
		(@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND KP.[ID_WORK_ORDER] = @PIN_ID_WORK_ORDER))

