-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 04/11/2017
-- Description: Get Work order from JDEdwards
-- =============================================

CREATE PROCEDURE  [PRD].[SPE_GET_WORK_ORDERS_JDEDWARDS] 
	@PIN_ID_BRANCH_PLANT INT
	, @PIN_FG_TEST AS BIT = NULL
	, @PIN_ID_PRODUCTION_LINE AS INT = NULL
AS  

	DECLARE @ID_BRANCH_PLANT NVARCHAR(10) = (
			SELECT TOP 1   SUBSTRING(CBP.KY_BRANCH_PLANT, 3,2) 
			FROM PRD.C_PRODUCTION_LINE CPL 
				INNER JOIN ADM.C_BRANCH_PLANT CBP 
					ON CPL.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT 
			WHERE ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE
		)


	SELECT ID_WORK_ORDER
		, KY_CUSTOMER
		, NM_CUSTOMER
		, NO_WORK_ORDER
		, NO_ORDER
		, NO_SEQ
		, CAST(ISNULL(CI.ID_ITEM,0) AS INT) AS ID_ITEM
		, CI.KY_ITEM
		, CI.NM_ITEM
		, ID_PRODUCTION_LINE
		, KY_PRODUCTION_LINE
		, NM_PRODUCTION_LINE
		, KY_BRANCH_PLANT
		, DT_WORK_ORDER
		, NO_RUN_QTY
		, NO_BOX_QTY
		, NM_MATERIAL
		, NM_COLOR
		, NO_LENGHT
		, NO_WIDTH
		, NO_THICKNESS
		, KY_PACKAGE
		, PACKED
		--, NO_QTY_SKID
		, CASE WHEN CI.NO_PIECES_PER_SKID  IS NULL THEN 0 ELSE CI.NO_PIECES_PER_SKID END AS NO_QTY_SKID
		, NO_SHIPING_WEIGHT_PER_HR
		, DT_REQ_DATE
		, CL_STATUS
		, CASE WHEN CI.NO_PIECES_PER_SKID IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS FG_HAS_NO_PICES_PER_SKID
		, CASE WHEN VKWOJ.ID_ITEM IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS FG_HAS_ID_ITEM
		, CASE WHEN (SELECT COUNT(ID_ITEM_CHARACTERISTIC) FROM PRD.C_ITEM_CHARACTERISTIC CIC WHERE CIC.ID_ITEM = VKWOJ.ID_ITEM) = 0 THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS FG_HAS_CHARACTERISTICS
	FROM PRD.VW_K_WORK_ORDER_JDEDWARDS VKWOJ
		LEFT JOIN PRD.C_ITEM CI ON VKWOJ.ID_ITEM = CI.ID_ITEM
	WHERE KY_BRANCH_PLANT = @ID_BRANCH_PLANT
		AND CL_STATUS = '45'
		AND (@PIN_ID_PRODUCTION_LINE IS NULL OR ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE)
		AND NOT EXISTS (SELECT TOP 1 1 FROM PRD.K_WORK_ORDER KWO WHERE VKWOJ.ID_WORK_ORDER = KWO.ID_WORK_ORDER)
	ORDER BY NO_SEQ, DT_REQ_DATE DESC
