-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 08/03/2017
-- Description: get all defect category 
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_DEFECT_CATEGORY] 
	    @PIN_ID_DEFECT_CATEGORY AS int = NULL,
        @PIN_KY_DEFECT_CATEGORY AS nvarchar(50) = NULL,
        @PIN_NM_DEFECT_CATEGORY AS nvarchar(300) = NULL,
        @PIN_DS_DEFECT_CATEGORY AS nvarchar(500) = NULL,
		@PIN_ID_BRANCH_PLANT AS int = NULL,
        @PIN_FG_ACTIVE AS bit = NULL

AS   
				SELECT 
					 ID_DEFECT_CATEGORY,
					 KY_DEFECT_CATEGORY,
					 NM_DEFECT_CATEGORY,
					 DS_DEFECT_CATEGORY,
					 ISNULL(CP.NM_BRANCH_PLANT,'All') NM_BRANCH_PLANT,
					 CP.ID_BRANCH_PLANT,
					 FG_ACTIVE,
					 CASE FG_ACTIVE WHEN 1 THEN 'Yes' ELSE 'No' END AS KY_ACTIVE
				FROM PRD.C_DEFECT_CATEGORY CDC
	 LEFT OUTER JOIN ADM.C_BRANCH_PLANT CP ON CDC.ID_BRANCH_PLANT = CP.ID_BRANCH_PLANT
			   WHERE (@PIN_ID_DEFECT_CATEGORY IS NULL OR (@PIN_ID_DEFECT_CATEGORY IS NOT NULL AND [ID_DEFECT_CATEGORY] = @PIN_ID_DEFECT_CATEGORY )) AND 
				 	 (@PIN_KY_DEFECT_CATEGORY IS NULL OR (@PIN_KY_DEFECT_CATEGORY IS NOT NULL AND UPPER([KY_DEFECT_CATEGORY]) = UPPER(@PIN_KY_DEFECT_CATEGORY ))) AND 
					 (@PIN_NM_DEFECT_CATEGORY IS NULL OR (@PIN_NM_DEFECT_CATEGORY IS NOT NULL AND UPPER([NM_DEFECT_CATEGORY]) = UPPER(@PIN_NM_DEFECT_CATEGORY ))) AND 
    				 (@PIN_DS_DEFECT_CATEGORY IS NULL OR (@PIN_DS_DEFECT_CATEGORY IS NOT NULL AND UPPER([DS_DEFECT_CATEGORY]) = UPPER(@PIN_DS_DEFECT_CATEGORY ))) AND 
					 (@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND [FG_ACTIVE] = @PIN_FG_ACTIVE)) AND
					 (@PIN_ID_BRANCH_PLANT IS NULL OR CDC.ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CDC.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

