

-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - VITEK - 2019
-- Author: DELLC
-- CREATE date: 07/15/2019
-- Description: Get unproductive events time
-- =============================================
-- =============================================
CREATE PROCEDURE  [PRD].[SPE_GET_TIME_UNPRODUCTIVE_EVENTS]
	  @MIDDLE_DATE varchar(20),
	  @ID_BP INT = NULL

AS
BEGIN    
	DECLARE  
	 @INIT DATETIME,
	 @ENDT DATETIME

	 SET @INIT = DATEADD(HOUR, -6, @MIDDLE_DATE)
	 SET @ENDT = DATEADD(HOUR, 6, @MIDDLE_DATE)

    
	SELECT ID_ISSUE, ID_WORK_ORDER, ID_PRODUCTION_LINE,   FG_LINE_DOWN, DT_ISSUE,   ISNULL(DT_ISSUE_CLOSED,GETDATE()) AS DT_ISSUE_CLOSED, 
 DATEDIFF(MINUTE, DT_ISSUE, DT_ISSUE_CLOSED) AS MIN_DURATION, DS_ISSUE_EXPLANATION_OPEN  FROM PRD.K_ISSUE I WHERE 
 EXISTS (SELECT ID_WORK_ORDER FROM PRD.K_WORK_ORDER W WHERE W.ID_BRANCH_PLANT = @ID_BP AND I.ID_WORK_ORDER = W.ID_WORK_ORDER) AND
  DT_ISSUE  BETWEEN @INIT AND @ENDT OR (
			@INIT BETWEEN DT_ISSUE AND ISNULL(DT_ISSUE_CLOSED,GETDATE()) AND KY_STATUS='HOLD_ON') AND NM_PROGAM_CREATE <> 'SkipWO'
			
END

