-- =============================================
-- Author:		<Christian ,Moreno>
-- Create date: <04/21/2020,,>
-- Update date: <6/24/2020,,>
-- Description:	<Obtener las mediciones de formulario soc por qa27,,>
-- =============================================
CREATE PROCEDURE [PRD].[SPE_GET_FORMSOC_TO_REPORT]
	--@PIN_WORKORDER AS INT,
	@PIN_SHIFT AS NVARCHAR(50),
	@PIN_DT AS DATETIME
	--@PIN_ID_FORM AS INT
AS
BEGIN

	
 DECLARE @INIT DATETIME,
		-- especifica el turno 1 que inicia a las 00 horas de la madrugada
		@TURNO_SF1_INIT DATETIME = (SELECT INITIAL_SHIFT_TIME FROM ADM.VW_C_SHIFT WHERE KY_SHIFT = 'SF-1'), 
		@TURNO_SF1_FINAL DATETIME = (SELECT FINAL_SHIFT_TIME FROM ADM.VW_C_SHIFT WHERE KY_SHIFT = 'SF-1'), 
		-- especifica el turno 2 que inicia a las 12 horas de la tarde
		@TURNO_SF2_INIT DATETIME = (SELECT INITIAL_SHIFT_TIME FROM ADM.VW_C_SHIFT WHERE KY_SHIFT = 'SF-2'), 
		@TURNO_SF2_FINAL DATETIME = (SELECT FINAL_SHIFT_TIME FROM ADM.VW_C_SHIFT WHERE KY_SHIFT = 'SF-2'),
		@FECHA_FINAL DATETIME

		IF (@PIN_SHIFT  = 'SF-1')
		BEGIN 
		SET @INIT = DATEADD(HOUR, 0,@PIN_DT)
		(SELECT @FECHA_FINAL = CONVERT(DATETIME, @PIN_DT) + CONVERT(DATETIME, @TURNO_SF1_FINAL))
		END
		ELSE
		BEGIN
		SET @INIT = DATEADD(HOUR, 12, @PIN_DT)
		(SELECT @FECHA_FINAL = CONVERT(DATETIME, @PIN_DT) + CONVERT(DATETIME, @TURNO_SF2_FINAL))
		END
		SET @PIN_DT = @FECHA_FINAL
	
	SELECT --KQA.ID_QA27, 
	KQA.ID_WORK_ORDER, 
	KQA.KY_SHIFT,
	--KQA.DT_QA27,
	KF.ID_K_FORM, 
	KFM.ID_METRICS, 
	KFM.XML_METRICS_VALUE.value('(/FIELD_TYPES/@FINISHED_VALUE)[1]', 'NVARCHAR(50)') as MATERIAL, 
	KFM.XML_METRICS_VALUE.value('(/FIELD_TYPES/@PERCENTAGE)[1]', 'NVARCHAR(50)') as CONCENTRATE_PERCENT,
	--KFM.DT_CREATION,
	KF.DT_CLOSED,
	KWO.ID_PRODUCTION_LINE,
	KWO.NM_ITEM,
	CI.KY_ITEM
	FROM PRD.K_QA27 KQA 
	INNER JOIN PRD.K_FORM KF ON KQA.ID_WORK_ORDER = KF.ID_WORK_ORDER AND KF.ID_QA27 = KQA.ID_QA27
	INNER JOIN PRD.K_FORM_METRICS KFM ON KF.ID_K_FORM = KFM.ID_K_FORM
	INNER JOIN PRD.K_WORK_ORDER KWO ON KQA.ID_WORK_ORDER = KWO.ID_WORK_ORDER 
	INNER JOIN PRD.C_ITEM CI ON KWO.ID_ITEM = CI.ID_ITEM

	WHERE KQA.KY_SHIFT = @PIN_SHIFT AND (KFM.ID_METRICS = 71 OR KFM.ID_METRICS = 40) AND KF.ID_FORM = 3 and KQA.DT_QA27 BETWEEN @INIT AND  @PIN_DT 
	AND KF.ID_K_FORM = (SELECT TOP 1 ID_K_FORM FROM PRD.K_FORM KF WHERE ID_WORK_ORDER = KQA.ID_WORK_ORDER AND KF.ID_FORM = 3 AND KY_STATUS_FORM='CAPTURED' AND DT_CLOSED BETWEEN @INIT AND  @PIN_DT ORDER BY DT_FORM DESC)
	
	--FOR JSON AUTO
	ORDER BY KQA.ID_WORK_ORDER
	
END
