-- Proyecto: Plaskolite
-- Copyright (c) - VITEK - 2020
-- Author: DELLC
-- CREATE date: 07/06/2020
-- Description: “SOC readings report” 
CREATE PROCEDURE   [PRD].[SPE_GET_RPT_SOC]
	@PIN_DT_INITIAL DATE = NULL
	, @PIN_DT_FINAL DATE = NULL
	, @PIN_ID_PRODUCTION_LINE INT = NULL
	, @PIN_KY_ITEM NVARCHAR(50) = NULL
	, @PIN_ID_BRANCH_PLANT INT = NULL
	, @PIN_CHARACTERISTIC VARCHAR(50) = NULL
	, @PIN_NOMINAL_VALUE NVARCHAR(MAX) = NULL

AS
BEGIN
				
	; WITH T_READINGS AS (
		SELECT REPLACE(KS.KY_SHIFT_TIME, 'SF-', '') AS KY_SHIFT_TIME
			, KWO.ID_WORK_ORDER
			, KWO.KY_CUSTOMER
			, KWO.NM_CUSTOMER
			, CI.KY_ITEM
			, CI.NM_ITEM
			, CMX.NM_METRICS
			, CASE WHEN KF.ID_K_FORM IS NULL OR KF.KY_STATUS_FORM IN ('CANCELLED', 'CREATED') THEN 'N' ELSE '' END AS KY_NO_READINGS
			, KF.DT_FORM
			, KF.ID_K_FORM
			, KF.KY_STATUS_FORM
			, KF.KY_USER_APP_CREATION
			, KF.KY_USER_AUTHORIZED_CANCEL
			, KF.DS_EXPLANATION_CANCEL
			, KF.KY_USER_AUTHORIZED_OUT_OF_RANGE
			, KF.DS_EXPLANAtION_OUT_OF_RANGE
			, CPL.NM_PRODUCTION_LINE
			, CPL.ID_PRODUCTION_LINE
			, KF.DT_CLOSED
			, CASE WHEN  KFM.ID_METRICS = 40  THEN 
			CASE WHEN XML_METRICS_VALUE.value('(/FIELD_TYPES/@FINISHED_VALUE)[1]', 'NVARCHAR(MAX)') = 'undefined' THEN '' ELSE
			XML_METRICS_VALUE.value('(/FIELD_TYPES/@FINISHED_VALUE)[1]', 'NVARCHAR(MAX)') + 
			XML_METRICS_VALUE.value('(/FIELD_TYPES/@PERCENTAGE)[1]', 'NVARCHAR(MAX)') END   ELSE
			XML_METRICS_VALUE.value('(/FIELD_TYPES/@FINISHED_VALUE)[1]', 'NVARCHAR(MAX)') END  AS FINISHED_VALUE
			, XML_METRICS_VALUE.value('(/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'NVARCHAR(MAX)') AS NOMINAL_VALUE
		FROM PRD.K_WORK_ORDER KWO
			INNER JOIN ADM.C_BRANCH_PLANT CBP
				ON KWO.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT
			INNER JOIN PRD.C_ITEM CI 
				ON CI.ID_ITEM =  KWO.ID_ITEM 
			INNER JOIN PRD.C_ITEM_CHARACTERISTIC CIC
				ON CIC.ID_ITEM = CI.ID_ITEM 
			INNER JOIN PRD.C_METRICS CM
				ON CM.ID_METRICS = CIC.ID_METRICS 
			INNER JOIN PRD.K_FORM KF 
				ON KF.ID_WORK_ORDER = KWO.ID_WORK_ORDER AND KF.ID_FORM =3
			INNER JOIN PRD.K_FORM_METRICS KFM 
				ON KF.ID_K_FORM = KFM.ID_K_FORM AND 
				 KFM.XML_METRICS_VALUE.value('(/FIELD_TYPES/@FIELD_TYPE)[1]', 'NVARCHAR(20)') = 'NUMERICBOX'
				AND KFM.XML_METRICS_VALUE.value('(/FIELD_TYPES/@FINISHED_VALUE)[1]', 'VARCHAR(10)') NOT IN ('','null','undefined')
				AND KF.KY_STATUS_FORM != 'CANCELLED'
			INNER JOIN PRD.C_METRICS CMX 
				ON CMX.ID_METRICS = KFM.ID_METRICS
			INNER JOIN PRD.K_QA27 KQ
				ON KF.ID_QA27 = KQ.ID_QA27
			INNER JOIN PRD.K_SHIFT KS
				ON KQ.ID_SHIFT = KS.ID_SHIFT
			INNER JOIN PRD.C_PRODUCTION_LINE CPL
				ON KS.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
			
			
		WHERE 
			CM.NM_METRICS =  CASE WHEN @PIN_CHARACTERISTIC IS NULL THEN 'Weight' ELSE @PIN_CHARACTERISTIC END    AND
		    CAST(KF.DT_CLOSED AS DATE) BETWEEN ISNULL( @PIN_DT_INITIAL, '1/1/2018') AND ISNULL (@PIN_DT_FINAL, GETDATE() ) 
			AND (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND KS.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE))
			AND (@PIN_KY_ITEM IS NULL OR  (@PIN_KY_ITEM  IS NOT NULL AND  CI.KY_ITEM = @PIN_KY_ITEM))
			AND (@PIN_CHARACTERISTIC IS NULL OR  (@PIN_CHARACTERISTIC  IS NOT NULL AND  CM.NM_METRICS = @PIN_CHARACTERISTIC))
			AND (@PIN_NOMINAL_VALUE IS NULL OR  (@PIN_NOMINAL_VALUE  IS NOT NULL AND 
			CIC.XML_FIELD_SETTINGS.value('(SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'NVARCHAR(MAX)') = @PIN_NOMINAL_VALUE))
	)

	SELECT
		
		  TR.NM_PRODUCTION_LINE
		, TR.ID_PRODUCTION_LINE
		, TR.KY_SHIFT_TIME
		, TR.ID_WORK_ORDER
		, TR.KY_ITEM
		, TR.NM_ITEM
		, TR.NM_METRICS
		, TR.FINISHED_VALUE
		, TR.DT_CLOSED
		, TR.KY_USER_APP_CREATION AS KY_USER
	FROM T_READINGS TR  

	ORDER BY DT_CLOSED
END

