-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 15/06/2017
-- Description: GET POSITION OF CONFIGURATION TO MRB 2
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_VERDICT_POSITIONS_MRB2] 
	@PIN_ID_BRANCH_PLANT NVARCHAR(5)
AS
	SET @PIN_ID_BRANCH_PLANT = ISNULL(@PIN_ID_BRANCH_PLANT, 'ALL')
	
	DECLARE @XML_CONFIGURATION XML , @XML_BRANCH_PLANT_SELECTED XML
	
	SELECT @XML_CONFIGURATION =XML_CONFIGURATION FROM ADM.S_CONFIGURATION

	DECLARE @T_POSITIONS AS TABLE(ID_POSITION INT, ID_POSITION_BACKUP INT, FG_IS_OPTIONAL BIT, XML_POSITIONS XML)

	SELECT 				 
		 @XML_BRANCH_PLANT_SELECTED=msgs.msg.query('.')
	FROM @XML_CONFIGURATION.nodes('CONFIGURATIONS/ESPECIFIC_CONFIGURATION/child::node()') msgs(msg)	
	WHERE msgs.msg.value('@ID_BRANCH_PLANT', 'nvarchar(max)') = @PIN_ID_BRANCH_PLANT
	
	INSERT INTO @T_POSITIONS
	SELECT		
		msgs.msg.value('@ID_POSITION', 'INT') ID_POSITION,
		msgs.msg.value('@ID_POSITION_BACKUP', 'INT') ID_POSITION_BACKUP,
		--msgs.msg.value('@FG_IS_OPTIONAL', 'BIT') FG_IS_OPTIONAL,
		isnull(msgs.msg.value('@FG_IS_OPTIONAL', 'BIT'),cast(0 as bit)) FG_IS_OPTIONAL,
		msgs.msg.query('.') XML_POSITIONS
	FROM @XML_BRANCH_PLANT_SELECTED.nodes('BRANCH_PLANT/QUALITY_PROCESS/POSITIONS_MBR2/child::node()') msgs(msg)  --,PRD.K_PALLET KP



	SELECT 
		TP.ID_POSITION,
		TP.ID_POSITION_BACKUP,
		TP.FG_IS_OPTIONAL,
		TP.XML_POSITIONS,
		CP.KY_EMAIL
	FROM @T_POSITIONS TP
		INNER JOIN ADM.C_POSITION CP ON TP.ID_POSITION = CP.ID_POSITION

