-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 22/03/2017
-- Description: get all forms
-- =============================================
-- 08/05/2018 JDR NO_RANDOM_ACQUISITION_VARIABLES column added
-- =============================================

CREATE PROCEDURE  [PRD].[SPE_GET_FORM] 
		@PIN_ID_FORM AS INT = NULL,
		@PIN_NM_FORM AS nvarchar(300) = NULL,
        @PIN_FREQUENCY AS nvarchar(50) = NULL,
		@PIN_NM_DATA_ADQUISITION AS nvarchar = NULL,
        @PIN_SAMPLE AS nvarchar(500) = NULL,
        @KY_PROCESS NVARCHAR(50) = NULL ,
		--@PIN_1ST_LEVEL AS NVARCHAR(100) = NULL,
		--@PIN_2ST_LEVEL AS NVARCHAR(100) = NULL,
		--@PIN_3ST_LEVEL AS NVARCHAR(100) = NULL,
		--@PIN_4ST_LEVEL AS NVARCHAR(100) = NULL, 
		@PIN_FG_ACTIVE AS bit = NULL,
		@PIN_ID_BRANCH_PLANT AS int = NULL		
AS   
	; WITH T_TIME_HOLD AS (
		SELECT KAU.ID_FORM
			, KAU.NO_TIME_HOLD_ON 
		FROM PRD.K_POSITION_SCALING KAU 
		WHERE ID_FORM IS NOT NULL
		GROUP BY KAU.ID_FORM, KAU.NO_TIME_HOLD_ON 
	)

	SELECT CF.ID_FORM
		, CF.KY_FORM
		, CF.NM_FORM
		, CF.DS_FORM
		, CF.NO_FREQUENCE
		, VDA.NM_DATA_ACQUISITION_ORIGIN
		, VDA.ID_DATA_ACQUISITION_ORIGIN
		, ISNULL(CBP.NM_BRANCH_PLANT, 'All') AS NM_BRANCH_PLANT
		, CBP.ID_BRANCH_PLANT
		, CASE CF.FG_ACTIVE WHEN 1 THEN 'Yes' ELSE 'No' END AS KY_ACTIVE
		, CF.NO_SAMPLE
		, CF.KY_SAMPLE_UNIT
		, VSU.NM_SAMPLE_UNIT
		, CF.KY_PROCESS
		, VP.NM_PROCESS
		, TH.NO_TIME_HOLD_ON
		, CF.FG_GET_PERIODICALLY
		, CF.ID_PRODUCTION_LINE_TYPE
		, VSPLT.KY_PRODUCTION_LINE_TYPE
		, CF.NO_RANDOM_ACQUISITION_VARIABLES
	FROM PRD.C_FORM CF
		INNER JOIN ADM.VW_C_DATA_ACQUISITION_ORIGIN VDA 
			ON CF.ID_DATA_ACQUISITION_ORIGIN = VDA.ID_DATA_ACQUISITION_ORIGIN 
		INNER JOIN ADM.VW_C_SAMPLE_UNIT VSU 
			ON CF.KY_SAMPLE_UNIT = VSU.KY_SAMPLE_UNIT
		INNER JOIN ADM.VW_C_PROCESS VP 
			ON CF.KY_PROCESS = VP.KY_PROCESS
		INNER JOIN ADM.VW_S_PRODUCTION_LINE_TYPE VSPLT
			ON CF.ID_PRODUCTION_LINE_TYPE = VSPLT.ID_PRODUCTION_LINE_TYPE
		LEFT OUTER JOIN ADM.C_BRANCH_PLANT CBP 
			ON CF.ID_BRANCH_PLANT = CBP.ID_BRANCH_PLANT 
		LEFT OUTER JOIN T_TIME_HOLD TH 
			ON CF.ID_FORM = TH.ID_FORM
	WHERE (@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND CF.FG_ACTIVE=@PIN_FG_ACTIVE)) AND
		(@PIN_ID_FORM IS NULL OR (@PIN_ID_FORM IS NOT NULL AND CF.ID_FORM = @PIN_ID_FORM)) AND 
		(@PIN_NM_FORM IS NULL OR (@PIN_NM_FORM IS NOT NULL AND UPPER(CF.NM_FORM) = UPPER(@PIN_NM_FORM) )) AND 
		(@PIN_FREQUENCY IS NULL OR (@PIN_FREQUENCY IS NOT NULL AND (CF.NO_FREQUENCE) = (@PIN_FREQUENCY ))) AND 
		(@PIN_NM_DATA_ADQUISITION IS NULL OR (@PIN_NM_DATA_ADQUISITION IS NOT NULL AND UPPER(VDA.NM_DATA_ACQUISITION_ORIGIN) = UPPER(@PIN_NM_DATA_ADQUISITION ))) AND 
		(@PIN_SAMPLE IS NULL OR (@PIN_SAMPLE IS NOT NULL AND CF.NO_SAMPLE = @PIN_SAMPLE )) AND 
		(@PIN_ID_BRANCH_PLANT IS NULL OR CBP.ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CBP.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT )) AND
		(@KY_PROCESS IS NULL OR (@KY_PROCESS IS NOT NULL AND CF.KY_PROCESS = @KY_PROCESS ))

