CREATE PROCEDURE [PRD].[SPE_GET_SHIFT_TIME_DATE]
 @DT DATETIME,
 @BP INT
AS	
BEGIN

DECLARE 
	@DT_1 DATETIME,
	@DT_2 DATETIME

SET @DT_1 = @DT
SET @DT_2 = DATEADD(HOUR, 12, @DT);


CREATE TABLE #SHIFTS(
ID_SHIFT INT,
KY_SHIFT VARCHAR(5),
KY_SHIFT_TIME VARCHAR(5)
)

INSERT INTO #SHIFTS
SELECT TOP 1 ID_SHIFT, KY_SHIFT,  KY_SHIFT_TIME FROM PRD.K_SHIFT 
WHERE DT_START_SHIFT = @DT_1 AND KY_SHIFT IS NOT NULL AND  ID_BRANCH_PLANT = @BP

INSERT INTO #SHIFTS
SELECT TOP 1 ID_SHIFT, KY_SHIFT,  KY_SHIFT_TIME FROM PRD.K_SHIFT
WHERE DT_START_SHIFT = @DT_2 AND KY_SHIFT IS NOT NULL AND  ID_BRANCH_PLANT = @BP

SELECT * FROM #SHIFTS

END

