-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 13/03/2017
-- Description: get all problem's area 
-- =============================================


CREATE PROCEDURE    [PRD].[SPE_GET_PROBLEM_AREA]  
	    @PIN_ID_PROBLEM_AREA AS int = NULL,
        @PIN_KY_PROBLEM_AREA AS nvarchar(50) = NULL,
        @PIN_NM_PROBLEM_AREA AS nvarchar(100) = NULL,
        @PIN_DS_PROBLEM_AREA AS nvarchar(1000) = NULL,
        @PIN_FG_ACTIVE AS BIT = NULL,
        @PIN_ID_BRANCH_PLANT AS INT = NULL

AS   
	SELECT 
	PA.[ID_PROBLEM_AREA],
	PA.[KY_PROBLEM_AREA],
	PA.[NM_PROBLEM_AREA],
	PA.[DS_PROBLEM_AREA],
	PA.[FG_ACTIVE],
	CASE PA.[FG_ACTIVE] WHEN 1 THEN 'Yes' ELSE 'No' END AS KY_ACTIVE,
	PA.[ID_BRANCH_PLANT],
	BP.KY_BRANCH_PLANT,
	ISNULL(BP.NM_BRANCH_PLANT,'All') AS NM_BRANCH_PLANT
	FROM [PRD].[C_PROBLEM_AREA] PA
	LEFT OUTER JOIN ADM.C_BRANCH_PLANT BP ON PA.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
	WHERE (@PIN_ID_PROBLEM_AREA IS NULL OR (@PIN_ID_PROBLEM_AREA IS NOT NULL AND PA.[ID_PROBLEM_AREA] = @PIN_ID_PROBLEM_AREA)) AND 
			(@PIN_KY_PROBLEM_AREA IS NULL OR (@PIN_KY_PROBLEM_AREA IS NOT NULL AND PA.[KY_PROBLEM_AREA] = @PIN_KY_PROBLEM_AREA)) AND 
			(@PIN_NM_PROBLEM_AREA IS NULL OR (@PIN_NM_PROBLEM_AREA IS NOT NULL AND PA.[NM_PROBLEM_AREA] = @PIN_NM_PROBLEM_AREA)) AND 
    		(@PIN_DS_PROBLEM_AREA IS NULL OR (@PIN_DS_PROBLEM_AREA IS NOT NULL AND PA.[DS_PROBLEM_AREA] = @PIN_DS_PROBLEM_AREA)) AND 
			(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND PA.[FG_ACTIVE] = @PIN_FG_ACTIVE)) AND
			(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND (PA.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR PA.ID_BRANCH_PLANT IS NULL)))

