-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- Create date: 08/24/2018
-- Description: GET AUTHORIZED USER TO CANCEL READINGS
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_AUTHORIZED_USERS_CANCEL_READINGS]
		@PIN_ID_K_FORM INT = NULL
AS 
BEGIN  
	DECLARE @T_AUHORIZED_POSITION TABLE (
		ID_POSITION INT,
		NM_POSITION NVARCHAR(50)
	)
	DECLARE @XML_CONFIGURATION XML 
		, @XML_BRANCH_PLANT_SELECTED XML
		, @V_ID_BRANCH_PLANT INT

	SELECT @V_ID_BRANCH_PLANT = KF.ID_BRANCH_PLANT
		FROM PRD.K_FORM KF
		WHERE ID_K_FORM = @PIN_ID_K_FORM

	SELECT @XML_CONFIGURATION = XML_CONFIGURATION 
	FROM ADM.S_CONFIGURATION


	SELECT @XML_BRANCH_PLANT_SELECTED = msgs.msg.query('.')
	FROM @XML_CONFIGURATION.nodes('CONFIGURATIONS/ESPECIFIC_CONFIGURATION/child::node()') msgs(msg)	
	WHERE msgs.msg.value('@ID_BRANCH_PLANT', 'nvarchar(max)') = @V_ID_BRANCH_PLANT


	INSERT INTO @T_AUHORIZED_POSITION
	SELECT --x.ref.query('.'),
		   x.ref.value('@ID_POSITION', 'INT') ID_POSITION, 
		   x.ref.value('@NM_POSITION', 'nvarchar(50)') NM_POSITION
	FROM @XML_BRANCH_PLANT_SELECTED.nodes('/BRANCH_PLANT/PRODUCTION_LINE_AUTHORIZERS/POSITION') x(ref)
	

	SELECT P.ID_POSITION
		 , P.NM_POSITION
		 , CE.NM_FIRST_NAME +' '+ CE.NM_LAST_NAME AS FULL_NAME
		 , CU.KY_USER
	FROM @T_AUHORIZED_POSITION P
	JOIN ADM.C_EMPLOYEE CE 
		ON P.ID_POSITION = CE.ID_POSITION
	JOIN ADM.C_USER CU 
		ON CE.ID_EMPLOYEE = CU.ID_EMPLOYEE
	WHERE CU.ID_BRANCH_PLANT = @V_ID_BRANCH_PLANT
	  AND CE.ID_BRANCH_PLANT = @V_ID_BRANCH_PLANT
	  AND CU.FG_ACTIVE = 1 
	  AND CE.FG_ACTIVE = 1 

END

