-- ================================================================
-- Proyecto: Plaskolite v2
-- Copyright (c) - Vitek - 2020
-- Author: Cynthia Aideé Alvarez.
-- CREATE date: 06/25/2020
-- Description: GET_CALIBRATION_DATA 
-- =================================================================
create PROCEDURE [PRD].[SPE_GET_CALIBRATION_DATA]
	@PIN_ID_WORK_ORDER AS INT = NULL,
	@PIN_ID_QA27 AS INT = NULL,
	@PIN_FG_OPERATOR AS NVARCHAR(40) = NULL
AS

	SELECT ID_CALIBRATION, TAPE_NUMBER, TAPE_VALUE, MICROMETER, FIRST_VALUE, SECOND_VALUE, THIRD_VALUE FROM PRD.K_CALIBRATION WHERE
	(@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND ID_WORK_ORDER = @PIN_ID_WORK_ORDER)) AND 
			 (@PIN_ID_QA27 IS NULL OR (@PIN_ID_QA27 IS NOT NULL AND ID_QA27 = @PIN_ID_QA27)) AND
			 (@PIN_FG_OPERATOR IS NULL OR (@PIN_FG_OPERATOR IS NOT NULL AND FG_OPERATOR = @PIN_FG_OPERATOR))

	--		  ID_WORK_ORDER = @PIN_ID_WORK_ORDER
	--OR ID_QA27 = @PIN_ID_WORK_ORDER  OR FG_OPERATOR = @PIN_FG_OPERATOR

	