-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Javier Diaz Barron
-- CREATE date: 04/05/2017
-- Description: get the metrics catalog
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_INSERT_LOG] 
	 @XML_RESULT XML = '' OUT     -- --0 TO ERROR AND 1 TO CORRECT
	,@LOG_TYPE NVARCHAR(50)
	,@DS_LOG NVARCHAR(1000)	
	,@XML_REFERENCE XML
	,@ID_BRANCH_PLANT INT
	,@KY_USER_APP NVARCHAR (50)
	,@NM_PROGAM NVARCHAR (50)
	,@PIN_TYPE_TRANSACTION CHAR(1) --I--> INSERT U -->  UPDATE

AS   
BEGIN
----WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE
	DECLARE @V_EXIST_TRAN BIT = 0
	,@CFE_SISTEMA DATETIME = GETDATE()

	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1
		END	
		--WE VERIFY IF THE SPE IS GOING TO EXECUTE A UPDATE OR INSERT
		IF @PIN_TYPE_TRANSACTION = 'I'-- AND @KY_USER_APP != 'MODBUS'
	    BEGIN
			--WE INSERT THE REGISTER ON THE TABLE  ADM.C_DEPARTMENT
			
			INSERT INTO PRD.K_LOG (LOG_TYPE,DS_LOG,XML_REFERENCE,ID_BRANCH_PLANT,DT_CREATION,KY_USER_APP_CREATION,NM_PROGAM_CREATE)
			SELECT
				 @LOG_TYPE 
				,@DS_LOG
				,@XML_REFERENCE
				,@ID_BRANCH_PLANT
				,GETDATE()
				,@KY_USER_APP	
				,@NM_PROGAM

		END 
		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = 	 ERROR_MESSAGE()
	
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		
			
	END CATCH
END

