-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 30/06/2017
-- Description: get forms TO Stack Light Unit
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_FORMS_BY_PRODUCTION_LINE] 		 
	 @PIN_ID_PRODUCTION_LINE INT = NULL 
	,@PIN_ID_K_FORM INT = NULL ,
	 @PIN_KY_PROCESS NVARCHAR(20) = NULL 

AS

SELECT 
	KF.ID_K_FORM,
	KF.ID_FORM,
	NULL AS ID_WORK_ORDER,
	KF.ID_PRODUCTION_LINE,
	NULL AS ID_QA27,
	KF.KY_STATUS_FORM,
	VCP.KY_PROCESS
	FROM PRD.K_FORM KF
		INNER JOIN PRD.C_FORM CF ON CF.ID_FORM = KF.ID_FORM
		--INNER JOIN PRD.K_WORK_ORDER WO ON WO.ID_WORK_ORDER = KF.ID_WORK_ORDER
		--INNER JOIN PRD.K_QA27 QA ON QA.ID_QA27 = KF.ID_QA27
		INNER JOIN ADM.VW_C_PROCESS  VCP ON VCP.KY_PROCESS = CF.KY_PROCESS
		INNER JOIN ADM.VW_C_DATA_ACQUISITION_ORIGIN DA ON DA.ID_DATA_ACQUISITION_ORIGIN =CF.ID_DATA_ACQUISITION_ORIGIN
		WHERE (@PIN_KY_PROCESS IS NULL OR  (@PIN_KY_PROCESS  IS NOT NULL AND VCP.KY_PROCESS =@PIN_KY_PROCESS ))
		AND KF.KY_STATUS_FORM  <> 'CAPTURED'

