-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 06/03/2017
-- Description: Get all Stack Light Unit status.
-- =============================================
-- =============================================


CREATE PROCEDURE    [PRD].[SPE_GET_STACK_LIGHT_UNIT_STATUS] 
	    @PIN_ID_PRODUCTION_LINE AS int = NULL,
		@PIN_ID_WORK_ORDER AS int = NULL,
		@PIN_ID_QA27 AS int = NULL
AS   
   SELECT  distinct
  T1.ID_PRODUCTION_LINE,
  T1.KY_PRODUCTION_LINE,
  T1.NM_PRODUCTION_LINE,
  T1.[FG_STACK_LIGHT_ENABLED],
  T1.[NO_IP],
  T1.[NO_PORT],
  T1.[NO_GREEN_REGISTER],
  T1.[NO_RED_REGISTER],
  T1.[NO_YELLOW_REGISTER],
  T1.[NO_GRAY_REGISTER],
  T1.ID_WORK_ORDER,
  T1.ID_QA27,
  CASE WHEN (T1.FG_LOST_TIME_EVENT + T1.FG_LOST_TIME_EVENT_ATTENDED
  --+NO_FORMS
  ) >0 THEN 0 ELSE 1 END AS FG_ALL_FINE ,
  T1.FG_LOST_TIME_EVENT,
  T1.FG_LOST_TIME_EVENT_ATTENDED,
  CASE WHEN T1.NO_FORMS  >0 THEN 1 ELSE 0 END AS FG_FORM
   FROM
  (  
  SELECT 
  PL.ID_PRODUCTION_LINE,
  PL.KY_PRODUCTION_LINE,
  PL.NM_PRODUCTION_LINE,
  PL.[FG_STACK_LIGHT_ENABLED],
  PL.[NO_IP],
  PL.[NO_PORT],
  PL.[NO_GREEN_REGISTER],
  PL.[NO_RED_REGISTER],
  PL.[NO_YELLOW_REGISTER],
  PL.[NO_GRAY_REGISTER],
  ISNULL(WO.ID_WORK_ORDER,0) AS ID_WORK_ORDER,
  ISNULL(QA.ID_QA27,0) AS ID_QA27,
  CASE WHEN I.KY_STATUS ='CREATED' THEN 1 ELSE 0 END AS FG_LOST_TIME_EVENT,
  CASE WHEN I.KY_STATUS IN ('CHANGE_SHIFT','HOLD_ON') THEN 1 ELSE 0 END AS FG_LOST_TIME_EVENT_ATTENDED,
  ISNULL(F.NO_FORMS,0) AS NO_FORMS
  FROM [PRD].[C_PRODUCTION_LINE] PL
  LEFT OUTER JOIN (SELECT top 1 * FROM PRD.K_WORK_ORDER  WHERE KY_STATUS= 'RUNNING') WO ON WO.ID_PRODUCTION_LINE = PL.ID_PRODUCTION_LINE
  LEFT OUTER JOIN (SELECT * FROM PRD.K_QA27 WHERE KY_STATUS = 'RUNNING') QA ON QA.ID_WORK_ORDER = WO.ID_WORK_ORDER
  LEFT OUTER JOIN (SELECT * FROM PRD.K_ISSUE WHERE KY_STATUS <> 'CLOSED') I ON (I.ID_WORK_ORDER = WO.ID_WORK_ORDER AND I.ID_QA27 = QA.ID_QA27)
  LEFT OUTER JOIN (SELECT ID_PRODUCTION_LINE, COUNT(*) AS NO_FORMS FROM PRD.K_FORM WHERE KY_STATUS_FORM   <> 'CAPTURED' GROUP BY ID_PRODUCTION_LINE UNION ALL
				   SELECT WO.ID_PRODUCTION_LINE,COUNT(*) AS NO_FORMS FROM PRD.K_FORM KF
				   INNER JOIN PRD.K_WORK_ORDER WO ON KF.ID_WORK_ORDER  =WO.ID_WORK_ORDER WHERE KF.KY_STATUS_FORM   <> 'CAPTURED' 
				   GROUP BY WO.ID_PRODUCTION_LINE ) F ON (F.ID_PRODUCTION_LINE = PL.ID_PRODUCTION_LINE) 
  ) T1
	WHERE (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND T1.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE)) AND 
			(@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND T1.ID_WORK_ORDER = @PIN_ID_WORK_ORDER)) AND 
			(@PIN_ID_QA27 IS NULL OR (@PIN_ID_QA27 IS NOT NULL AND T1.ID_QA27 = @PIN_ID_QA27))

ORDER BY T1.ID_PRODUCTION_LINE



--EXECUTE [PRD].[SPE_GET_STACK_LIGHT_UNIT_STATUS]  NULL,NULL,NULL

--SELECT * FROM PRD.K_FORM

