-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 28/03/2017
-- Description: get all USERS SCALING
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_USERS_SCALING] 
		@PIN_ID_AUTHORIZED_USER_CODE AS INT = NULL,
		@PIN_ID_PROBLEM_CODE AS INT = NULL,
		@PIN_ID_FORM AS INT = NULL,
		@PIN_NM_FORM AS VARCHAR(50) = NULL,
		@PIN_KY_USER AS VARCHAR(50) = NULL,
		@PIN_KY_LEVEL_TYPE AS VARCHAR(10) = NULL,
		@PIN_NO_TIME_HOLD_ON AS INT = NULL


AS   
	SELECT KUS.ID_AUTHORIZED_USER_CODE,
		   KUS.ID_PROBLEM_CODE,
		   KUS.ID_FORM, 
		   CF.NM_FORM,
		   KUS.KY_USER,
		   CE.ID_EMPLOYEE,
		   CE.NM_FIRST_NAME NM_USER, 
		   KUS.KY_LEVEL_TYPE,
		   KUS.NO_TIME_HOLD_ON
		
		FROM PRD.K_USERS_SCALING KUS
		JOIN PRD.C_FORM CF ON KUS.ID_FORM = CF.ID_FORM
		JOIN ADM.C_USER CU ON KUS.KY_USER = CU.KY_USER
		JOIN ADM.C_EMPLOYEE CE ON CU.ID_EMPLOYEE = CE.ID_EMPLOYEE
					
  	   WHERE (@PIN_ID_AUTHORIZED_USER_CODE IS NULL OR (@PIN_ID_AUTHORIZED_USER_CODE IS NOT NULL AND KUS.ID_AUTHORIZED_USER_CODE = @PIN_ID_AUTHORIZED_USER_CODE)) AND 
			 (@PIN_ID_PROBLEM_CODE IS NULL OR (@PIN_ID_PROBLEM_CODE IS NOT NULL AND KUS.ID_PROBLEM_CODE = @PIN_ID_PROBLEM_CODE)) AND
			 (@PIN_ID_FORM IS NULL OR (@PIN_ID_FORM IS NOT NULL AND KUS.ID_FORM = @PIN_ID_FORM)) AND
			 (@PIN_NM_FORM IS NULL OR (@PIN_NM_FORM IS NOT NULL AND CF.NM_FORM = @PIN_NM_FORM)) AND
			 (@PIN_KY_LEVEL_TYPE IS NULL OR (@PIN_KY_LEVEL_TYPE IS NOT NULL AND KUS.KY_LEVEL_TYPE = @PIN_KY_LEVEL_TYPE)) AND
			 (@PIN_KY_USER IS NULL OR (@PIN_KY_USER IS NOT NULL AND KUS.KY_USER = @PIN_KY_USER)) AND
			 (@PIN_KY_LEVEL_TYPE IS NULL OR (@PIN_KY_LEVEL_TYPE IS NOT NULL AND KUS.KY_LEVEL_TYPE = @PIN_KY_LEVEL_TYPE)) AND
			 (@PIN_NO_TIME_HOLD_ON IS NULL OR (@PIN_NO_TIME_HOLD_ON IS NOT NULL AND KUS.NO_TIME_HOLD_ON = @PIN_NO_TIME_HOLD_ON))

ORDER BY KUS.KY_LEVEL_TYPE

