

-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - VITEk - 2019
-- Author: DELLC
-- CREATE date: 07/19/2019
-- Description: REPORT SKIPPED WORK ORDER 
-- =============================================[ADM].[SPE_GET_USER_CATALOGUES]
CREATE PROCEDURE    [PRD].[SPE_GET_RPT_SKIPPED_WORK_ORDER]
	@PIN_ID_BRANCH_PLANT AS int ,
	@PIN_DT_INITIAL AS DATE, 
	@PIN_DT_FINAL AS DATE 
	
AS   
BEGIN


SELECT 
 SWL.DT_CREATION,
 Q.ID_WORK_ORDER,
 SUBSTRING(SH.KY_SHIFT_TIME , 4,1) AS [SHIFT],
 W.ID_PRODUCTION_LINE,
 w.NM_PRODUCTION_LINE,
 Q.NM_LEADMAN,
 W.ID_ITEM,
 W.NM_ITEM,
 W.NO_RUN_QTY AS RUN_QTY,
 W.NO_POUNDS * W.NO_QTY_SKID AS RUN_LBS,
PC.KY_PROBLEM_CODE+' / '+PA.DS_PROBLEM_AREA+' / '+ PC.NM_PROBLEM_CODE AS CODE,
SWL.DS_EXPLANATION,
SWL.KY_AUTHORIZER_USER
FROM PRD.K_QA27 Q
INNER JOIN PRD.K_SKIPPED_WORK_ORDER_LOG SWL ON  Q.ID_QA27= SWL.ID_QA27 AND Q.ID_WORK_ORDER=SWL.ID_WORK_ORDER
INNER JOIN PRD.K_WORK_ORDER W ON Q.ID_WORK_ORDER=W.ID_WORK_ORDER 
INNER JOIN PRD.K_SHIFT SH ON Q.ID_SHIFT=SH.ID_SHIFT
INNER JOIN PRD.K_ISSUE I ON I.ID_ISSUE=SWL.ID_ISSUE
INNER JOIN PRD.C_PROBLEM_AREA PA ON I.ID_PROBLEM_AREA = PA.ID_PROBLEM_AREA
INNER JOIN PRD.C_PROBLEM_CODE  PC ON I.ID_PROBLEM_CODE=PC.ID_PROBLEM_CODE 
 

WHERE 

(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND W.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
AND  ( (@PIN_DT_INITIAL IS NULL AND @PIN_DT_FINAL IS NULL ) OR  CAST(SWL.DT_CREATION AS DATE) BETWEEN @PIN_DT_INITIAL AND  @PIN_DT_FINAL)

END

