-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 09/11/2017
-- Description: Get Production lines from JDEdwards
-- =============================================
CREATE PROCEDURE  [PRD].[SPE_GET_PRODUCTION_LINES_JDEDWARDS] 
	@PIN_ID_BRANCH_PLANT INT
AS  
BEGIN
	DECLARE @ID_BRANCH_PLANT NVARCHAR(10) = SUBSTRING((SELECT TOP 1 KY_BRANCH_PLANT FROM ADM.C_BRANCH_PLANT WHERE ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT),3,2) 
	
	PRINT(@ID_BRANCH_PLANT)

		 SELECT  CAST (PL.ABAN8 AS INT) AS ID_PRODUCTION_LINE
		, LTRIM(RTRIM(PL.ABALPH)) AS NM_PRODUCTION_LINE
		, LTRIM(RTRIM(PL.ABDC)) AS DS_PRODUCTION_LINE FROM 
	OPENQUERY(JDEPROD, 'SELECT * FROM PRODDTA.F0101 PLX
		WHERE PLX.ABAT1 = ''WC''') PL  WHERE  SUBSTRING( CAST(CAST(PL.ABAN8 AS INT) AS VARCHAR(8)),2,2) = @ID_BRANCH_PLANT




	
END
