-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 13/03/2017
-- Description: get all Device catalogs
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_DEVICE_CATALOGS] 
	    @PIN_ID_DEVICE AS int = NULL,
	    @PIN_ID_BRANCH_PLANT AS int = NULL
		
AS   
	BEGIN
	DECLARE 
        @PIN_KY_DEVICE AS nvarchar(50) = NULL,
        @PIN_NM_DEVICE AS nvarchar(100) = NULL,
        @PIN_DS_DEVICE AS nvarchar(300) = NULL,
	    --@PIN_ID_PRODUCTION_LINE AS int = NULL,
        @PIN_NO_IP AS nvarchar(50)= NULL,
        @PIN_NO_PORT AS nvarchar(10) = NULL,
        @PIN_FG_ACTIVE AS BIT = NULL

		  ,@XML_BRANCHPLANTS AS XML
		  ,@XML_PRODUCTION_LINES AS XML
		  ,@XML_DEVICE_METRICS AS XML
		  ,@XML_MODBUS_DATATYPE AS XML
		  ,@XML_CATALOGS AS XML


		SET @XML_BRANCHPLANTS = (
		SELECT 	    
	    BP.ID_BRANCH_PLANT  AS "@ID_BRANCH_PLANT",
        BP.KY_BRANCH_PLANT  AS "@KY_BRANCH_PLANT",
        BP.NM_BRANCH_PLANT  AS "@NM_BRANCH_PLANT",
        BP.DS_BRANCH_PLANT  AS "@DS_BRANCH_PLANT",
        BP.ID_FILE  AS "@ID_FILE"
		FROM ADM.C_BRANCH_PLANT BP
		FOR XML PATH ('BRANCHPLANT'), ROOT ('BRANCHPLANTS')
	)

	--	SET @XML_PRODUCTION_LINES = (
	--	SELECT 	    
	--    PL.ID_PRODUCTION_LINE  AS "@ID_PRODUCTION_LINE",
 --       PL.KY_PRODUCTION_LINE  AS "@KY_PRODUCTION_LINE",
 --       PL.NM_PRODUCTION_LINE  AS "@NM_PRODUCTION_LINE",
 --       PL.DS_PRODUCTION_LINE  AS "@DS_PRODUCTION_LINE",
 --       PL.FG_ACTIVE  AS "@FG_ACTIVE",
 --       PL.ID_PRODUCTION_LINE_TYPE  AS "@ID_PRODUCTION_LINE_TYPE",
 --       PL.ID_BRANCH_PLANT  AS "@ID_BRANCH_PLANT",
	--	VW.NM_PRODUCTION_LINE_TYPE AS "@NM_PRODUCTION_LINE_TYPE"
	--	FROM PRD.C_PRODUCTION_LINE PL
	--		JOIN ADM.VW_S_PRODUCTION_LINE_TYPE VW ON PL.ID_PRODUCTION_LINE_TYPE = VW.ID_PRODUCTION_LINE_TYPE
	--		WHERE 
	--		(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND (PL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT  OR PL.ID_BRANCH_PLANT IS NULL))) 
	--	FOR XML PATH ('PRODUCTION_LINE'), ROOT ('PRODUCTION_LINES')
	--)

	    SET @XML_DEVICE_METRICS = (
		SELECT 	    
	    PM.ID_DEVICE_METRICS  AS "@ID_DEVICE_METRICS",
	    NEWID()  AS "@ID_ASSISTANT",
        PM.ID_DEVICE  AS "@ID_DEVICE",
        PM.ID_METRICS  AS "@ID_METRICS",
        CM.KY_METRICS  AS "@KY_METRICS",
        CM.NM_METRICS  AS "@NM_METRICS",
        PM.NO_REGISTER  AS "@NO_REGISTER",
        PM.KY_MODBUS_DATATYPE  AS "@KY_MODBUS_DATATYPE",
		VWMD.NM_MODBUS_DATATYPE AS "@NM_MODBUS_DATATYPE"
      ,	 PM.[KY_SCALING_TYPE] AS "@KY_SCALING_TYPE"
	  ,	 VST.[NM_SCALING_TYPE] AS "@NM_SCALING_TYPE"
	  ,	 PM.[NO_RAW_HI] AS "@NO_RAW_HI"
      ,  PM.[NO_RAW_LO] AS  "@NO_RAW_LO"
      ,  PM.[NO_SCALE_HI] AS "@NO_SCALE_HI"
      ,  PM.[NO_SCALE_LO] AS "@NO_SCALE_LO"
      ,  PM.[FG_CLAMP_HI] AS "@FG_CLAMP_HI"
      ,  PM.[FG_CLAMP_LO] AS "@FG_CLAMP_LO"
		FROM PRD.C_DEVICE_METRICS PM
			LEFT OUTER JOIN ADM.VW_C_MODBUS_DATATYPE VWMD ON VWMD.KY_MODBUS_DATATYPE = PM.KY_MODBUS_DATATYPE
			LEFT OUTER JOIN [ADM].[VW_SCALING_TYPE] VST ON VST.KY_SCALING_TYPE= PM.KY_SCALING_TYPE
			LEFT OUTER JOIN PRD.C_METRICS CM ON CM.ID_METRICS = PM.ID_METRICS
			WHERE PM.ID_DEVICE = @PIN_ID_DEVICE
		FOR XML PATH ('DEVICE_METRIC'), ROOT ('DEVICE_METRICS')
	)

	  SET @XML_MODBUS_DATATYPE = (
		SELECT 	    
        KY_MODBUS_DATATYPE  AS "@KY_MODBUS_DATATYPE",
        NM_MODBUS_DATATYPE  AS "@NM_MODBUS_DATATYPE"
		FROM ADM.VW_C_MODBUS_DATATYPE
		FOR XML PATH ('MODBUS_DATATYPE'), ROOT ('MODBUS_DATATYPES')
	)

	    SET @XML_CATALOGS = (
		SELECT 
			@XML_BRANCHPLANTS,
			@XML_PRODUCTION_LINES,
			@XML_DEVICE_METRICS,
			@XML_MODBUS_DATATYPE
		FOR XML PATH ('CATALOGS')
	)

		SELECT 
		@PIN_KY_DEVICE =PL.[KY_DEVICE],
		@PIN_NM_DEVICE =PL.[NM_DEVICE],
		@PIN_DS_DEVICE =PL.[DS_DEVICE],
		--@PIN_ID_PRODUCTION_LINE =PL.[ID_PRODUCTION_LINE],
		@PIN_ID_BRANCH_PLANT=PL.[ID_BRANCH_PLANT],
		@PIN_NO_IP =PL.[NO_IP],
		@PIN_NO_PORT =PL.[NO_PORT],
		@PIN_FG_ACTIVE =PL.[FG_ACTIVE]
		FROM [PRD].[C_DEVICE] PL
		LEFT OUTER JOIN ADM.C_BRANCH_PLANT BP ON PL.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
			WHERE PL.ID_DEVICE = @PIN_ID_DEVICE


		SELECT  @PIN_ID_DEVICE AS ID_DEVICE,
			    @PIN_KY_DEVICE AS KY_DEVICE,
			    @PIN_NM_DEVICE AS NM_DEVICE,
				@PIN_DS_DEVICE AS DS_DEVICE,
				--@PIN_ID_PRODUCTION_LINE AS ID_PRODUCTION_LINE,
				@PIN_ID_BRANCH_PLANT AS ID_BRANCH_PLANT,
				@PIN_NO_IP AS NO_IP,
				@PIN_NO_PORT AS NO_PORT,
				@PIN_FG_ACTIVE AS FG_ACTIVE,
			    @XML_CATALOGS AS XML_CATALOGS
END

