-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez Torres
-- CRETAE date: 02/06/2018
-- Description: Delete a scheduling work order
-- =============================================
-- MODIFY: JCTC - add delete sentense to work order trasition table
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_DELETE_WORK_ORDER_SCHEDULED] 
	 @XML_RESULT XML = '' OUT     -- --0 TO ERROR AND 1 TO CORRECT
	,@PIN_ID_WORK_ORDER INT = NULL
	,@KY_USER_APP_CREATION NVARCHAR(50) = NULL
	,@NM_PROGAM_CREATE NVARCHAR(50)  = NULL
	
AS 
BEGIN  
	----WE DECLARE THE STARTED VARIABLE THAT INDICATES IF WE WILL HAVE A TRANSACTION ON SPE

	DECLARE @V_EXIST_TRAN BIT = 0
		, @DT_SYSTEM DATETIME = GETDATE()
		, @V_ERROR NVARCHAR(300) = NULL

   	BEGIN TRY
		--WE VERIFY THAT EXISTS A WORKING TRANSACTION
		IF (@@TRANCOUNT = 0) BEGIN
			--IN CASE THAT THE TRANSACTION DOESNT START
			BEGIN TRANSACTION 
			--IT EDITS THE VARIABLE THAT INDICATES THAT THE TRANSACTION START IN THIS BLOCK TO CANCEL IN ANY MOMENT
			SET @V_EXIST_TRAN = 1

		END	

		DELETE FROM PRD.K_WORK_ORDER_COMMENT WHERE ID_WORK_ORDER = @PIN_ID_WORK_ORDER; ----*****JCTC

		DELETE FROM PRD.K_WORK_ORDER_TRANSITIONS WHERE ID_WORK_ORDER = @PIN_ID_WORK_ORDER;  ----*****JCTC

		DELETE FROM PRD.K_WORK_ORDER WHERE ID_WORK_ORDER = @PIN_ID_WORK_ORDER AND KY_STATUS = 'SCHEDULED';


		-- WE BACK A RETURN VARIABLE THAT INDICATES ALL WAS PERFORMED OKAY 
		SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
		SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
		--SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, CAST(@ID_SCALING AS NVARCHAR), 'ID_SCALING')

		-- IF THERE IS A TRANSACTION IN THIS BLOCK, IT WILL BE ERASED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	

	END TRY
	BEGIN CATCH		
		--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTIO GET CANCELED
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
			
		DECLARE @KY_ERROR INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MESSAGE NVARCHAR(250)  = 	 ERROR_MESSAGE()			
	    SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al procesar el registro')
		SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error processing the register')
		
			
	END CATCH
END

