-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 13/03/2017
-- Description: get all problem area catalogs
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_PROBLEM_AREA_CATALOGS] 
	    @PIN_ID_PROBLEM_AREA AS int = NULL

AS   
	BEGIN
	DECLARE 
        @PIN_KY_PROBLEM_AREA AS nvarchar(50) = NULL,
        @PIN_NM_PROBLEM_AREA AS nvarchar(100) = NULL,
        @PIN_DS_PROBLEM_AREA AS nvarchar(1000) = NULL,
        @PIN_FG_ACTIVE AS BIT = NULL,
        @PIN_ID_BRANCH_PLANT AS INT = NULL
		  ,@XML_BRANCHPLANTS AS XML
		  ,@XML_CATALOGS AS XML



		SET @XML_BRANCHPLANTS = (
		SELECT 	    
	    BP.ID_BRANCH_PLANT  AS "@ID_BRANCH_PLANT",
        BP.KY_BRANCH_PLANT  AS "@KY_BRANCH_PLANT",
        BP.NM_BRANCH_PLANT  AS "@NM_BRANCH_PLANT",
        BP.DS_BRANCH_PLANT  AS "@DS_BRANCH_PLANT",
        BP.ID_FILE  AS "@ID_FILE"
		FROM ADM.C_BRANCH_PLANT BP
		ORDER BY BP.KY_BRANCH_PLANT
		--WHERE (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND BP.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
		FOR XML PATH ('BRANCHPLANT'), ROOT ('BRANCHPLANTS')
	)


	       SET @XML_CATALOGS = (
		SELECT 
			@XML_BRANCHPLANTS
		FOR XML PATH ('CATALOGS')
	)

		SELECT 
		@PIN_KY_PROBLEM_AREA =PA.[KY_PROBLEM_AREA],
		@PIN_NM_PROBLEM_AREA =PA.[NM_PROBLEM_AREA],
		@PIN_DS_PROBLEM_AREA =PA.[DS_PROBLEM_AREA],
		@PIN_FG_ACTIVE=PA.[FG_ACTIVE],
		@PIN_ID_BRANCH_PLANT =PA.[ID_BRANCH_PLANT]
		FROM [PRD].[C_PROBLEM_AREA] PA
		LEFT OUTER JOIN ADM.C_BRANCH_PLANT BP ON PA.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
			WHERE PA.ID_PROBLEM_AREA = @PIN_ID_PROBLEM_AREA



		SELECT  @PIN_ID_PROBLEM_AREA AS ID_PROBLEM_AREA,
			    @PIN_KY_PROBLEM_AREA AS KY_PROBLEM_AREA,
				@PIN_NM_PROBLEM_AREA AS NM_PROBLEM_AREA,
				@PIN_DS_PROBLEM_AREA AS DS_PROBLEM_AREA,
				@PIN_FG_ACTIVE AS FG_ACTIVE,
				@PIN_ID_BRANCH_PLANT AS ID_BRANCH_PLANT,
			    @XML_CATALOGS AS XML_CATALOGS
END

