-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio César Tavares
-- CREATE date: 22/06/2018
-- Description: get all shift on course to change user
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_SHIFT_CHANGE_USER] 
	    @PIN_ID_SHIFT AS int = NULL,
        @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_KY_USER AS varchar(50) = NULL,
		@PIN_FG_STATUS AS bit = 1
AS

	DECLARE @V_DATE DATETIME = GETDATE()
		
		  SELECT KS.ID_SHIFT,
				KS.ID_PRODUCTION_LINE,
				PL.NM_PRODUCTION_LINE,
				KS.ID_BRANCH_PLANT,
				KS.KY_USER,
				CU.NM_USER,
				KS.FG_STATUS,
				KS.DT_SHIFT_HISTORY,
				KS.DT_END_SHIFT,
				KS.KY_SHIFT,
				KS.KY_SHIFT_TIME,
				WO.NO_WORK_ORDER,
				QA.ID_QA27,
				CASE WHEN @V_DATE BETWEEN KS.DT_START_SHIFT AND KS.DT_END_SHIFT THEN CONVERT(BIT,0) ELSE CONVERT(BIT,1) END FINISH_SHIFT
			  FROM PRD.K_SHIFT KS
			  JOIN ADM.VW_C_SHIFT VS ON KS.KY_SHIFT = VS.KY_SHIFT
			  JOIN ADM.C_USER CU ON KS.KY_USER = CU.KY_USER
			  JOIN PRD.C_PRODUCTION_LINE PL ON KS.ID_PRODUCTION_LINE =PL.ID_PRODUCTION_LINE
		 LEFT JOIN PRD.K_WORK_ORDER WO ON KS.ID_PRODUCTION_LINE = WO.ID_PRODUCTION_LINE AND WO.KY_STATUS = 'RUNNING'
		 LEFT JOIN PRD.K_QA27 QA ON WO.ID_WORK_ORDER = QA.ID_WORK_ORDER AND QA.KY_STATUS = 'RUNNING'
		     WHERE KS.FG_STATUS = @PIN_FG_STATUS AND 
				   KS.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT AND 
				   (@PIN_ID_SHIFT IS NULL OR (@PIN_ID_SHIFT IS NOT NULL AND KS.ID_SHIFT = @PIN_ID_SHIFT )) AND
				   (@PIN_KY_USER IS NULL OR (@PIN_KY_USER IS NOT NULL AND KS.KY_USER = @PIN_KY_USER )) AND
				   CASE WHEN @V_DATE BETWEEN KS.DT_START_SHIFT AND KS.DT_END_SHIFT THEN CONVERT(BIT,0) ELSE CONVERT(BIT,1) END = 0
		  ORDER BY PL.NM_PRODUCTION_LINE

