CREATE PROCEDURE    [PRD].[SPE_GET_DISTRIBUTION_LIST]

 @PIN_NM_DISTRIBUTION AS VARCHAR(100)=NULL,
 @PIN_ID_EVENT AS INT = NULL
 AS
SELECT ID_DISTRIBUTION_LIST,
		NM_DISTRIBUTION,
		KY_DISTRIBUTION,
		ID_TYPE_EVENT,
		KY_USER_APP_CREATION,
		KY_USER_APP_UPDATE,
		NM_PROGAM_CREATE,
		NM_PROGRAM_UPDATE 
FROM PRD.K_DISTRIBUTION_LIST
WHERE (@PIN_NM_DISTRIBUTION IS NULL OR (@PIN_NM_DISTRIBUTION IS NOT NULL AND NM_DISTRIBUTION = @PIN_NM_DISTRIBUTION)) AND
(@PIN_ID_EVENT IS NULL OR (@PIN_ID_EVENT IS NOT NULL AND ID_TYPE_EVENT = @PIN_ID_EVENT))

