-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Vitek - 2020
-- Author: Aideé Alvarez 
-- CREATE date: 04/10/2020
-- Description: get forms
-- =============================================
CREATE PROCEDURE [PRD].[SPE_GET_FORMS] 
		
		@PIN_ID_FORM AS INT = NULL,
		@PIN_NM_FORM AS VARCHAR(50) = NULL,
		@PIN_ID_BRANCH_PLANT AS INT = NULL
AS   
	SELECT 
		   CF.ID_FORM, 
		   CF.NM_FORM,
		   BP.NM_BRANCH_PLANT,
		   CF.NO_FREQUENCE,
		   CF.NO_SAMPLE,
		   CF.KY_SAMPLE_UNIT,
		   CF.ID_BRANCH_PLANT ID_BRANCH_PLANT_POSITION,
		   DAO.NM_DATA_ACQUISITION_ORIGIN,
		   CF.FG_ACTIVE --added
		
		FROM PRD.C_FORM  CF
	     JOIN ADM.C_BRANCH_PLANT BP ON CF.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
		 JOIN ADM.VW_C_DATA_ACQUISITION_ORIGIN DAO ON DAO.ID_DATA_ACQUISITION_ORIGIN = CF.ID_DATA_ACQUISITION_ORIGIN

  	   WHERE  
			 (@PIN_ID_FORM IS NULL OR (@PIN_ID_FORM IS NOT NULL AND CF.ID_FORM = @PIN_ID_FORM)) AND
			 (@PIN_NM_FORM IS NULL OR (@PIN_NM_FORM IS NOT NULL AND CF.NM_FORM = @PIN_NM_FORM)) AND
			 (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CF.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
ORDER BY CF.ID_FORM



