-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares
-- CREATE date: 09/07/2018
-- Description: get all users
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_ACTIVE_SHIFTS]
	@PIN_ID_SHIFT				AS INT = NULL
   ,@PIN_ID_PRODUCTION_LINE		AS INT = NULL
   ,@PIN_ID_BRANCH_PLANT		AS INT = NULL
   ,@PIN_KY_USER				AS NVARCHAR(50) = NULL
   ,@PIN_ID_QA27				AS INT = NULL
   ,@PIN_ID_WORK_ORDER			AS INT = NULL
AS   
	SELECT KS.ID_SHIFT	
		, KS.ID_PRODUCTION_LINE
		, KS.ID_BRANCH_PLANT
		, BP.NM_BRANCH_PLANT
		, KS.KY_USER
		, KS.DT_START_SHIFT
		, KS.DT_END_SHIFT
		, CASE WHEN GETDATE() BETWEEN KS.DT_START_SHIFT AND KS.DT_END_SHIFT THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS FG_CLOSE_SHIFT
		, QA.ID_QA27
		, QA.ID_WORK_ORDER
	FROM PRD.K_SHIFT KS
		LEFT JOIN PRD.K_QA27 QA 
			ON KS.ID_SHIFT = QA.ID_SHIFT 
			AND QA.KY_STATUS = 'RUNNING'
		INNER JOIN ADM.C_BRANCH_PLANT BP 
			ON KS.ID_BRANCH_PLANT = BP.ID_BRANCH_PLANT
	WHERE  KS.FG_STATUS = 1 
		AND (@PIN_ID_SHIFT IS NULL OR (@PIN_ID_SHIFT IS NOT NULL AND KS.ID_SHIFT = @PIN_ID_SHIFT))
		AND (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND KS.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE))
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND KS.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
		AND (@PIN_KY_USER IS NULL OR (@PIN_KY_USER IS NOT NULL AND KS.KY_USER = @PIN_KY_USER))
		AND (@PIN_ID_QA27 IS NULL OR (@PIN_ID_QA27 IS NOT NULL AND QA.ID_QA27 = @PIN_ID_QA27))
		AND (@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND QA.ID_WORK_ORDER = @PIN_ID_WORK_ORDER))

