-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Vitek - 2020
-- Author: Aideé Alvarez.
-- CREATE date: 01/06/2020
-- Description: Get SOC names by production line. 
-- =============================================	
CREATE PROCEDURE [PRD].[SPE_GET_SOC_NAME_PER_LINE]
@PIN_ID_PRODUCTION_LINE AS INT = NULL
	AS
	BEGIN
		SELECT CL.ID_LINE_METRIC, CL.ID_PRODUCTION_LINE, CM.ID_METRICS, CM.NM_METRICS,
		CL.XML_FIELD_SETTINGS.value('(SETTINGS/FIELD_TYPES/@CATALOG_VALUE)[1]', 'varchar(80)') AS NOMINAL,
		CL.XML_FIELD_SETTINGS.value('(SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]', 'varchar(80)') AS RANGE,
		CL.XML_FIELD_SETTINGS
		FROM PRD.C_LINE_METRIC CL
		INNER JOIN PRD.C_METRICS CM ON CM.ID_METRICS = CL.ID_METRICS
		INNER JOIN PRD.C_PRODUCTION_LINE CPL ON CPL.ID_PRODUCTION_LINE = CL.ID_PRODUCTION_LINE
		WHERE CPL.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE
	END
