-- ================================================================
-- Proyecto: Plaskolite v2
-- Copyright (c) - Vitek - 2020
-- Author: Cynthia Aideé Alvarez.
-- CREATE date: 01/15/2020
-- Description: UPDATE LINE OPERATOR IN THE PAPER COPY.
-- =================================================================
CREATE PROCEDURE   [PRD].[SPE_UPDATE_LINE_OPERATOR]
	@XML_RESULT        XML  = '' OUT,
	@PIN_LINE_OPERATOR AS VARCHAR(80) = NULL,
	@PIN_ID_QA27       AS INT = NULL
AS
BEGIN
		DECLARE @V_EXIST_TRAN BIT = 0
		BEGIN TRY
		-- VERIFY THAT EXIST A TRANSACTION.
		IF (@@TRANCOUNT = 0)
			BEGIN
			-- IN CASE THAT THE TRANSACTION DOESN'T WORK, WE INITIALIZE THE VARIABLE.
				BEGIN TRANSACTION 
					SET @V_EXIST_TRAN = 1
			END
			-- UPDATE LINE OPERATOR BY QA27.
			BEGIN
			UPDATE PRD.K_QA27 SET LINE_OPERATOR = @PIN_LINE_OPERATOR WHERE ID_QA27  = @PIN_ID_QA27
			END
			SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, 1, 'SUCCESSFUL')
			SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Proceso exitoso', 'ES')
			SET @XML_RESULT = DBO.F_ERROR_INSERT_MESSAGES(@XML_RESULT, 'Successful Process', 'EN')
				
			IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
				COMMIT	
			END TRY
				BEGIN CATCH		
				--IF IT OCCURS A ERROR IN THIS BLOCK THE TRANSACTION GET CANCELED
				IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
					ROLLBACK

				DECLARE @KY_ERROR INT				  = ERROR_NUMBER()
				DECLARE @ERROR_MESSAGE NVARCHAR(250)  = ERROR_MESSAGE()
	
				SET @XML_RESULT = DBO.F_ERROR_CREATE_HEADER( @@ROWCOUNT, @KY_ERROR, 'ERROR')
				SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR,'Ocurrió un error al actualizar al line operator.')
				SET @XML_RESULT = DBO.F_ERROR_MESSAGES( @KY_ERROR, 'There was an error to update line operator.')	
			END CATCH
END
