-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Martin Sánchez
-- CREATE date: 06/03/2017
-- Description: Get all production line.
-- =============================================
-- 2017 03 31 JDR It is changed to a left join with the table of plants
-- 2017 03 31 JDR It is changed to return all record where Branch Plant Id field is null
-- 2018 03 11 JDR Last captured form date & time column added
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_PRODUCTION_LINE] 
	    @PIN_ID_PRODUCTION_LINE AS int = NULL,
        @PIN_KY_PRODUCTION_LINE AS nvarchar(50) = NULL,
        @PIN_NM_PRODUCTION_LINE AS nvarchar(300) = NULL,
		@PIN_DS_PRODUCTION_LINE AS nvarchar(500) = NULL,
		@PIN_ID_PRODUCTION_LINE_TYPE AS int = NULL,
		@PIN_NM_PRODUCTION_LINE_TYPE AS nvarchar(11) =	NULL,
		@PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_FG_ACTIVE AS BIT = NULL

AS   
BEGIN
	
	DECLARE @DT_LAST_FORM DATETIME
	
	IF @PIN_ID_PRODUCTION_LINE IS NOT NULL BEGIN
		SET @DT_LAST_FORM = (SELECT TOP 1 DT_FORM FROM PRD.K_FORM KF WHERE KF.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE AND DT_CLOSED IS NOT NULL)
	END

	SELECT PL.ID_PRODUCTION_LINE
		, PL.KY_PRODUCTION_LINE
		, PL.NM_PRODUCTION_LINE
		, PL.DS_PRODUCTION_LINE
		, PL.FG_ACTIVE
		, PL.ID_PRODUCTION_LINE_TYPE
		, PL.ID_BRANCH_PLANT
		, PL.DT_CREATION
		, ISNULL(CP.NM_BRANCH_PLANT, 'All') AS NM_BRANCH_PLANT
		, ISNULL(CP.KY_BRANCH_PLANT, 'All') KY_BRANCH_PLANT
		, VW.KY_PRODUCTION_LINE_TYPE
		, VW.NM_PRODUCTION_LINE_TYPE
		, PL.NO_POUNDS_PER_HOUR
		, PL.FG_STACK_LIGHT_ENABLED
		, PL.NO_IP
		, PL.NO_PORT
		, PL.NO_GREEN_REGISTER
		, PL.NO_RED_REGISTER
		, PL.NO_YELLOW_REGISTER
		, PL.NO_GRAY_REGISTER
		, @DT_LAST_FORM AS DT_LAST_FORM
		, '' AS KY_USER_ACTIVE_LINE
		, '' AS NO_IP_CONFIGURED
		--, KS.KY_USER KY_USER_ACTIVE_LINE
		--, IP_PL.NO_IP AS NO_IP_CONFIGURED
	FROM PRD.C_PRODUCTION_LINE PL
		INNER JOIN ADM.VW_S_PRODUCTION_LINE_TYPE VW 
			ON PL.ID_PRODUCTION_LINE_TYPE = VW.ID_PRODUCTION_LINE_TYPE
		LEFT JOIN ADM.C_BRANCH_PLANT CP 
			ON PL.ID_BRANCH_PLANT = CP.ID_BRANCH_PLANT
		--LEFT JOIN PRD.K_SHIFT KS 
		--	ON PL.ID_PRODUCTION_LINE = KS.ID_PRODUCTION_LINE AND KS.FG_STATUS = 1
		--LEFT JOIN (
		--	SELECT ID_PRODUCTION_LINE
		--		  ,NO_IP
		--		  , ROW_NUMBER() OVER (PARTITION BY PIP.ID_PRODUCTION_LINE ORDER BY PIP.ID_PRODUCTION_LINE DESC) AS  ROW_WO
		--	FROM PRD.C_PRODUCTION_LINE_IP PIP
		--)IP_PL ON PL.ID_PRODUCTION_LINE = IP_PL.ID_PRODUCTION_LINE AND IP_PL.ROW_WO = 1
	WHERE (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND PL.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE)) AND 
			(@PIN_KY_PRODUCTION_LINE IS NULL OR (@PIN_KY_PRODUCTION_LINE IS NOT NULL AND PL.KY_PRODUCTION_LINE = @PIN_KY_PRODUCTION_LINE)) AND 
			(@PIN_NM_PRODUCTION_LINE IS NULL OR (@PIN_NM_PRODUCTION_LINE IS NOT NULL AND PL.NM_PRODUCTION_LINE = @PIN_NM_PRODUCTION_LINE)) AND 
    		(@PIN_DS_PRODUCTION_LINE IS NULL OR (@PIN_DS_PRODUCTION_LINE IS NOT NULL AND PL.DS_PRODUCTION_LINE = @PIN_DS_PRODUCTION_LINE)) AND
			(@PIN_NM_PRODUCTION_LINE_TYPE IS NULL OR (@PIN_NM_PRODUCTION_LINE_TYPE IS NOT NULL AND VW.NM_PRODUCTION_LINE_TYPE = @PIN_ID_PRODUCTION_LINE_TYPE)) AND  
			(@PIN_ID_PRODUCTION_LINE_TYPE IS NULL OR (@PIN_ID_PRODUCTION_LINE_TYPE IS NOT NULL AND PL.ID_PRODUCTION_LINE_TYPE = @PIN_ID_PRODUCTION_LINE_TYPE)) AND
			(@PIN_ID_BRANCH_PLANT IS NULL OR PL.ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND PL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT)) AND
			(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND PL.FG_ACTIVE = @PIN_FG_ACTIVE))

	ORDER BY PL.NM_PRODUCTION_LINE

END

