-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 05/25/2017
-- Description: Get transitions
-- =============================================
-- 12/28/2018 JDR FG_IS_TOOL_CHANGE and KY_IS_TOOL_CHANGE columns added
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_TRANSITIONS] 
	@PIN_ID_TRANSITION INT
	, @PIN_KY_TRANSITION NVARCHAR(50)
	, @PIN_NB_TRANSITION NVARCHAR(100)
	, @PIN_FG_ACTIVE BIT
	, @PIN_ID_BRANCH_PLANT int

AS

SELECT ID_TRANSITION
	, KY_TRANSITION
	, NM_TRANSITION
	, DS_TRANSITION
	, NO_STANDARD_TIME
	, [ID_BRANCH_PLANT]
	, FG_ACTIVE
	, FG_ACTIVE AS KY_ACTIVE
	, CASE WHEN FG_IS_TOOL_CHANGE = NULL THEN 0 ELSE FG_IS_TOOL_CHANGE END as FG_IS_TOOL_CHANGE
	, CASE WHEN FG_IS_TOOL_CHANGE = 1 THEN 'Yes' ELSE 'No' END AS KY_IS_TOOL_CHANGE
FROM PRD.C_TRANSITION
WHERE (@PIN_ID_TRANSITION IS NULL OR (@PIN_ID_TRANSITION IS NOT NULL AND ID_TRANSITION = @PIN_ID_TRANSITION)) AND
	(@PIN_KY_TRANSITION IS NULL OR (@PIN_KY_TRANSITION IS NOT NULL AND KY_TRANSITION = @PIN_KY_TRANSITION)) AND
	(@PIN_NB_TRANSITION IS NULL OR (@PIN_NB_TRANSITION IS NOT NULL AND NM_TRANSITION = @PIN_NB_TRANSITION)) AND
	(@PIN_FG_ACTIVE IS NULL OR (@PIN_FG_ACTIVE IS NOT NULL AND FG_ACTIVE = @PIN_FG_ACTIVE)) AND
	(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

