
-- =============================================
-- Proyecto: Plaskolite
-- Author: Daniel RM
-- CREATE date: 22/07/2019
-- Description: GET POSITION USER 
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_USER_POSITION_BY_ROLE]
@PIN_NM_POSITION AS NVARCHAR(50) = NULL
		
AS 
BEGIN 

SELECT US.ID_ROLE,
		US.KY_USER,
		US.NM_USER,
		RO.KY_ROLE,
		RO.NM_ROLE,
		PO.ID_POSITION,
		PO.NM_POSITION 
FROM ADM.C_USER US
INNER JOIN ADM.C_ROLE RO ON US.ID_ROLE = RO.ID_ROLE
INNER JOIN ADM.C_EMPLOYEE E ON US.ID_EMPLOYEE=E.ID_EMPLOYEE
INNER JOIN ADM.C_POSITION PO ON E.ID_POSITION= PO.ID_POSITION

WHERE (@PIN_NM_POSITION IS NULL OR (@PIN_NM_POSITION IS NOT NULL AND PO.NM_POSITION = @PIN_NM_POSITION))  
AND  US.FG_ACTIVE=1


ORDER BY ID_ROLE
END

