-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Javier Diaz Barron
-- CREATE date: 04/04/2017
-- Description: Get Nothifications
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_NOTIFICATIONS] 
		 @ID_NOTIFICATION INT=NULL
		,@KY_USER NVARCHAR(50)= NULL
		,@ID_BRANCH_PLANT INT= NULL
		,@KY_PROCESS_TYPE NVARCHAR(10) = NULL
		,@KY_STATUS NVARCHAR(50)= NULL		
		,@DT_NOTIFICATION DATETIME= NULL
		,@DT_SENDED DATETIME= NULL
		,@DT_WAITING DATETIME= NULL
		,@DT_CLOSE DATETIME= NULL

AS 

	IF @ID_NOTIFICATION =0
		SELECT @ID_NOTIFICATION = NULL
	
	DECLARE @T_NOTIFICATION TABLE (
		ID_NOTIFICATION INT
		, KY_USER NVARCHAR(50)
		, KY_PROCESS_TYPE NVARCHAR(10)
		, KY_STATUS NVARCHAR(50)
		, XML_PROCESS_CONFIGURATION XML
		, NO_ATTEMPT_NUMBER INT
		, DS_ERROR NVARCHAR(1000)
		, DT_NOTIFICATION DATETIME
		, ID_BRANCH_PLANT INT
		, DT_SENDED DATETIME
		, DT_WAITING DATETIME
		, DT_CLOSE DATETIME
		, NO_LEVEL INT
		, FG_ATTENDED BIT
	)

	INSERT INTO @T_NOTIFICATION
   SELECT KNP.ID_NOTIFICATION as ID_NOTIFICATION		 
		, KNP.KY_USER
		, KNP.KY_PROCESS_TYPE
		, KNP.KY_STATUS
		, KNP.XML_PROCESS_CONFIGURATION
		, KNP.NO_ATTEMPT_NUMBER
		, KNP.DS_ERROR
		, KNP.DT_NOTIFICATION
		, KNP.ID_BRANCH_PLANT
		, KNP.DT_SENDED
		, KNP.DT_WAITING
		, KNP.DT_CLOSE
		, KNP.NO_LEVEL
		, KNP.FG_ATTENDED
	FROM PRD.K_NOTIFICATION_PROCESS KNP 
	--LEFT JOIN PRD.K_FORM KF ON (SELECT TOP 1 msgs.msg.value('@KY_VALUE', 'nvarchar(50)') TO_USER FROM KNP.XML_PROCESS_CONFIGURATION.nodes('NOTIFICATIONS/FORM/PARAMETERS/child::node()') msgs(msg)  WHERE msgs.msg.value('@KY_PARAMETER' , 'nvarchar(max)') = 'idKForm')  = KF.ID_K_FORM
	WHERE --ISNULL(KF.KY_STATUS_FORM ,'CREATED' ) NOT IN ('CANCELLED')
		1=1
	    AND (@ID_BRANCH_PLANT IS NULL OR (@ID_BRANCH_PLANT IS NOT NULL AND KNP.ID_BRANCH_PLANT = @ID_BRANCH_PLANT)) 
		AND (@KY_USER IS NULL OR (@KY_USER IS NOT NULL AND KNP.KY_USER = @KY_USER))
		AND (@ID_NOTIFICATION IS NULL OR (@ID_NOTIFICATION IS NOT NULL AND KNP.ID_NOTIFICATION = @ID_NOTIFICATION))
		AND (@KY_PROCESS_TYPE IS NULL OR (@KY_PROCESS_TYPE IS NOT NULL AND KNP.KY_PROCESS_TYPE = @KY_PROCESS_TYPE))
		AND (@KY_STATUS IS NULL OR (@KY_STATUS IS NOT NULL AND KNP.KY_STATUS = @KY_STATUS))
		AND (@DT_NOTIFICATION IS NULL OR (@DT_NOTIFICATION IS NOT NULL AND KNP.DT_NOTIFICATION = @DT_NOTIFICATION))
		AND (@DT_SENDED IS NULL OR (@DT_SENDED IS NOT NULL AND KNP.DT_SENDED = @DT_SENDED))
		AND (@DT_WAITING IS NULL OR (@DT_WAITING IS NOT NULL AND KNP.DT_WAITING = @DT_WAITING))
		AND (@DT_CLOSE IS NULL OR (@DT_CLOSE IS NOT NULL AND KNP.DT_CLOSE = @DT_CLOSE))
		AND NO_ATTEMPT_NUMBER < 2
			
	UPDATE KNP
	SET KY_STATUS = 'AWAIT'
	FROM PRD.K_NOTIFICATION_PROCESS KNP
	WHERE EXISTS (SELECT TOP 1 1 FROM @T_NOTIFICATION TN WHERE TN.KY_PROCESS_TYPE IN ('TELEGRAM','EMAIL') AND KNP.ID_NOTIFICATION = TN.ID_NOTIFICATION)
	 
	 
	 SELECT ID_NOTIFICATION	as ID_NOTIFICATION	 
		, KY_USER
		, KY_PROCESS_TYPE
		, KY_STATUS
		, XML_PROCESS_CONFIGURATION
		, CASE WHEN NO_ATTEMPT_NUMBER IS NULL THEN 0 ELSE NO_ATTEMPT_NUMBER END AS NO_ATTEMPT_NUMBER
		, DS_ERROR
		, DT_NOTIFICATION
		, ID_BRANCH_PLANT
		, DT_SENDED
		, DT_WAITING
		, DT_CLOSE
		, NO_LEVEL
		, FG_ATTENDED 
	 FROM @T_NOTIFICATION
	 

