-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio Díaz
-- CREATE date: 12/03/2018
-- Description: Get pallets by dates
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_PALLET_BY_DATES] 
	@PIN_ID_BRANCH_PLANT AS INT = NULL
	, @PIN_DT_INITIAL AS DATE = NULL
	, @PIN_DT_FINAL AS DATE = NULL
AS   
	SELECT KP.ID_PALLET
		, KP.NO_PALLET
		, KP.KY_STATUS
		, CPS.NM_PALLET_STATUS
		, KP.DT_INITIAL_TIME
		, KP.DT_FINAL_TIME
		, KP.NO_QUANTITY
		, WO.ID_WORK_ORDER
		, WO.NO_WORK_ORDER
		, WO.NM_ITEM

	FROM PRD.K_PALLET KP
		INNER JOIN ADM.VW_C_PALLET_STATUS CPS 
			ON CPS.KY_PALLET_STATUS = KP.KY_STATUS
		LEFT JOIN PRD.K_WORK_ORDER WO 
			ON WO.ID_WORK_ORDER = KP.ID_WORK_ORDER
		LEFT JOIN PRD.K_QA27 QA 
			ON QA.ID_QA27 = KP.ID_QA27
		LEFT JOIN PRD.C_ITEM CI 
			ON CI.ID_ITEM = WO.ID_ITEM
	WHERE KP.DT_INITIAL_TIME BETWEEN @PIN_DT_INITIAL AND @PIN_DT_FINAL
		AND (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND WO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
	ORDER BY KP.DT_INITIAL_TIME DESC

