	-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez Torres
-- CREATE date: 04/06/2018
-- Description: get all Shifts times

-- get shift per day query  DELLC 09/06/2019
-- =============================================
CREATE PROCEDURE  [PRD].[SPE_GET_SHIFT_TIME] 

	 @PIN_ID_SHIFT		INT = NULL
	,@PIN_KY_SHIFT		NVARCHAR(50) = NULL
	,@PIN_DATE DATETIME = NULL
	,@PIN_ID_BP INT
AS	
BEGIN

	DECLARE @DT_SYSTEM DATETIME
	SET @DT_SYSTEM = 
	CASE 
    WHEN @PIN_DATE IS NULL  THEN  GETDATE() ELSE @PIN_DATE END
	
	print  @DT_SYSTEM
	SELECT
		ID_SHIFT_TIME,
		KY_SHIFT_TIME,
		NM_SHIFT_TIME,
		ID_SHIFT,
		KY_SHIFT,
		NM_SHIFT,
		NO_SHIFT_TIME, 
		CONVERT(VARCHAR,  ST.INITIAL_SHIFT_TIME, 108) INITIAL_SHIFT_TIME,
		CONVERT(VARCHAR,  ST.FINAL_SHIFT_TIME, 108) FINAL_SHIFT_TIME
	FROM [ADM].[VW_C_SHIFT_TIME] ST	
	WHERE ID_BRANCH_PLANT = @PIN_ID_BP AND
		(@PIN_ID_SHIFT IS NULL OR (@PIN_ID_SHIFT IS NOT NULL AND ID_SHIFT = @PIN_ID_SHIFT))  AND 
		(@PIN_KY_SHIFT IS NULL OR (KY_SHIFT_TIME IS NOT NULL AND KY_SHIFT_TIME = @PIN_KY_SHIFT))  AND 
		--@DT_SYSTEM BETWEEN INITIAL_SHIFT_TIME AND FINAL_SHIFT_TIME
		--INITIAL_SHIFT_TIME >= @DT_SYSTEM AND  FINAL_SHIFT_TIME <= @DT_SYSTEM
		( @DT_SYSTEM BETWEEN  CONVERT(DATETIME, (CONVERT(VARCHAR(10),  @DT_SYSTEM, 101) 
		+ ' ' + CONVERT(VARCHAR(50),  ST.INITIAL_SHIFT_TIME, 108)), 101) 
		AND DATEADD(HOUR, CAST(ST.NO_SHIFT_TIME AS INT) ,CONVERT(DATETIME,((CONVERT(VARCHAR(10),@DT_SYSTEM,101))
		+ ' ' + CONVERT(VARCHAR(50),  ST.INITIAL_SHIFT_TIME, 108)), 101))) 
		--EXISTS(SELECT TOP 1 1 FROM  PRD.C_LINE_METRIC WHERE ID_PRODUCTION_LINE =KS.ID_PRODUCTION_LINE )
		

END