-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Vitek -2019
-- Author: José Donaldo LG
-- CREATE date: 08/26/2019
-- Description: Get all work order skipped per date
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_ALL_SKIPPED_WORK_ORDER_PER_DATE]
@PIN_DATE_INITTIAL DATE,
@PIN_DATE_FINAL DATE,
@PIN_ID_BP INT


--DECLARE @INIT DATE = '07-02-2019',
--		@ENDT DATE = '07-20-2019'
AS
		--IF OBJECT_ID('tempdb..#SKIPPED_TABLE') IS NOT NULL
	 --  DROP TABLE #SKIPPED_TABLE
	--CREATE TABLE #SKIPPED_TABLE(
	--DATE_TIME DATETIME,
	--WORK_ORDER INT,
	--ID_BRANCH_PLANT INT,
	--[SHIFT] VARCHAR(20),
	--PRODUCTION_LINE INT,
	--LEADMAN VARCHAR(200),
	--ITEM VARCHAR(60),
	--NM_ITEM VARCHAR(400),
	--RUN_QTY_LBS DECIMAL(13,2),
	--RUN_QTY_PCS INT,
	--PROBLEM_AREA VARCHAR(200),
	--PROBLEM_CODE INT,
	--SYMPTOM VARCHAR(200),
	--REASON VARCHAR(400),
	--AUTHORIZER_USER VARCHAR(200))
	--;WITH table_skipped
	--AS(
	SELECT DISTINCT SWOL.DT_CREATION AS DATE_TIME,
	QA.ID_WORK_ORDER AS WORK_ORDER,
	WO.ID_BRANCH_PLANT AS ID_BRANCH_PLANT,
	SUBSTRING(KS.KY_SHIFT_TIME , 4,1) AS [SHIFT],
	WO.ID_PRODUCTION_LINE AS PRODUCTION_LINE,
	QA.NM_LEADMAN AS LEADMAN,
	IT.KY_ITEM AS ITEM,
	WO.NM_ITEM AS NM_ITEM,
	(WO.NO_POUNDS * WO.NO_BOX_QTY) AS RUN_QTY_LBS,
	WO.NO_BOX_QTY AS RUN_QTY_PCS,
	PA.KY_PROBLEM_AREA AS PROBLEM_AREA,
	PC.KY_PROBLEM_CODE AS PROBLEM_CODE,
	ISNULL(SWOL.ID_ISSUE , '' ) AS SYMPTOM,
	SWOL.DS_EXPLANATION AS REASON,
	SWOL.KY_AUTHORIZER_USER AS USER_AUTHORIZER
	FROM PRD.K_QA27 QA 
	INNER JOIN PRD.K_SKIPPED_WORK_ORDER_LOG SWOL ON QA.ID_QA27 = SWOL.ID_QA27
	INNER JOIN PRD.K_WORK_ORDER WO ON QA.ID_WORK_ORDER = WO.ID_WORK_ORDER
	INNER JOIN C_ITEM IT ON IT.ID_ITEM = WO.ID_ITEM
	INNER JOIN PRD.K_SHIFT KS ON QA.ID_SHIFT = KS.ID_SHIFT
	INNER JOIN PRD.K_ISSUE KI ON QA.ID_QA27 = KI.ID_QA27
	INNER JOIN PRD.C_PROBLEM_CODE PC ON WO.ID_BRANCH_PLANT = PC.ID_PROBLEM_CODE
	INNER JOIN PRD.C_PROBLEM_AREA PA ON PC.ID_PROBLEM_AREA = PA.ID_PROBLEM_AREA
	WHERE  WO.ID_BRANCH_PLANT = @PIN_ID_BP AND CAST(SWOL.DT_CREATION AS DATE) BETWEEN @PIN_DATE_INITTIAL AND @PIN_DATE_FINAL
	--INSERT INTO #SKIPPED_TABLE SELECT * FROM table_skipped
	--SELECT DISTINCT * FROM #SKIPPED_TABLE

