-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Gabriel Vázquez Torres
-- CREATE date: 18/05/2018
-- Description: get all branch plants by form
-- =============================================

CREATE PROCEDURE  [PRD].[SPE_GET_PRODUCTION_LINE_PER_FORM] 
		@PIN_ID_FORM_PRODUCTION_LINE AS INT = NULL,
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_ID_FORM AS INT = NULL,
		@PIN_ID_PRODUCTION_LINE AS INT = NULL
AS

	SELECT  CFPL.[ID_FORM_PRODUCTION_LINE]
		  , CFPL.[ID_FORM]
		  , CFPL.[ID_PRODUCTION_LINE]
		  , CPL.KY_PRODUCTION_LINE
		  , CPL.NM_PRODUCTION_LINE
	FROM [PRD].[C_FORM_PRODUCTION_LINE] CFPL
		INNER JOIN PRD.C_PRODUCTION_LINE CPL 
			ON CFPL.ID_PRODUCTION_LINE = CPL.ID_PRODUCTION_LINE
	WHERE
		(@PIN_ID_FORM IS NULL OR (@PIN_ID_FORM IS NOT NULL AND CFPL.ID_FORM = @PIN_ID_FORM)) AND
		(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CPL.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT)) AND
		(@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND CFPL.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE AND NOT EXISTS (SELECT TOP 1 1 FROM PRD.K_ISSUE KI WHERE KI.KY_STATUS IN ('CREATED', 'HOLD_ON') AND KI.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE))) AND
		(@PIN_ID_FORM_PRODUCTION_LINE IS NULL OR (@PIN_ID_FORM_PRODUCTION_LINE IS NOT NULL AND CFPL.ID_FORM_PRODUCTION_LINE = @PIN_ID_FORM_PRODUCTION_LINE))
	ORDER BY CFPL.ID_PRODUCTION_LINE

