-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 15/05/2017
-- Description: get Characteristics
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_REPORT_DATA_WORK_ORDER_METRICS] 
		@PIN_ID_PRODUCTION_LINE AS int = NULL,
	    @PIN_ID_BRANCH_PLANT AS int = NULL,
		@PIN_ID_WORK_ORDER AS int = NULL,
		@PIN_ID_WORK_QA27 AS int = NULL

	AS
			 SELECT 
					CM.ID_METRICS, 
					CM.NM_METRICS, 
					XML_METRICS_VALUE.value('(/SETTINGS/FIELD_TYPES/@NOMINAL_VALUE)[1]','VARCHAR(20)') NOMINAL_VALUE,
					XML_METRICS_VALUE.value('(/SETTINGS/FIELD_TYPES/@FINISHED_VALUE)[1]','VARCHAR(20)') FINISHED_VALUE,
					FORMAT(KF.DT_FORM, 'MM/dd/yyyy hh:mm:ss tt') DT_FORM
			FROM PRD.C_METRICS CM
			LEFT OUTER JOIN PRD.K_FORM_METRICS KFM ON KFM.ID_METRICS = CM.ID_METRICS
			LEFT OUTER JOIN PRD.K_FORM KF ON KFM.ID_K_FORM = KF.ID_K_FORM
			LEFT OUTER JOIN PRD.K_SHIFT KS ON KF.ID_PRODUCTION_LINE = KS.ID_PRODUCTION_LINE AND KS.FG_STATUS = 1
			WHERE 
				  (@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND KF.ID_WORK_ORDER = @PIN_ID_WORK_ORDER )) AND 
				  (@PIN_ID_WORK_QA27 IS NULL OR (@PIN_ID_WORK_QA27 IS NOT NULL AND KF.ID_QA27 = @PIN_ID_WORK_QA27 ))

