-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 13/03/2017
-- Description: get all issue catalogs
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_ISSUE_CATALOGS] 
	    @PIN_ID_ISSUE AS int = NULL

AS   
BEGIN
	DECLARE @V_XML_POSITIONS AS XML = NULL

		, @V_KY_ISSUE AS UNIQUEIDENTIFIER = NULL
		, @V_ID_QA27 AS int = NULL
		, @V_ID_WORK_ORDER AS int = NULL
		, @V_ID_PALLET AS int = NULL
		, @V_NO_PALLET AS int = NULL
		, @V_KY_SHIFT AS nvarchar(50) = NULL
		, @V_NM_SHIFT AS nvarchar(200) = NULL

		, @V_NO_WORK_ORDER AS int =NULL
		, @V_ID_PRODUCTION_LINE AS int = NULL
		, @V_NM_PRODUCTION_LINE AS nvarchar(200) = NULL

		, @V_ID_PROBLEM_AREA AS int = NULL
		, @V_KY_PROBLEM_AREA AS nvarchar(50) = NULL
		, @V_NM_PROBLEM_AREA AS nvarchar(200) = NULL
		, @V_ID_PROBLEM_CODE AS int = NULL
		, @V_KY_PROBLEM_CODE AS nvarchar(50) = NULL
		, @V_NM_PROBLEM_CODE AS nvarchar(200) = NULL
		, @V_DS_SYMPTOM AS nvarchar(1000) = NULL
		, @V_XML_POSITIONS_INVOLVED AS XML = NULL
		, @V_DS_ISSUE_EXPLANATION_OPEN AS nvarchar(1000) = NULL
		, @V_DT_ISSUE AS DATETIME = NULL
		, @V_FG_CONFIRMED AS bit = NULL
		, @V_DT_CONFIRMED AS DATETIME = NULL
		, @V_ID_DEFECT_CATEGORY AS int = NULL
		, @V_DS_EXPLANATION_EVENT_CLOSED AS nvarchar(1000) = NULL
		, @V_DT_ISSUE_CLOSED AS DATETIME = NULL
		, @V_KY_STATUS AS nvarchar(50) = NULL
		, @V_KY_USER_INVOLVED AS nvarchar(50) = NULL
		, @V_NM_USER AS nvarchar(200) = NULL
		, @V_NM_ISSUE_STATUS AS nvarchar(200) = NULL
		, @V_FG_CAN_SKIP_WORK_ORDER AS BIT = NULL
		, @V_FG_LINE_DOWN AS BIT = NULL

		, @V_INITIAL_TIME AS TIME = NULL
		, @V_CONFIRMED_TIME AS TIME = NULL
		, @V_LOST_TIME_HRS AS int = NULL
		, @V_CLOSE_TIME AS TIME = NULL
		, @V_NO_PALLETS AS NVARCHAR(50) = NULL

		, @XML_USERS AS XML
		, @XML_CATALOGS AS XML

	SELECT @V_XML_POSITIONS = XML_POSITIONS_INVOLVED 
	FROM PRD.K_ISSUE
	WHERE ID_ISSUE = @PIN_ID_ISSUE


	SET @XML_USERS = (
		SELECT CU.KY_USER AS '@KY_USER'
			, CE.NM_FIRST_NAME + ' ' + CE.NM_LAST_NAME AS '@NM_EMPLOYEE'
		FROM ADM.C_USER CU
			INNER JOIN ADM.C_EMPLOYEE CE 
				ON CE.ID_EMPLOYEE = CU.ID_EMPLOYEE
			INNER JOIN ADM.C_POSITION CP 
				ON CP.ID_POSITION = CE.ID_POSITION
			INNER JOIN @V_XML_POSITIONS.nodes('POSITIONS/POSITION') AS T(d) 
				ON d.value('@ID_POSITION', 'INT') = CP.ID_POSITION
		FOR XML PATH ('USER'), ROOT ('USERS')
	)

	SET @XML_CATALOGS = (
		SELECT @XML_USERS
		FOR XML PATH ('CATALOGS')
	)

	SELECT @V_KY_ISSUE = KI.KY_ISSUE
		,@V_ID_QA27 = KI.ID_QA27
		,@V_ID_WORK_ORDER = KI.ID_WORK_ORDER
		,@V_ID_PALLET = 0
		,@V_NO_PALLET = 0
		,@V_NO_PALLETS = (SELECT Substring((SELECT ((', ' + RTRIM(LTRIM(KP.NO_PALLET)))) FROM PRD.K_PALLET KP WHERE KP.ID_WORK_ORDER = WO.ID_WORK_ORDER AND KP.KY_STATUS = 'WORKING' FOR XML PATH ( '' )), 3, 1000 ))
		,@V_KY_SHIFT = QA.KY_SHIFT
		,@V_NM_SHIFT = CS.NM_SHIFT

		,@V_NO_WORK_ORDER = WO.NO_WORK_ORDER
		,@V_ID_PRODUCTION_LINE = WO.ID_PRODUCTION_LINE
		,@V_NM_PRODUCTION_LINE  = PL.NM_PRODUCTION_LINE
		,@V_ID_PROBLEM_AREA = KI.ID_PROBLEM_AREA
		,@V_KY_PROBLEM_AREA = PA.KY_PROBLEM_AREA
		,@V_NM_PROBLEM_AREA = PA.NM_PROBLEM_AREA
		,@V_ID_PROBLEM_CODE = KI.ID_PROBLEM_CODE
		,@V_KY_PROBLEM_CODE = PC.KY_PROBLEM_CODE
		,@V_NM_PROBLEM_CODE = PC.NM_PROBLEM_CODE
		,@V_DS_SYMPTOM = KI.DS_SYMPTOM
		,@V_XML_POSITIONS_INVOLVED = KI.XML_POSITIONS_INVOLVED
		--@V_NM_POSITION_INVOLVED = CP.NM_POSITION,
		,@V_DS_ISSUE_EXPLANATION_OPEN = KI.DS_ISSUE_EXPLANATION_OPEN
		,@V_DT_ISSUE = KI.DT_ISSUE
		,@V_FG_CONFIRMED = KI.FG_CONFIRMED
		,@V_DT_CONFIRMED = KI.DT_CONFIRMED
		,@V_ID_DEFECT_CATEGORY = KI.ID_DEFECT_CATEGORY
		,@V_DS_EXPLANATION_EVENT_CLOSED = KI.DS_EXPLANATION_EVENT_CLOSED
		,@V_DT_ISSUE_CLOSED = KI.DT_ISSUE_CLOSED
		,@V_KY_STATUS = KI.KY_STATUS
		,@V_KY_USER_INVOLVED = KI.KY_USER_INVOLVED
		,@V_NM_USER = CU.NM_USER
		,@V_NM_ISSUE_STATUS = CIS.NM_ISSUE_STATUS
		,@V_INITIAL_TIME = CAST(KI.DT_ISSUE AS TIME )
		,@V_CONFIRMED_TIME = CAST(KI.DT_CONFIRMED AS TIME)
		,@V_LOST_TIME_HRS = (CASE WHEN KI.DT_CONFIRMED IS NOT NULL THEN DATEDIFF(HOUR, KI.[DT_CONFIRMED], KI.[DT_ISSUE_CLOSED]) ELSE NULL END) 
		,@V_CLOSE_TIME = CAST(KI.DT_ISSUE_CLOSED AS TIME)
		,@V_FG_CAN_SKIP_WORK_ORDER = ISNULL(PC.FG_CAN_SKIP_WO,0) 
		,@V_FG_LINE_DOWN = ISNULL(KI.FG_LINE_DOWN, 0)
	FROM PRD.K_ISSUE KI
		LEFT OUTER JOIN PRD.K_WORK_ORDER WO 
			ON WO.ID_WORK_ORDER = KI.ID_WORK_ORDER
		LEFT OUTER JOIN PRD.C_PROBLEM_AREA PA 
			ON KI.ID_PROBLEM_AREA = PA.ID_PROBLEM_AREA
		LEFT OUTER JOIN PRD.C_PROBLEM_CODE PC 
			ON KI.ID_PROBLEM_CODE = PC.ID_PROBLEM_CODE
		LEFT OUTER JOIN ADM.VW_C_ISSUE_STATUS CIS 
			ON CIS.KY_ISSUE_STATUS = KI.KY_STATUS
		--LEFT OUTER JOIN ADM.C_POSITION CP ON CP.ID_POSITION = KI.ID_POSITION_INVOLVED
		LEFT OUTER JOIN ADM.C_USER CU 
			ON CU.KY_USER = KI.KY_USER_INVOLVED
		LEFT OUTER JOIN PRD.C_PRODUCTION_LINE PL 
			ON PL.ID_PRODUCTION_LINE = WO.ID_PRODUCTION_LINE
		--LEFT OUTER JOIN PRD.K_PALLET P ON P.ID_QA27 = KI.ID_QA27 AND P.ID_WORK_ORDER = KI.ID_WORK_ORDER
		LEFT OUTER JOIN PRD.K_QA27 QA 
			ON QA.ID_QA27 = KI.ID_QA27
		LEFT OUTER JOIN ADM.VW_C_SHIFT CS 
			ON CS.KY_SHIFT = QA.KY_SHIFT
	WHERE KI.ID_ISSUE = @PIN_ID_ISSUE

	SELECT @PIN_ID_ISSUE AS ID_ISSUE
		, @V_KY_ISSUE AS KY_ISSUE
		, @V_ID_QA27 AS ID_QA27
		, @V_ID_PALLET AS ID_PALLET
		, @V_NO_PALLET AS NO_PALLET
		, @V_NO_PALLETS AS NO_PALLETS
		, @V_KY_SHIFT AS KY_SHIFT
		, @V_NM_SHIFT AS NM_SHIFT
	
		, @V_ID_WORK_ORDER AS ID_WORK_ORDER
		, @V_NO_WORK_ORDER AS NO_WORK_ORDER
		, @V_ID_PRODUCTION_LINE AS ID_PRODUCTION_LINE
		, @V_NM_PRODUCTION_LINE AS NM_PRODUCTION_LINE
		, @V_ID_PROBLEM_AREA AS ID_PROBLEM_AREA
		, @V_KY_PROBLEM_AREA AS KY_PROBLEM_AREA
		, @V_NM_PROBLEM_AREA AS NM_PROBLEM_AREA
		, @V_ID_PROBLEM_CODE AS ID_PROBLEM_CODE
		, @V_KY_PROBLEM_CODE AS KY_PROBLEM_CODE
		, @V_NM_PROBLEM_CODE AS NM_PROBLEM_CODE
		, @V_DS_SYMPTOM AS DS_SYMPTOM
		, @V_XML_POSITIONS_INVOLVED AS XML_POSITIONS_INVOLVED
		--@V_NM_POSITION_INVOLVED AS NM_POSITION_INVOLVED,
		, @V_DS_ISSUE_EXPLANATION_OPEN AS DS_ISSUE_EXPLANATION_OPEN
		, @V_DT_ISSUE AS DT_ISSUE
		, @V_FG_CONFIRMED AS FG_CONFIRMED
		, @V_DT_CONFIRMED AS DT_CONFIRMED
		, @V_ID_DEFECT_CATEGORY AS ID_DEFECT_CATEGORY
		, @V_DS_EXPLANATION_EVENT_CLOSED AS DS_EXPLANATION_EVENT_CLOSED
		, @V_DT_ISSUE_CLOSED AS DT_ISSUE_CLOSED
		, @V_KY_STATUS AS KY_STATUS
		, @V_KY_USER_INVOLVED AS KY_USER_INVOLVED
		, @V_NM_USER AS NM_USER
		, @V_NM_ISSUE_STATUS AS NM_ISSUE_STATUS
		, @V_INITIAL_TIME AS INITIAL_TIME
		, @V_CONFIRMED_TIME AS CONFIRMED_TIME
		, @V_LOST_TIME_HRS AS LOST_TIME_HRS
		, @V_CLOSE_TIME AS CLOSE_TIME
		, @XML_CATALOGS AS XML_CATALOGS
		, @V_FG_CAN_SKIP_WORK_ORDER AS FG_CAN_SKIP_WORK_ORDER
		, @V_FG_LINE_DOWN AS FG_LINE_DOWN
END

