-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2018
-- Author: Julio Tavares	
-- CREATE date: 17/07/2018
-- Description: Get 
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_INSPECTION_SKIDS]
	  @PIN_ID_BRANCH_PLANT INT = NULL
     ,@PIN_ID_WORK_ORDER INT = NULL
	 ,@PIN_ID_PRODUCTION_LINE INT = NULL
	 ,@PIN_XML_STATUS XML = NULL
	 ,@PIN_ID_INSPECTION_SKID INT = NULL
AS   
BEGIN

	DECLARE @T_SKID_STATUS TABLE (
		KY_SKID_STATUS NVARCHAR(20)
	)

	INSERT INTO @T_SKID_STATUS (KY_SKID_STATUS)
	SELECT x.ref.value('@KY_STATUS', 'VARCHAR(25)') KY_STATUS_SKID FROM @PIN_XML_STATUS.nodes('/STATUS/ST') x(ref)

	SELECT PL.NM_PRODUCTION_LINE
		, WO.ID_PRODUCTION_LINE 
		, WO.ID_WORK_ORDER
		, WO.NO_WORK_ORDER
		, WO.NM_CUSTOMER
		, WO.KY_STATUS AS KY_STATUS_WORK_ORDER
		, CI.KY_ITEM
		, CI.NM_ITEM
		, KIS.NO_PALLET
		, KIS.KY_STATUS
		, PS.NM_PALLET_STATUS
		, CAST(WO.NO_QTY_SKID AS INT) AS NO_QUANTITY
		, KIS.ID_INSPECTION_SKID
		, KP.ID_PALLET
		, KIS.FG_INSPECTOR_AGREEMENT
		, KIS.ID_QUALITY_INSPECTOR
		, KIS.NM_QUALITY_INSPECTOR
		, KIS.DT_INSPECTOR_AGREEMENT
		, KIS.KY_USER_INSPECTOR
		, KIS.DS_EXPLANATION_AGREEMENT
		, ISNULL(KIS.DT_INSPECTION_CREATED, KIS.DT_CREATION) AS DT_INSPECTION_CREATED
	  FROM PRD.K_INSPECTION_SKID KIS
		INNER JOIN PRD.K_WORK_ORDER WO 
			ON KIS.ID_WORK_ORDER = WO.ID_WORK_ORDER
		INNER JOIN PRD.C_PRODUCTION_LINE PL 
			ON WO.ID_PRODUCTION_LINE = PL.ID_PRODUCTION_LINE
		INNER JOIN PRD.C_ITEM CI 
			ON WO.ID_ITEM = CI.ID_ITEM
		INNER JOIN ADM.VW_C_PALLET_STATUS PS 
			ON KIS.KY_STATUS = PS.KY_PALLET_STATUS
		INNER JOIN @T_SKID_STATUS SS 
			ON KIS.KY_STATUS = SS.KY_SKID_STATUS
		LEFT JOIN PRD.K_PALLET KP 
			ON KIS.NO_PALLET = KP.NO_PALLET 
			AND KIS.ID_WORK_ORDER = KP.ID_WORK_ORDER
		

	 WHERE (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND WO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
	   AND (@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND WO.ID_WORK_ORDER = @PIN_ID_WORK_ORDER))
	   AND (@PIN_ID_PRODUCTION_LINE IS NULL OR (@PIN_ID_PRODUCTION_LINE IS NOT NULL AND WO.ID_PRODUCTION_LINE = @PIN_ID_PRODUCTION_LINE))
	   AND (@PIN_ID_INSPECTION_SKID IS NULL OR (@PIN_ID_INSPECTION_SKID IS NOT NULL AND KIS.ID_INSPECTION_SKID = @PIN_ID_INSPECTION_SKID))
	ORDER BY KIS.DT_CREATION ASC
END

