-- =============================================
-- Proyect: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Julio César Tavares
-- CREATE date: 28/03/2017
-- Description: get all USERS SCALING
-- =============================================
CREATE PROCEDURE    [PRD].[SPE_GET_POSITION_SCALING] 
		@PIN_ID_POSITION_SCALING AS INT = NULL,
		@PIN_ID_PROBLEM_CODE AS INT = NULL,
		@PIN_ID_FORM AS INT = NULL,
		@PIN_NM_FORM AS VARCHAR(50) = NULL,
		@PIN_ID_POSITION AS INT = NULL,
		@PIN_KY_LEVEL_TYPE AS VARCHAR(10) = NULL,
		@PIN_NO_TIME_HOLD_ON AS INT = NULL,
		@PIN_ID_BRANCH_PLANT AS INT = NULL
AS   
	SELECT KUS.ID_POSITION_SCALING,
		   KUS.ID_PROBLEM_CODE,
		   KUS.ID_FORM, 
		   CF.NM_FORM,
		   CP.ID_POSITION,
		   CP.KY_POSITION,
		   CP.NM_POSITION,
		   CP.ID_BRANCH_PLANT ID_BRANCH_PLANT_POSITION,
		   KUS.KY_LEVEL_TYPE,
		   KUS.NO_TIME_HOLD_ON
		
		FROM PRD.K_POSITION_SCALING KUS
		JOIN PRD.C_FORM CF ON KUS.ID_FORM = CF.ID_FORM
		JOIN ADM.C_POSITION CP ON KUS.ID_POSITION = CP.ID_POSITION
					
  	   WHERE (@PIN_ID_POSITION_SCALING IS NULL OR (@PIN_ID_POSITION_SCALING IS NOT NULL AND KUS.ID_POSITION_SCALING = @PIN_ID_POSITION_SCALING)) AND 
			 (@PIN_ID_PROBLEM_CODE IS NULL OR (@PIN_ID_PROBLEM_CODE IS NOT NULL AND KUS.ID_PROBLEM_CODE = @PIN_ID_PROBLEM_CODE)) AND
			 (@PIN_ID_FORM IS NULL OR (@PIN_ID_FORM IS NOT NULL AND KUS.ID_FORM = @PIN_ID_FORM)) AND
			 (@PIN_NM_FORM IS NULL OR (@PIN_NM_FORM IS NOT NULL AND CF.NM_FORM = @PIN_NM_FORM)) AND
			 (@PIN_KY_LEVEL_TYPE IS NULL OR (@PIN_KY_LEVEL_TYPE IS NOT NULL AND KUS.KY_LEVEL_TYPE = @PIN_KY_LEVEL_TYPE)) AND
			 (@PIN_ID_POSITION IS NULL OR (@PIN_ID_POSITION IS NOT NULL AND KUS.ID_POSITION = @PIN_ID_POSITION)) AND
			 (@PIN_KY_LEVEL_TYPE IS NULL OR (@PIN_KY_LEVEL_TYPE IS NOT NULL AND KUS.KY_LEVEL_TYPE = @PIN_KY_LEVEL_TYPE)) AND
			 (@PIN_NO_TIME_HOLD_ON IS NULL OR (@PIN_NO_TIME_HOLD_ON IS NOT NULL AND KUS.NO_TIME_HOLD_ON = @PIN_NO_TIME_HOLD_ON)) AND
			 (@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND CP.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))

ORDER BY KUS.KY_LEVEL_TYPE

