-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Vitek - 2019
-- Author: Jose Donaldo LG
-- CRETAE date: 08/29/2019
-- Description: get item and production line by date and shift
-- =============================================
-- 01/08/2020 : Modify dates to get items correctly.
-- =============================================
CREATE PROCEDURE [PRD].[SPE_GET_ITEM_AND_PRODUCTION_LINE] 

	 @ENDT DATETIME,-- DATA REQUIRED 
	 @KYSHIFT VARCHAR(200), -- DATA REQUIRED
	 @BP INT 
AS
BEGIN
	    DECLARE 
		--@INIT DATETIME,
		 @DT_1       DATETIME, -- Fecha inicio
		 @DT_2       DATETIME, -- Fecha fin
		 @WEIGHT DECIMAL(13,2),
	     @FECHA_GENERACION_REPORTE DATE = CONVERT(DATE, GETDATE()),
		 @VALUE_PRODUCED_TOTAL DECIMAL(10,2),
		 @VALUE_GROSS_LINE DECIMAL(10,2),
		 @TOTAL_SHIFT_SAVING DECIMAL(10,2)
		-- ///
		 DECLARE @INIT_TIME AS DATETIME = (SELECT INITIAL_SHIFT_TIME FROM ADM.VW_C_SHIFT
												WHERE KY_SHIFT = @KYSHIFT)
           DECLARE @END_TIME AS DATETIME = (SELECT FINAL_SHIFT_TIME FROM ADM.VW_C_SHIFT
												WHERE KY_SHIFT = @KYSHIFT)
			SET @DT_1 = CONVERT(DATETIME, @ENDT) + CONVERT(DATETIME, @INIT_TIME)
			SET @DT_2 = CONVERT(DATETIME, @ENDT) + CONVERT(DATETIME, @END_TIME)
		 -- ///

IF OBJECT_ID('tempdb..#RUNNING_HRS') IS NOT NULL
	   DROP TABLE #RUNNING_HRS
	CREATE TABLE #RUNNING_HRS(
	ID_PRODUCTION_LINE INT,
	CARTON VARCHAR(200),
    SCRAP_CARTON INT,
	FILM VARCHAR(10),
	ID_ITEM INT,
	NM_ITEM VARCHAR(200),
	KY_ITEM VARCHAR(200),
	ID_WORK_ORDER INT)
	;WITH running_hrs
	as
 	(SELECT W.ID_PRODUCTION_LINE, 
   CASE WHEN (SELECT TOP 1 NM_CARTON FROM PRD.K_WORK_ORDER_CARTON KWC WHERE KWC.ID_QA27 = Q.ID_QA27 ORDER BY KWC.DT_CREATION DESC) <> 'Null' THEN 'YES' ELSE 'NO' END NM_CARTON,

    (SELECT SUM (NO_SCRAP)
	 FROM PRD.K_WORK_ORDER_CARTON WO_CARTON 
	 WHERE WO_CARTON.ID_QA27 = Q.ID_QA27 GROUP BY ID_QA27) AS NO_SCRAP,

	 CASE WHEN (SELECT TOP 1 KFT.TOP_SIDE FROM PRD.K_FILM_TRACK KFT WHERE KFT.ID_QA27 = Q.ID_QA27 ORDER BY KFT.DT_CREATION DESC)  <> 'Null' THEN 'YES'
		  WHEN (SELECT TOP 1 KFT.BOTTOM_SIDE FROM PRD.K_FILM_TRACK KFT WHERE KFT.ID_QA27 = Q.ID_QA27 ORDER BY KFT.DT_CREATION DESC)  <> 'Null' THEN 'YES' 
		  ELSE 'NO' END AS FILM,
	-- datediff convierte las fechas a minutos despues es dividido por 60 para convertir a horas
	W.ID_ITEM, W.NM_ITEM, IT.KY_ITEM, W.ID_WORK_ORDER FROM PRD.K_QA27 Q
	INNER JOIN PRD.K_WORK_ORDER W ON Q.ID_WORK_ORDER = W.ID_WORK_ORDER
	INNER JOIN PRD.C_ITEM IT ON IT.ID_ITEM = W.ID_ITEM 
		
	WHERE 
	DT_QA27 BETWEEN @DT_1 AND @DT_2 AND Q.KY_SHIFT = @KYSHIFT AND W.ID_BRANCH_PLANT = @BP
	)
	-- eso no debe de ocurrir fantasma de vitek estuvo aqui 
--	AND 
--	EXISTS
--(SELECT 1 FROM PRD.K_PALLET P  WHERE Q.ID_QA27 = P.ID_QA27))

 INSERT INTO #RUNNING_HRS SELECT * FROM running_hrs
 SELECT * FROM #RUNNING_HRS RN
 ORDER BY RN.ID_PRODUCTION_LINE
 END



