-- =============================================
-- Proyecto: Plaskolite
-- Copyright (c) - Acrux - 2017
-- Author: Juan De Dios Pérez
-- CREATE date: 07/04/2017
-- Description: get all pallets comments
-- =============================================
-- MODIFY: the work order coments add to view i the same module and column add to dentify type origin comment (skid, work order)
-- =============================================

CREATE PROCEDURE    [PRD].[SPE_GET_PALLET_COMMENT]
	    @PIN_ID_PALLET_COMMENT AS int = NULL,
	    @PIN_ID_PALLET AS int = NULL,
		@PIN_ID_WORK_ORDER AS INT = NULL,
		@PIN_ID_BRANCH_PLANT AS INT = NULL
		
AS   

			SELECT 'SKID' COMMENT_TO
			  , PC.ID_PALLET_COMMENT
			  , KP.ID_PALLET
			  , KP.ID_WORK_ORDER
			  , KP.NO_PALLET
			  , KP.KY_STATUS AS KY_STATUS_PALLET
			  , PC.DS_COMMENT
			  , PC.DT_COMMENT
			  , KWO.NO_WORK_ORDER
			  , KWO.NM_PRODUCTION_LINE
			  , KWO.KY_STATUS AS KY_STATUS_WORK_ORDER
			  , CU.NM_USER
			FROM PRD.K_PALLET KP
				INNER JOIN PRD.K_PALLET_COMMENT PC ON PC.ID_PALLET = KP.ID_PALLET
				INNER JOIN PRD.K_WORK_ORDER KWO ON KP.ID_WORK_ORDER = KWO.ID_WORK_ORDER
				INNER JOIN ADM.C_USER CU ON PC.KY_USER_APP_CREATION = CU.KY_USER
			WHERE	--(@PIN_KY_TYPE_COMMENT IS NULL OR (@PIN_KY_TYPE_COMMENT IS NOT NULL AND @PIN_KY_TYPE_COMMENT = 'WORKORDER')) AND
					(@PIN_ID_PALLET_COMMENT IS NULL OR (@PIN_ID_PALLET_COMMENT IS NOT NULL AND PC.[ID_PALLET_COMMENT] = @PIN_ID_PALLET_COMMENT)) AND
					(@PIN_ID_PALLET IS NULL OR (@PIN_ID_PALLET IS NOT NULL AND KP.[ID_PALLET] = @PIN_ID_PALLET)) AND
					(@PIN_ID_WORK_ORDER IS NULL OR (@PIN_ID_WORK_ORDER IS NOT NULL AND KP.ID_WORK_ORDER = @PIN_ID_WORK_ORDER)) AND
					(@PIN_ID_BRANCH_PLANT IS NULL OR (@PIN_ID_BRANCH_PLANT IS NOT NULL AND KWO.ID_BRANCH_PLANT = @PIN_ID_BRANCH_PLANT))
			ORDER BY PC.DT_COMMENT DESC

