CREATE TABLE [LAB].[K_READING_DEVICE_CONFIGURATION] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [NM_DEVICE]  VARCHAR (200) NULL,
    [FG_STATUS]  BIT           NULL,
    [FG_ENABLED] BIT           NULL,
    [NM_REASON]  VARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

