CREATE TABLE [LAB].[K_SAMPLE] (
    [ID_SAMPLE]                    INT           IDENTITY (1, 1) NOT NULL,
    [NO_SAMPLE]                    INT           NOT NULL,
    [DT_WIDTH]                     DATETIME      NULL,
    [ID_WIDTH_METRIC]              INT           NULL,
    [NO_WIDTH_VALUE]               FLOAT (53)    NULL,
    [DT_LENGTH]                    DATETIME      NULL,
    [ID_LENGTH_METRIC]             INT           NULL,
    [NO_LENGTH_VALUE]              FLOAT (53)    NULL,
    [DT_THICKNESS]                 DATETIME      NULL,
    [ID_THICKNESS_METRIC]          INT           NULL,
    [NO_THICKNESS_VALUE]           FLOAT (53)    NULL,
    [DT_LIGHT_TRANSMISSION]        DATETIME      NULL,
    [ID_LIGHT_TRANSMISSION_METRIC] INT           NULL,
    [NO_LIGHT_TRANSMISSION_VALUE]  FLOAT (53)    NULL,
    [DT_GLOSS]                     DATETIME      NULL,
    [ID_GLOSS_METRIC]              INT           NULL,
    [NO_GLOSS_VALUE]               FLOAT (53)    NULL,
    [DT_WEIGHT]                    DATETIME      NULL,
    [ID_WEIGHT_METRIC]             INT           NULL,
    [NO_WEIGHT_VALUE]              FLOAT (53)    NULL,
    [NO_PALLET]                    INT           NULL,
    [NO_WORK_ORDER]                INT           NULL,
    [ID_FORM]                      INT           NULL,
    [ID_K_FORM]                    INT           NULL,
    [KY_SAMPLE_STATUS]             NVARCHAR (50) CONSTRAINT [DF_K_SAMPLE_KY_SAMPLE_STATUS] DEFAULT ('CAPTURED') NULL,
    [DT_CREATION]                  DATETIME      NOT NULL,
    [DT_UPDATE]                    DATETIME      NULL,
    [KY_USER_APP_CREATION]         NVARCHAR (50) NOT NULL,
    [KY_USER_APP_UPDATE]           NVARCHAR (50) NULL,
    [NM_PROGRAM_CREATE]            NVARCHAR (50) NOT NULL,
    [NM_PROGRAM_UPDATE]            NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_SAMPLE] PRIMARY KEY CLUSTERED ([ID_SAMPLE] ASC)
);

